### ISSUE TITLE
Syntax highlighting is broken inside curly brackets ?

### ISSUE THREAD

**Issue by igorinsky** [hashicorp/vscode-terraform#1020]
## Versions

This bug is reproducible in:
 - 2.21.0 vscode-terraform version
 - 1.65.0 VSC version on Mac

Coloring inside curly brackets is broken unless additional curly brackets are added:

![image](https://user-images.githubusercontent.com/36537972/160857779-7a56a004-77f1-4b1a-9f71-d4653dae0393.png)

![image](https://user-images.githubusercontent.com/36537972/160857906-e025e08e-4c91-4299-833f-629d12a40c9f.png)

![image](https://user-images.githubusercontent.com/36537972/160858247-98eccdac-8c09-4ce6-809f-b3098b633606.png)

![image](https://user-images.githubusercontent.com/36537972/160858090-889232a3-b5eb-44c0-8b2d-432a0f23842c.png)

Seems to be related to #466, #469, #461,  #441,  #477, but it should be solved 2 years ago. Am I missing something?

**Comment by dbanck** [comment]
Hey @igorinsky! Thank you for taking the time to raise this issue.

I'm not able to reproduce it, using the mentioned VS Code and extension versions.
![CleanShot 2022-03-30 at 17 10 14](https://user-images.githubusercontent.com/45985/160868999-159d237c-fccd-4a09-bc25-d8e2bfff67a2.png)

Can you please share a list of your installed VS Code extensions? Maybe another extension claims `*.tf` files and highlights them incorrectly.
You can quickly obtain the list by running our "Generate Bug Report" command and copying the output.

![CleanShot 2022-03-30 at 17 11 51](https://user-images.githubusercontent.com/45985/160869482-4e6d6661-330e-4196-b03c-b46cf720eb28.png)
