### ISSUE TITLE
Slow on Save

### ISSUE THREAD

**Issue by leventyalcin** [hashicorp/vscode-terraform#1109]
## Versions

This bug is reproducible in:
 - [x] the **latest** version of the extension (below)
 - [x] the **latest** version of the language server (below)

### Extension

```
hashicorp.terraform@2.22.0
```

### Language Server

```
{"name":"terraform-ls","version":"0.27.0"}}
```

### VS Code

```
Version: 1.67.1 (Universal)
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:16.526Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.4.0
```

### Operating System

```
MacOS Monterey 12.3.1
```

### Terraform Version

```
Terraform v1.0.8
on darwin_amd64
```

### Steps To Reproduce

1. Set the editor Format on Save terraform
2. Make a change on file
3. Save

### Expected Behavior

Format the file and save immediately.

### Actual Behavior

 Every single time the following popup appears and saving files takes 15s to 30s every single save. 
![CCA0ABE7-6D0D-410C-A3FC-CA147ED644BA](https://user-images.githubusercontent.com/1218537/168806849-97065ca3-6a21-418e-856d-ab0a14c4eeec.jpeg)

### Additional context

`settings.json`
```json
{
    "editor.formatOnSave": true,
    "[terraform]": {
        "editor.defaultFormatter": "hashicorp.terraform",
        "editor.formatOnSave": false,
        "editor.codeActionsOnSave": {
            "source.formatAll.terraform": true
        },
    },
    "[terraform-vars]": {
        "editor.defaultFormatter": "hashicorp.terraform",
        "editor.formatOnSave": false,
        "editor.codeActionsOnSave": {
            "source.formatAll.terraform": true
        },
    },
    "files.trimTrailingWhitespace": true
}
```

I've removed all the extensions and reinstalled Hashicorp Terraform only but didn't help at all. These are the extension I currently have. 

```shell
❯ code --list-extensions --show-versions
hashicorp.terraform@2.22.0
jetmartin.bats@0.1.9
mads-hartmann.bash-ide-vscode@1.13.0
```

**Comment by radeksimko** [comment]
Hi @leventyalcin 

1. Can you share some more details about your Terraform installation? Specifically _how_ did you install it? Do you use tfenv? There's a known issue upstream which causes all commands to be delayed, see https://github.com/tfutils/tfenv/issues/196
2. Can you reproduce this with the same Terraform version downloaded from [our Homebrew tap](https://github.com/hashicorp/homebrew-tap) or directly from [here](https://releases.hashicorp.com/terraform/)?
3. Can you share the log from `Output > HashiCorp Terraform`? We're interested in any lines around `textDocument/formatting` requests and responses (and especially the requests and responses themselves).
4. Can you try formatting the same document yourself via `cat file.tf | terraform fmt -` and check how long that takes?

**Comment by leventyalcin** [comment]
I thought I searched enough but couldn't come across tfenv issue apparently. 
Standalone installation solved the problem for me.  
For the future, I'll be following tfenv issue. 

Thanks very much,
L.
