### ISSUE TITLE
Extension Setting Scope Review

### ISSUE THREAD

**Issue by jpogran** [hashicorp/vscode-terraform#1158]
As documented in https://code.visualstudio.com/api/references/contribution-points#contributes.configuration:

> A configuration setting can have one of the following possible scopes:
> - application - Settings that apply to all instances of VS Code and can only be configured in user settings.
> - machine - Machine specific settings that can be set only in user settings or only in remote settings. For example, an installation path which shouldn't be shared across machines.
> - machine-overridable - Machine specific settings that can be overridden by workspace or folder settings.
> - window - Windows (instance) specific settings which can be configured in user, workspace, or remote settings.
> - resource - Resource settings, which apply to files and folders, and can be configured in all settings levels, even folder settings.
> - language-overridable - Resource settings that can be overridable at a language level.

We currently scope all settings as `resource`. This allows a setting to be set at the User, Workspace, WorkspaceFolder levels. However we have settings that might make sense to scope to `machine` like the terraform-ls or terraform binary paths. This is especially important as this extension works locally and in remote environments like SSH, WSL, Docker, or Codespaces.

The `resource` scope does not seem to apply to our extension, because our settings do not vary between resource paths, it varies by machine.

The following settings deal with paths or concepts related to a specific machine:

```
terraform.languageServer.path
terraform.languageServer.args
terraform.languageServer.terraform.path
terraform.languageServer.terraform.logFilePath
terraform.languageServer.rootModules
terraform.languageServer.excludeRootModules
terraform.languageServer.ignoreDirectoryNames
```

This ticket should investigate scoping and determine if action is necessary.

**Comment by radeksimko** [comment]
Related to https://github.com/hashicorp/vscode-terraform/issues/187
