### ISSUE TITLE
Marketplace image reference is broken

### ISSUE THREAD

**Issue by digitarald** [hashicorp/vscode-terraform#1195]
The large banner on https://marketplace.visualstudio.com/items?itemName=hashicorp.terraform points to https://github.com/hashicorp/vscode-terraform/raw/HEAD/terraform-banner.png , which doesn't seem to exist anymore.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/8599/181589974-7ff354d8-ed29-420c-b563-0120f360727c.png">

**Comment by radeksimko** [comment]
Hi @digitarald
Thanks for the report.
We are aware of this. Unfortunately it's with Microsoft's Marketplace team and affects some other extensions too.

Feel free to subscribe to https://github.com/microsoft/vsmarketplace/issues/415 for updates.

**Comment by radeksimko** [comment]
Actually now I noticed that you work for Microsoft (according to your GitHub profile), so maybe you have access to some other channels we don't, to help us get that problem resolved? 😄

**Comment by jpogran** [comment]
I'm happy to report that publishing the latest release has made the Marketplace update the cached page and it now renders correctly.
