### ISSUE TITLE
terraform.languageServer.terraform.path doesn't work

### ISSUE THREAD

**Issue by sidewinder12s** [hashicorp/vscode-terraform#1212]
### Extension

```
2.24.0
```

### VS Code

```
Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:25.715Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.4.0-124-generic
```

### Operating System

```
Ubuntu 18.04.6 LTS \n \l
```

### Terraform Version

```
v0.14.10
```

My old config for finding it was:

```json
    "terraform.languageServer": {
        "external": true,
        "args": [
            "serve",
            "--tf-exec",
            "/full/path/tools/bin/terraform"
        ],
        "maxNumberOfProblems": 100
    },
```

The new settings did not work and were greyed out like VSCode and the extension had no idea what it was. The logs then errored out with unable to find Terraform CLI.

**Comment by jpogran** [comment]
Did you used to define this settings at the folder (`.vscode/settings.json`) or workspace level? If so, this setting along with the other settings that deal with file paths have been set to a machine scope. This means you can only set these in your user settings or remote machine (WSL, Docker, SSH Extensions, GitHub Codespaces) settings. 

We put a list of settings that changed scope with some more information in https://github.com/hashicorp/vscode-terraform/blob/v2.24.0/docs/settings-migration.md#setting-scope

**Comment by sidewinder12s** [comment]
> Did you used to define this settings at the folder (`.vscode/settings.json`) or workspace level? If so, this setting along with the other settings that deal with file paths have been set to a machine scope. This means you can only set these in your user settings or remote machine (WSL, Docker, SSH Extensions, GitHub Codespaces) settings.
> 
> We put a list of settings that changed scope with some more information in https://github.com/hashicorp/vscode-terraform/blob/v2.24.0/docs/settings-migration.md#setting-scope

Yes this was set at the User level, not workspace (though I do have workspace settings as well)

**Comment by jpogran** [comment]
I'm able to set the setting, and it's not grayed out. Can you post a screenshot of your settings with it greyed out?

![image](https://user-images.githubusercontent.com/272569/186299212-1e7110b8-f00b-4d51-802b-7d2857ce7f22.png)

**Comment by sidewinder12s** [comment]
Here, using the latest patch version of the module.

![image](https://user-images.githubusercontent.com/1393426/186950426-8f2c7735-f705-4ea9-b8e7-e526de37e6fe.png)

**Comment by jpogran** [comment]
I'm sorry for the disconnect there. I'll add more to the documentation with links to the VS Code settings description.

I know this wasn't the best impression, but in doing this the extension now knows to use the remote path when in your Remote context, and use the User settings when on your machine. I'll try to call this out better in the docs
