### ISSUE TITLE
Extension crashing on M2 MacBook Air

### ISSUE THREAD

**Issue by bixu** [hashicorp/vscode-terraform#1224]
### Extension

```
v2.24.1
```

### VS Code

```
Version: 1.71.0
```

### Operating System

```
macOS Monterey, MacBook Air M2
```

### Terraform Version

```
terraform version
Terraform v1.2.5
on darwin_arm64

Your version of Terraform is out of date! The latest version
is 1.2.8. You can update by downloading from https://www.terraform.io/downloads.html
```

### Steps To Reproduce

1. Install extension
2. Open any `.tf` file
3. See this error in the extension output:
```
Error: spawn Unknown system error -86
	at ChildProcess.spawn (node:internal/child_process:413:11)
	at Object.spawn (node:child_process:720:9)
	at /Users/blake/Documents/Dots/.vscode/extensions/hashicorp.terraform-2.24.1-darwin-x64/out/extension.js:52:17013
```

### Expected Behavior
Language server should perform tasks embedded in extension.

### Actual Behavior
Crash/fail.
 
### Additional context
None.

**Comment by jpogran** [comment]
Do you have any settings configured for the Terraform extension? If so can you post the settings you have?

An error like that at start likely means it can't find the server

**Comment by radeksimko** [comment]
We'd be happy to assist with changing any settings, or fixing a bug, but unfortunately without more details there is nothing we can do at this point. Therefore I am going to close this issue. Feel free to reach out when you find a moment to provide more details via comment, or a new issue.

Thanks!
