### ISSUE TITLE
Is it better not to save in real time

### ISSUE THREAD

**Issue by jaychoubaby** [hashicorp/vscode-terraform#1226]
## Versions

 to new

Is it better not to save in real time.

Sometimes I just enter it accidentally, but the file has been updated and saved. I think this is very bad, and it is easy to cause the file to be confused. I hope to add a save button and save it after editing. Thank you.

**Comment by dbanck** [comment]
Hi @jaychoubaby!

I'm not sure if I understand this issue correctly. Neither Terraform VS Code extension nor the Terraform language server triggers a file save.

There is a feature in VS Code to auto-save files. Do you happen to have turned that one on? You can control it via the File menu on any platform.

<img width="165" alt="CleanShot 2022-09-06 at 10 42 47@2x" src="https://user-images.githubusercontent.com/45985/188589650-d4d2f23d-cff5-4c3d-ac07-f5f1df79e9f5.png">

Or are you editing files outside VS Code, and that platform auto-saves?

**Comment by radeksimko** [comment]
We'd be happy to assist with changing any settings, or fixing a bug, but unfortunately without more details there is nothing we can do at this point. Therefore I am going to close this issue. Feel free to reach out when you find a moment to provide more details via comment, or a new issue.

Thanks!
