### ISSUE TITLE
Command "Enable Language Server" doesn't work

### ISSUE THREAD

**Issue by dbanck** [hashicorp/vscode-terraform#1232]
### Extension

```
v2.24.2
```

### VS Code

```
Version: 1.71.0
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:38.437Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 20.6.0
Sandboxed: No
```

## Steps To Reproduce

1. Run command "Terraform: Disable Language Server"
2. Hit Reload
3. Run command "Terraform: Enable Language Server"

### Expected Behavior
Language Server should be enabled and the user prompted to reload the editor

### Actual Behavior
<img width="268" alt="CleanShot 2022-09-09 at 11 37 29@2x" src="https://user-images.githubusercontent.com/45985/189362781-f4f2030a-3d27-4b3b-b00d-2d3d109cd841.png">

**Comment by asyrafnorafandi** [comment]
Can confirm having same issue on version >= `2.24.0`. Reverting to version `2.23.0` helped to resolve the issue for now.
