### ISSUE TITLE
Pasting into a Terraform Block opens the Terraform Registry

### ISSUE THREAD

**Issue by byitkc** [hashicorp/vscode-terraform#1233]
### Extension

```
2.24.2
```

### VS Code

```
Version: 1.71.0 (Universal)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:38.437Z (1 wk ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
```

### Operating System

```
MacOS Monterey 12.5.1 (21G83) - arm64
```

### Terraform Version

```
Terraform v1.2.9
on darwin_arm64
```

### Steps To Reproduce
1. Create a terraform block
```
resource "aws_route53_record" "example" {
  zone_id = var.zoneId
  name    = ""
  type    = "TXT"
  ttl     = 300
  records = []
}
```
2. Paste using CMD+V in the block in between the "name" quotes

Doesn't happen every time, but for some reason it will sometimes open the terraform registry.

Include any relevant Terraform configuration or project structure:

```terraform
resource "aws_route53_record" "example" {
  zone_id = var.zoneId
  name    = ""
  type    = "TXT"
  ttl     = 300
  records = []
}
```

### Expected Behavior
Paste the clipboard into the code block

### Actual Behavior
Opens Terraform Register
 
### Comments
I don't know if there is a way to disable this function as a workaround? I did see some documentation mentioning opening the registry but no mention of the shortcut how to disable that feature.

**Comment by jpogran** [comment]
Hi @byitkc, do you perhaps have any other extensions installed that modify key bindings or emulate other editors key mappings like vim? The reason I ask is that the only functionality we offer that opens the registry is [Terraform Module and Providers view](https://github.com/hashicorp/vscode-terraform#terraform-module-and-provider-explorer)

![image](https://user-images.githubusercontent.com/272569/189665910-1622c985-2dc6-4522-88c8-c96752a4d64a.png)

It could be possible something is activating the `Open Documentation Link` while you are pasting into the block in the open editor.

**Comment by byitkc** [comment]
Hey @jpogran, apologies on the late response. I believe you are right here, if there's not a shortcut built in, as I've got quite a few extensions loaded. I'm going to disable some additional extensions and test again and will re-open if I continue to run into issues.

Thank you!
