### ISSUE TITLE
Preview extension fails to load terraform-ls

### ISSUE THREAD

**Issue by adamstirk-ct** [hashicorp/vscode-terraform#1243]
### Extension

```
v2022.09.1210
```

### VS Code

```
v1.71.2
```

### Operating System

```
macOS 12.6, Apple M1 Max
```

### Terraform Version

```
Terraform v1.2.9
on darwin_arm64
```

### Steps To Reproduce

1. Download and install the preview version of the vscode terraform plugin `hashicorp.terraform-preview`
2. Restart VScode
3. This error appears `Launching server using command /Users/user/.vscode/extensions/hashicorp.terraform-preview-2022.9.1210-darwin-arm64/bin/terraform-ls failed.`

### Expected Behavior

No errors and the language server started in the background.

### Actual Behavior

This error appears `Launching server using command /Users/user/.vscode/extensions/hashicorp.terraform-preview-2022.9.1210-darwin-arm64/bin/terraform-ls failed.`

### Additional context

Listing the contents of the folder `~/.vscode/extensions/hashicorp.terraform-preview-2022.9.1210-darwin-arm64/bin/` you can see that the file is not executable.
```
total 37232
drwxr-xr-x   3 user  user    96B 28 Sep 14:21 ./
drwxr-xr-x  14 user  user   448B 28 Sep 14:21 ../
-rw-r--r--   1 user  user    18M 28 Sep 14:21 terraform-ls
```

if you `chmod +x terraform-ls` in this folder and restart VScode the language server is then started.

**Comment by radeksimko** [comment]
This should be addressed in the latest preview release, as available from https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform-preview

Thank you for the report. Do let us know if you discover any other problems in the future.

**Comment by radeksimko** [comment]
New preview release `2022.11.110` should now be available which isn't affected by this.
