### ISSUE TITLE
CTRL click -> open docs not working 

### ISSUE THREAD

**Issue by dsfrederic** [hashicorp/vscode-terraform#1245]
### Extension

```
HashiCorp Terraform
v2.24.2
```

### VS Code

```
Version: 1.72.0 (user setup)
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Date: 2022-10-04T23:20:39.912Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No
```

### Operating System

```
Edition	Windows 11 Enterprise
Version	21H2
Installed on	‎13/‎05/‎2022
OS build	22000.978
Serial number	5CG1413M91
Experience	Windows Feature Experience Pack 1000.22000.978.0
```

### Terraform Version

```
Terraform v1.2.2
```

### Steps To Reproduce

Opens terraform docs for that resources

### Actual Behavior

 Nothing

**Comment by radeksimko** [comment]
Hi @dsfrederic 
docs/links for `resource` and `data` blocks is a feature we have not yet implemented, but we're tracking it under https://github.com/hashicorp/vscode-terraform/issues/677
