### ISSUE TITLE
Intellisense not working for local block definitions

### ISSUE THREAD

**Issue by TeamDman** [hashicorp/vscode-terraform#1246]
### Extension

```
Name: HashiCorp Terraform
Id: hashicorp.terraform
Description: Syntax highlighting and autocompletion for Terraform
Version: 2.24.2
Publisher: HashiCorp
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform
```

### VS Code

```
Version: 1.72.0 (user setup)
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Date: 2022-10-04T23:20:39.912Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
```

### Operating System

```
Linux myubuntuvm2 5.15.0-1020-azure #25~20.04.1-Ubuntu SMP Thu Sep 1 19:20:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Terraform Version

```
Terraform v1.3.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.21.0
+ provider registry.terraform.io/hashicorp/azurerm v3.3.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
```

### Steps To Reproduce

1. Create a resource
2. Create a local block
3. Intellisense doesn't work for local values referencing resources

### Expected Behavior

![image](https://user-images.githubusercontent.com/9356891/195380759-18f7908f-458a-464b-9059-798abc604239.png)

![image](https://user-images.githubusercontent.com/9356891/195380214-1d5d57a5-5af8-4f49-8cf2-69511b6df7bf.png)

### Actual Behavior

 
![image](https://user-images.githubusercontent.com/9356891/195380339-f2072b77-130a-4fee-a4ad-539778d3ed26.png)

**Comment by radeksimko** [comment]
Hi @TeamDman 
It is true we don't yet support "nested expressions". In your example, the "outer expression" under `locals` is object, as indicated by the `{ ... }`. To put it very bluntly, IntelliSense currently only reliably works after the first `=`.

![Screenshot 2022-10-12 at 16 24 01](https://user-images.githubusercontent.com/287584/195383812-90089cbf-6f76-470e-8df4-037a19f2ff1f.png)
![Screenshot 2022-10-12 at 16 24 15](https://user-images.githubusercontent.com/287584/195383816-ff76f2eb-444d-4620-89ad-56396bd27a37.png)

This is all work in progress as we track it under https://github.com/hashicorp/terraform-ls/issues/496 which is in turn part of a bigger epic tracked in https://github.com/hashicorp/vscode-terraform/issues/641

As I believe this work to do is already covered in the mentioned issue, I'm going to close this one as a duplicate, but feel free to comment there, if there's anything you believe it does _not_ cover and is related.
