### ISSUE TITLE
Language server fails to start

### ISSUE THREAD

**Issue by steve-down** [hashicorp/vscode-terraform#1254]
Type: <b>Bug</b>

After the most recent update to VS Code (1.72.2), the Terraform language server fails to load, with the following message in the log:

```
Launching language server: /home/vscode/.vscode-server/extensions/hashicorp.terraform-2.24.3-linux-x64/bin/terraform-ls 
Failure to start terraform-ls. Please check your configuration settings and reload this window
[Error - <date and time>] Connection to server got closed. Server will not be restarted.
```

The following error messages are displayed: 

<img width="342" alt="screenshot" src="https://user-images.githubusercontent.com/99507170/196551250-69e6343e-262c-47ca-9ec0-c17a6dc1d1f1.png">

Extension version: 2.24.3
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1690)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.41GB (15.06GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/steve/projects/olde/infrastructure-application --remote=wsl+Ubuntu --crash-reporter-id 5c8fb19a-236a-4ded-9222-4cfc61978f43|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1689)|
|Memory (System)|15.63GB (13.97GB free)|
|VM|0%|
</details>

**Comment by GizzmoAsus** [comment]
Hey, I've been having the same issue but was able to resolve it by adding serve to the language server args list in settings.json as follows:

```
    "terraform.languageServer": {
        "enabled": true,
        "args": [
            "serve",
        ]
    },
```

**Comment by radeksimko** [comment]
@GizzmoAsus This should be the default settings as implied/set by the extension upon fresh installation, so manual changes shouldn't be necessary unless you changed it to something else in the past.

@steve-down Do you mind sharing your settings, especially the `terraform.languageServer` section, as mentioned by @GizzmoAsus ?

Thanks!

**Comment by GizzmoAsus** [comment]
@radeksimko that's interesting, mine was a clean install of the extension after picking up Terraform for the first time since it was originally released and that args setting was just an empty array in my config.

**Comment by radeksimko** [comment]
Also, assuming you are installing the latest version, this is actually outdated settings, see https://github.com/hashicorp/vscode-terraform/blob/main/docs/settings-migration.md for more

AFAIK (@jpogran correct me here if I'm wrong) we no longer add any particular settings anywhere upon installation/activation and instead rely on the default settings, which is also visible here

![Screenshot 2022-10-20 at 14 38 28](https://user-images.githubusercontent.com/287584/196964056-6559b364-a96d-497e-9f79-f45d7ce449f8.png)

So if you have nothing in your _User_ or other settings related to `terraform` then it should just work out of the box.
![Screenshot 2022-10-20 at 14 39 37](https://user-images.githubusercontent.com/287584/196964328-8a5e56c2-7146-44fd-9e18-c72385b075a1.png)

**Comment by steve-down** [comment]
> @steve-down Do you mind sharing your settings, especially the `terraform.languageServer` section, as mentioned by @GizzmoAsus ?


Here's the relevant portion of my settings.json - note that in VSCode, the "terraform.languageServer" element generates the warning "Invalid Configuration Setting", where it did not previously.

```
    "terraform.codelens.referenceCount": true,
    "terraform.languageServer.enable": true,
    "terraform.languageServer": {
        "args": [
            "serve"
        ]
    },
```

**Comment by steve-down** [comment]
Think I solved it, thanks to your help - it was a "terraform.languageServer" block inside a "settings" block inside `devcontainer.json` that was causing it - I removed it and it starts up nicely now, thanks again!

**Comment by radeksimko** [comment]
@steve-down Glad you solved it. Just to clarify - was this a publicly available `devcontainer.json`, or something you authored yourself from scratch?

The reason I ask is to understand whether we can PR a fix for a publicly available configuration snippet somewhere to help other people avoid falling into the same trap.

**Comment by steve-down** [comment]
It was publicly authored, but I added the settings section.

I don't think there's anything for you to do with this one!

**Comment by radeksimko** [comment]
Great, I am going to close this one then! Thanks.
