### ISSUE TITLE
Update extension on Open VSX Registry

### ISSUE THREAD

**Issue by ohemelaar** [hashicorp/vscode-terraform#1256]
## Problem Statement

[The extension provided on the Open VSX registry](https://open-vsx.org/extension/hashicorp/terraform) is out of date. [The account publishing this extentions](https://github.com/tf-editor-exp-ci-bot) is linked to the Hashicorp organisation, leading me to believe you can handle its update.

## Proposal

Is it possible to get an update pushed? The outdated version doesn't handle module completion well.

**Comment by dbanck** [comment]
Hi @ohemelaar!

We switched from publishing universal extension versions to platform-specific ones with the 2.21 release. The newer releases now bundle the Terraform language server for your specific platform, e.g., Windows arm64.
The Open VSX registry was (and is) still working on supporting this new kind of publishing mechanism. As a result, we ran into a few problems when trying to publish a more recent version.

You track our work and find additional context here:
* https://github.com/hashicorp/vscode-terraform/issues/379
* https://github.com/hashicorp/vscode-terraform/issues/525
* https://github.com/hashicorp/vscode-terraform/pull/1064
* https://github.com/EclipseFdn/open-vsx.org/issues/1084

As I believe this work is already covered in the mentioned issue, I'm going to close this one as a duplicate, but feel free to comment there if there's anything you believe it does not cover and is related.
