### ISSUE TITLE
Failure to start terraform-ls on fresh install with tf-exec setting

### ISSUE THREAD

**Issue by jpogran** [hashicorp/vscode-terraform#1278]
I have the same issue from installing the Terraform plugin fresh on the latest VS Code, no dev containers. It seems to be an issue with the default config adding `-tf-exec=/usr/local/bin/terraform` as an arg to the language server. A temporary workaround is to replace that with a whitespace in the settings.

_Originally posted by @richardsimko in https://github.com/hashicorp/vscode-terraform/issues/1272#issuecomment-1317494700_

**Comment by radeksimko** [comment]
@richardsimko Would you mind providing some more details about your environment and circumstances?

e.g.

 - what do you mean by "default config"? Are you implying the default configuration provided by the extension, or something else?
 - VS Code version (or clarify if you use VS Codium or any other unofficial VS Code build and what version)
 - Extension version
 - Log output

**Comment by richardsimko** [comment]
Thanks for the feedback! It seems to have been fixed now, not sure if it was config lingering from a previous version of the plugin or what it was but resetting all the settings related to the TF plugin solved it
