### ISSUE TITLE
-/aws loading issue and erroring code that's fine

### ISSUE THREAD

**Issue by vunqd** [hashicorp/vscode-terraform#1288]
Issue Description
=====

Doesn't seem to do anything and I keep getting loading issues [-/aws] and never seems to work.

Environment Information
=====

Terraform Information
-----

Version:	1.3.5
Platform:	windows_amd64
Outdated:	true
    

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.22621 |
| VSCode | 1.73.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|code-runner|formulahendry|0.11.8|
|gitlens|eamodio|13.1.1|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.6|
|kanagawa|qufiwefefwoyn|1.5.1|
|LiveServer|ritwickdey|5.7.9|
|material-icon-theme|PKief|4.22.0|
|path-autocomplete|ionutvmi|1.22.1|
|prettier-vscode|esbenp|9.10.3|
|python|ms-python|2022.18.2|
|roblox-lua-autofills|Kampfkarren|1.7.1|
|robloxlsp|Nightrains|1.6.6|
|stylelint-plus|hex-ci|0.56.6|
|stylua|JohnnyMorganz|1.4.0|
|synthwave-vscode|RobbOwen|0.1.14|
|terraform|hashicorp|2.25.1|
|terraform-advanced-syntax-highlighting|pjmiravalle|1.4.0|
|terraform-doc-snippets|run-at-scale|0.6.0|
|theme-panda|tinkertrain|1.3.0|
|vsc-community-material-theme|Equinusocio|1.4.4|
|vsc-material-theme|Equinusocio|33.6.0|
|vsc-material-theme-icons|equinusocio|2.5.0|
|vscode-icons|vscode-icons-team|12.0.1|
|vscode-pylance|ms-python|2022.11.40|
|vscode-rojo|evaera|2.1.2|
|vscodeintellicode|VisualStudioExptTeam|1.2.29|
</details>

Extension Logs
-----

> Find this from the first few lines of the relevant Output pane:
View -> Output -> 'HashiCorp Terraform'

**Comment by radeksimko** [comment]
Hi @vunqd 
Can you be a little more specific in describing what doesn't work and what are you attempting to do?

> Doesn't seem to do anything and I keep getting loading issues [-/aws] and never seems to work.

Also it may help to share the extension logs, so we can investigate further.
