### ISSUE TITLE
Wrong argument for azurerm_management_lock

### ISSUE THREAD

**Issue by dvonessen** [hashicorp/vscode-terraform#130]
The extension provides for `azurerm_management_lock` the argument `note` but actually it is called `notes`.
Is this wrong in the extension or do I have to point this issue to another place?

**Comment by mauve** [comment]
The issue is in this plugin. I am in the process of updating the completion data but it still requires some more work for it to be done, expect a fix soon though.

**Comment by paultyng** [comment]
Completion data in the https://github.com/hashicorp/terraform-ls is now provided by the provider itself, and its the same schema Terraform itself uses, so should no longer have these types of issues.
