### ISSUE TITLE
Consider on-boarding to Pre-release extensions

### ISSUE THREAD

**Issue by isidorn** [hashicorp/vscode-terraform#1303]
Hi VS Code PM here 👋 

I just noticed you have a HashiCorp Terraform extension and the HashiCorp Terraform Preview extension.
Consider on-boarding to pre-release extensions https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions

As that would be a much better user experience, and I think your preview extension will get more usage from VS Code Insiders.

Thanks

**Comment by jpogran** [comment]
Hi @isidorn, thanks for opening this issue. We have considered using the pre-release functionality, but are hesitant for several reasons.

We do see value in the automatic use in VS Code Insiders and that there would be only one extension for a user to use (and not have to switch back and forth between extensions to try new features out) as a big motivator to move to this.

However the major reason we haven't moved is the lack of support for semver pre-release tags. We have an automated release process based on git tags so moving to something like "even/odd" would mean changing our current versioning scheme and either making the process manual or significantly modifying the GitHub Action logic to detect whether a tag is pre-release or not. 

If you have time for a meeting, we can explain in more detail

**Comment by isidorn** [comment]
@jpogran thanks for the explanation, this makes sense.
I know the VS Marketplace plans to support SemVer in the future (hopefully next year) - so ideally we will then no longer have these limitations.

**Comment by isidorn** [comment]
@dbanck yes I can do that. Is it ok if I do that right away? Can you just confirm by commenting here and I can enable the transition. Thanks

**Comment by dbanck** [comment]
Let's do it! Thanks! :)

**Comment by isidorn** [comment]
Done. Should take a couple of days to kick in. Expect the migration to happen next week. Thanks for doing this 👏

**Comment by dbanck** [comment]
The separate preview extension is marked as deprecated now.

<img width="697" alt="CleanShot 2023-05-09 at 09 38 36@2x" src="https://user-images.githubusercontent.com/45985/237027734-b7d26a5b-394b-41a4-96b0-3c4de5477ee9.png">

So I'm closing this issue. Thanks again for the help.
