### ISSUE TITLE
Support azurerm_kubernetes_cluster addon_profile

### ISSUE THREAD

**Issue by lfshr** [hashicorp/vscode-terraform#131]
There is currently no highlighting for the azurerm_kubernetes_cluster.addon_profile block.

**Comment by mauve** [comment]
Thanks for your bug-report, can you please post a screenshot?

**Comment by lfshr** [comment]
@mauve  I don't really know what you're expecting? :S Create a block similar to:
```hcl
azurerm_kubernetes_cluster "test" {
    addon_profile {
        http_application_routing {
            enabled = true
        }
    }
}
```

addon_profile doesn't have any intellisense linked to it.

**Comment by lfshr** [comment]
They are new implementations that haven't made their way here yet.

**Comment by mauve** [comment]
@lfshr Thanks for responding, I will try to be clearer:

1. I am a little bit surprised about `azurerm_kubernetes_cluster "test" {` syntax, isn't it supposed to be `resource "azurerm_kubernetes_cluster" "test" {`?

2. your bug-report mentions that syntax-hightlightning is broken for your example, which seems to be correct, however changing it to `resource "azurerm_kubernetes_cluster" "test" {` works (refer: https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html)

3. It seems that the IntelliSense (Code Completion) data for `azurerm_kubernetes_cluster`) is outdated, I am working on that separately and will hopefully have a system in place which make sure that is kept up-2-date.

**Comment by paultyng** [comment]
Completion data in the [hashicorp/terraform-ls](https://github.com/hashicorp/terraform-ls) is now provided by the provider itself, and its the same schema Terraform itself uses, so should no longer have these types of issues.
