### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by jackharvey1** [hashicorp/vscode-terraform#134]
I'm unable to use the extension as the memory usage will grow to about 1.2gb before ultimately crashing.

I was unable to find any specific behaviour that causes this. Once I open VSCode and ran it in the background and when I tried to switch back it crashed. 

I saw the issue regarding high CPU usage and I didn't see this as an issue. It's at 100%, which is very high, but it stayed stable whilst the memory usage climbed. 

My colleague has reported a similar issue. We're both running Mac OS, but on different Mac models. 

I do have many terraform projects (estimate 40-50 files) in my workspace.

**Comment by mauve** [comment]
Can you try setting `terraform.indexing.enabled` to `false`? Does it behave better with indexing disabled?

Can you share your templates with me?

**Comment by jackharvey1** [comment]
Thanks for the quick reply mauve. I tried that setting but the issue persisted. I watched the memory usage climb from ~500mb to 1.54gb over 5 minutes before it crashed.

![image](https://user-images.githubusercontent.com/21218317/46529143-8e692700-c88d-11e8-96e2-39088fd77fc8.png)

All our repos are private so I'd have to check with my manager, what sort of things were you looking for so that maybe I could narrow the request down?

**Comment by jackharvey1** [comment]
Disabling Code Lens has me steady for the past 5 minutes

**Comment by jackharvey1** [comment]
I disabled index and VSCode still crashed. When I re-opened VSCode after the crash I enabled indexing & disabled code lens and I still don't have a crash.

**Comment by mauve** [comment]
disabling indexing will disable codelense as well as the codelense feature is dependent on indexing to work.

Both settings require a restart to take effect. Anyway thanks for verifying that it is the codelense feature which is causing the problem.

**Comment by jackharvey1** [comment]
I didn't know VSCode needed a restart for the settings to take effect -- that means I've had indexing disabled this whole time, not code lens. Realising this I restarted so that just code lens was disabled and the memory usage started to climb rapidly again. Once that happened I re-disabled indexing, restarted and I'm stable again, so looks like it's indexing.

**Comment by mauve** [comment]
VSCode doesn't need a restart for settings to take effect, however my plugin requires a restart for some changes to take effect (for example `terraform.indexing.enable` and `terraform.codelens.enabled` both require a restart/reload).

Just to verify it is indexing which is causing the memory usage.

Can you please check with your manager if you can share your templates with me (privately)? Would be nice to be able to debug this properly.

**Comment by Sherlock-Holo** [comment]
when I install this extension and enable it, it eat my 5G mem, after disable it, vscode memory usage becomes normal.

**Comment by Sherlock-Holo** [comment]
when I use arch official repo code(build vscode from srouce by arch linux) with this extension, the memory leak doesn't happen, but it still cause 100% CPU

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.
