### ISSUE TITLE
auto-format not working on mac

### ISSUE THREAD

**Issue by tony-kerz** [hashicorp/vscode-terraform#1341]
### Extension

```
v2.25.2
```

### VS Code

```
Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No
```

### Operating System

```
macos monterey 12.6
```

### Terraform Version

```
Terraform v1.3.8
on darwin_amd64
```

### Steps To Reproduce

open dot-tf file in visual-code edit it with inconsistent formatting and command-s to save or right-click format-document

### Expected Behavior

formatting should be adjusted

### Actual Behavior

 nothing happens to file

### Additional context

syntax highlighting looks good so plugin is partially functional

**Comment by tony-kerz** [comment]
fwiw, just verified that reverting to `v2.23.0` of vscode-terraform made formatting work again with above configuration.

**Comment by petarkolaric** [comment]
@radeksimko you've marked this as a `question`, but I believe it is a `bug`. I am experiencing the same issue.

**Comment by dbanck** [comment]
Hi! Can you check if the latest release (extension [2.26.0](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.26.0)) resolves this issue for you?

**Comment by olsemenov** [comment]
@dbanck yes, the latest version works for me, thanks
