### ISSUE TITLE
`"\*"` is shown as invalid

### ISSUE THREAD

**Issue by adesso-os** [hashicorp/vscode-terraform#1344]
### Extension

```
2.25.2
```

### VS Code

```
1.75.1
```

### Operating System

```
Windows
```

### Terraform Version

```
Terraform v1.3.9
on linux_amd64
```

### Steps To Reproduce

```
locals {
  s = regexall("\*", "*")
}
```

Include any relevant Terraform configuration or project structure:

```terraform
resource "github_repository" "test" {
  name = "vscode-terraform"
}

# etc...
```
You can use `tree` to output ASCII-based hierarchy of your project.

### Expected Behavior

A regular expression, which matches the literal `*` char is applied to the string and the result is returned.

### Actual Behavior

The extension complains that I'm illegally escaping `*`.

**Comment by dbanck** [comment]
Hi @adesso-os,

Thanks for taking the time to raise this and providing an example.

The observed behavior isn't a bug in the extension but a genuine issue with your configuration. The extension is surfacing the HCL error.

Running `terraform validate` will give you the same output:
```
❯ terraform validate
╷
│ Error: Invalid escape sequence
│ 
│   on main.tf line 3, in locals:
│    3:   s = regexall("\*", "*")
│ 
│ The symbol "*" is not a valid escape sequence selector.
```

The solution is escaping the `\`, so you use `regexall` like this: `regexall("\\*", "*")`

In HCL, there is no need to escape the `*` character, so the parser complains that `\*` is not a valid escape sequence. However, by using `\\*`, you're escaping the backslash, and `\\` will translate to a literal `\`. You can read more about [escape sequences here](https://developer.hashicorp.com/terraform/language/expressions/strings#escape-sequences).

Let me know if this solves your problem, or feel free to reopen the issue.

**Comment by adesso-os** [comment]
Ah okay, makes sense. I went with `"[*]"` as a workaround.

I was probably confused, because I looked at https://developer.hashicorp.com/terraform/language/functions/regex and that mentions to use `\*` to get a literal `*`. I scrolled past the paragraph above that points out the double-escape :(
