### ISSUE TITLE
Syntax colouring doesn't return to normal

### ISSUE THREAD

**Issue by ExcChua** [hashicorp/vscode-terraform#139]
Syntax colouring doesn't return to normal in the following example, if the  // " is not present.

```
resource "aws_lambda_function" "BackupLambda" {
    filename         = "${data.archive_file.BackupLambda.output_path}"
    function_name    = "BackupLambda-${var.network_id}-${var.region}"
    handler          = "BackupLambda" # Name of Go package after unzipping the filename above
    role             = "${aws_iam_role.iam_for_BackupLambda.arn}"
    runtime          = "go1.x"
    source_code_hash = "${data.archive_file.BackupLambda.output_sha}" # 
    timeout          = 300

    environment {
        variables = {
            NetworkId = "${var.network_id}"
        }
    }
}

# without the line below, the syntax highlighting does not return to normal
// "
# delete the line above and see the whole line below 

resource "aws_lambda_function" "normal" {

}
```

**Comment by mauve** [comment]
can you please upload a screenshot?

**Comment by EximChua** [comment]
![terraform - 1 - 2018-10-20 14_29_21- temp tf - packerbuildertencent workspace - visual studio code administrator](https://user-images.githubusercontent.com/40189902/47252373-2bbf8000-d476-11e8-868e-1d3cbc04c50a.png)
![terraform 2 - 2018-10-20 14_38_05- temp tf - packerbuildertencent workspace - visual studio code administrator](https://user-images.githubusercontent.com/40189902/47252374-2bbf8000-d476-11e8-82e6-9ee22885c326.png)

**Comment by chadasapp** [comment]
I saw/had the same bug. It's (partially?) triggered by the `=` in `variables = {`. If you remove it, you'll see the syntax highlighting work again properly. Considering both syntaxes are valid, this is a bug I think?

**Comment by aeschright** [comment]
I'm not seeing the highlighting issue in version 2.0+ of the extension, so I'm going to close this. Thanks for the report!
