### ISSUE TITLE
Implement token storage using the vscode.SecretStorage API

### ISSUE THREAD

**Issue by jpogran** [hashicorp/vscode-terraform#1397]
## Problem Statement

As a user I want to see the workspaces and runs I have permissions to view inside VS Code so I can interact with TFC while I code in my editor. To do this, I have to provide a TFC token that can be used to authenticate to the TFC instance where my workspaces are. I expect the token to be stored securely during my session

## Expected User Experience

To authenticate to TFC a user needs to provide a TFC User token. A user should be prompted to provide a token. 

This session lasts for the duration of the token lifetime, or until a user signs out. The user is able to sign out by removing their token from the current session. These operations are all performed using the familiar VS Code UI and command palette.

## Proposal

Use https://code.visualstudio.com/api/references/vscode-api#SecretStorage to store tokens and make available for https://github.com/hashicorp/vscode-terraform/issues/1396 to use it.

The following examples all use SecretStorage in slightly different ways. We need to determine if there is a need to wrap it entirely like some of them do, or if we can use it directly like the others:

- https://github.com/microsoft/vscode-extension-samples/tree/main/authenticationprovider-sample
- https://github.com/microsoft/vscode/blob/main/extensions/github-authentication/src/extension.ts
- https://github.com/microsoft/vscode/blob/main/extensions/microsoft-authentication/src/extension.ts

**Comment by dbanck** [comment]
Closed via #1421
