### ISSUE TITLE
Syntax highlighting doesn't recognize parentheses in string

### ISSUE THREAD

**Issue by cmeyertons** [hashicorp/vscode-terraform#140]
Parentheses are being highlighted white as if a part of the token:

![image](https://user-images.githubusercontent.com/19917677/47564179-c0e4cd80-d8e9-11e8-8484-03eef13a3a9d.png)

**Comment by aeschright** [comment]
This no longer appears to be an issue, in version 2.0 and up. Thanks for reporting it!
