### ISSUE TITLE
Implement List Runs

### ISSUE THREAD

**Issue by jpogran** [hashicorp/vscode-terraform#1402]
# Problem Statement

# Proposal

Provide a function or method on a class to query TFC runs. Utilize the functionality developed in https://github.com/hashicorp/vscode-terraform/issues/1400 to query. 

# Requirements

It is common to have many hundreds or thousands of runs, so filtering or searching for them will be a key user experience. This ticket should provide a way for the implementation of https://github.com/hashicorp/vscode-terraform/issues/1395 to filter or search for different runs.

In addition, this should have a way to adjust the paging number for each query. The implementation of https://github.com/hashicorp/vscode-terraform/issues/1395 will require loading a certain number of results, then asking for more.

## Documentation

TFC API calls

Documentation:
- General docs: https://developer.hashicorp.com/terraform/cloud-docs/api-docs
- Runs: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run
- List Runs: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run#list-runs-in-a-workspace

**Comment by dbanck** [comment]
Closed in https://github.com/hashicorp/vscode-terraform/pull/1416
