### ISSUE TITLE
Terraform Docs Accessible from VSCode

### ISSUE THREAD

**Issue by reskin89** [hashicorp/vscode-terraform#1432]
## Versions

v2.26.1

### Extension

```
HashiCorp Terraform v2.26.1
```

## Problem Statement

In many language extensions in VSCode, you can ctrl/command click certain reserve words/structs/data structures and it will take you to the declaration of it in the code, i.e.: if I have a method from a package in go, and I ctrl/command click it, it takes me to its declaration in that package.

Currently something like this with Terraform in VSCode is not possible.

## Expected User Experience

In Terraform, I would like the same type of functionality wherein if I ctrl/command click a resource (such as `aws_iam_role`) it either takes me in my browser, or in vscode, to the documentation for that resource, so I may easily see the examples, options, and exported outputs.

## Proposal

My proposal would be to ctrl/command click a resource name, and have the associated documentation page on the hashicorp tf website be opened.

**Comment by radeksimko** [comment]
Hi @reskin89 
Thanks for the suggestion. We already track this under https://github.com/hashicorp/vscode-terraform/issues/677 so I'm going to close this one as a duplicate.
