### ISSUE TITLE
unable to select workspace

### ISSUE THREAD

**Issue by putty808s** [hashicorp/vscode-terraform#1542]
### Extension Version

pre release

### VS Code Version

Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

### Operating System

Device name	PCACL-8MLN1V3 Processor	12th Gen Intel(R) Core(TM) i5-12500   3.00 GHz Installed RAM	16.0 GB (15.7 GB usable) Device ID	6A0044A1-49D7-475C-9C1E-3260FD353363 Product ID	00330-80000-00000-AA180 System type	64-bit operating system, x64-based processor

### Terraform Version

hashicorp cloud platform

### Steps to Reproduce

configure user token
select organization
expand workspaces
select workspace - error `"Failed to list runs in $workspacename$"`

### Expected Behavior

display workspace files

### Actual Behavior

error. no data displays

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by radeksimko** [comment]
Hi @putty808s 
While I recognise a part of that error message you reported, there must have been more details depending on the circumstance of that error. There's at least 5-6 known reasons behind such an error which we should be surfacing.

Would you mind sharing the whole error, or a screenshot of it?

https://github.com/hashicorp/vscode-terraform/blob/b43e633f80a47848f3ab7dd9d82d84dc6a43d7f9/src/providers/tfc/runProvider.ts#L214-L254

Thanks.

**Comment by putty808s** [comment]
Radek, thanks for your response. How can i view the detailed error?

[cid:26add2f2-9880-4095-bdad-6ab14f453232]

________________________________

**Comment by jpogran** [comment]
Hi @putty808s, there should be a button inside the error message window with a 'Report bug' label. Clicking that will open simultaneously the HashiCorp Cloud Output Panel with the JSON error as well as open a Github Issue in a browser. If you can copy the contents of the HashiCorp Cloud Output Panel and paste it here we would sincerely appreciate it.
