### ISSUE TITLE
vscode intellisense autocomplete is broken / stuck

### ISSUE THREAD

**Issue by Wassap124** [hashicorp/vscode-terraform#1556]
### Extension Version

v2.27.1

### VS Code Version

Version: 1.81.0 (Universal)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:40:02.782Z (1 wk ago)
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

### Operating System

macOS Ventura Version 13.4 (22F66)

### Terraform Version

Terraform v1.4.6 on darwin_arm64

### Steps to Reproduce

For some reason, I get only a specific set of suggestions, regardless of what im trying to write (what resource im configuring)

here are the suggestions i get in a `google_iam_workload_identity_pool`
![Screenshot 2023-08-15 at 8 37 40](https://github.com/hashicorp/vscode-terraform/assets/17432424/093d0794-f5eb-4d68-b23d-264b655a2a00)

here are the suggestion i get in a `fivetran_destination` (I swear it's not the same pic)
![Screenshot 2023-08-15 at 8 41 35](https://github.com/hashicorp/vscode-terraform/assets/17432424/c46aff0d-463f-4017-bd34-884cf7d29b01)

for some reason - when I go to a different repo / open project - I get some real suggestions,
this is for `aws_secretsmanager_secret_version` (see `secret_binary`)
![Screenshot 2023-08-15 at 8 42 38](https://github.com/hashicorp/vscode-terraform/assets/17432424/c16fb61c-ad57-453b-9a8c-2b1dd99b72d9)

### Expected Behavior

Get real autocomplete according to resources and their properties

### Actual Behavior

always getting the same autocomplete, regardless of where / when im trying 

### References

looks very similar to https://github.com/hashicorp/vscode-terraform/issues/1318

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by radeksimko** [comment]
Hi @Wassap124 
A few questions to help us get to the bottom of this:

1. Can you share some snippets of configuration that would help us reproduce the issue?
2. Can you share [the log](https://github.com/hashicorp/terraform-ls/blob/main/docs/TROUBLESHOOTING.md#logging)?
3. Can you clarify if in either of these folders you successfully ran `terraform init` (i.e. installed the providers) or not?
4. Can you double check for any custom settings, such as `terraform.languageServer.path` and try to remove or comment out those?
5. Related to (5) can you check for language server version in the bottom bar?
<img width="232" alt="Screenshot 2023-10-19 at 11 46 41" src="https://github.com/hashicorp/vscode-terraform/assets/287584/c65f1810-546c-43b7-a19c-8b0068c37f92">


Thanks!
