### ISSUE TITLE
No autocompletion in string interpolation

### ISSUE THREAD

**Issue by RobinFrcd** [hashicorp/vscode-terraform#1566]
### Extension Version

v2.27.2

### VS Code Version

Version: 1.82.1 (Universal)
Commit: 6509174151d557a81c9d0b5f8a5a1e9274db5585
Date: 2023-09-08T08:49:32.930Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

### Operating System

macOS Ventura 13.5.1 (client) | Pop!_OS 22.04 LTS (Server)

### Terraform Version

Terraform v1.5.7 on linux_amd64

### Steps to Reproduce

1. Go into a terraform repo from a SSH remote connection
2. Try to use auto-completion within a string
![image](https://github.com/hashicorp/vscode-terraform/assets/29704178/330218d3-9721-406c-a6c4-03e0b061de9c)
But it works fine outside the string interpolation:
![image](https://github.com/hashicorp/vscode-terraform/assets/29704178/429b1fdb-06ba-42c9-aadb-7023df5619dd)

### Expected Behavior

Autocompletion should work

### Actual Behavior

No suggestion at all

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by radeksimko** [comment]
Hi @RobinFrcd 
I can confirm we currently do not recognise template expressions (`"${ ... }"`) which indeed impacts completion the way you described.

We already track this under https://github.com/hashicorp/terraform-ls/issues/522 and we also track a list of other expression types and expression related work that's remaining under https://github.com/hashicorp/vscode-terraform/issues/641

I'm going to close this as a duplicate issue, so we keep things in one place. I'd recommend subscribing to either of these issues instead.
