### ISSUE TITLE
Valid tfvars found outside of root configuration reporting as incorrect syntax 

### ISSUE THREAD

**Issue by sheppyj** [hashicorp/vscode-terraform#1574]
### Extension Version

2.28.0

### VS Code Version

Version: 1.82.2 (Universal)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:59:47.790Z (3 wks ago)
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

### Operating System

macOS Ventura 13.6 (22G120)

### Terraform Version

Terraform v1.4.6 on darwin_arm64

### Steps to Reproduce

1. Create simple Terraform configuration
2. Create variables file environment/dev/terraform.tfvars

valid tfvars file reporting as having incorrect syntax;
![image](https://github.com/hashicorp/vscode-terraform/assets/11245924/1a67a71e-0f5e-48c7-8c1d-ede04265d4b4)

### Expected Behavior

Valid HCL tfvars aren't highlighted.

### Actual Behavior

Error;
Unexpected attribute: An attribute named "test" is not expected here Terraform

### Terraform Configuration

```terraform
output.tf
variable "test" {
    type = string
}

output "test" {
  value       = var.test
}

environment/dev/terraform.tfvars
test = "hello"
```

### Project Structure

```sh
.
├── environment
│   └── dev
│       └── terraform.tfvars
└── output.tf
```

### Workarounds

Dragging and dropping tfvars into root directory appear to work, syntax highlighting seems to behave as expected.

Reverting to previous version of extension 2.27.2

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by radeksimko** [comment]
We actually _already_ ignore non-autoloaded `*.tfvars`, which can be demonstrated below:

![Screenshot 2023-10-05 at 17 50 11](https://github.com/hashicorp/vscode-terraform/assets/287584/b1a8f475-63ad-4615-9136-cf8f3db7227d)

Admittedly we still compute the diagnostics in this case [but avoid publishing them](https://github.com/hashicorp/terraform-ls/blob/444fce38ece0d080175220123015a30f461472be/internal/langserver/handlers/hooks_module.go#L160). It's not a user-visible problem right now nonetheless.

--- 

What we do not account for however is a situation of a `*.tfvars` files with "autoloaded naming convention" (i.e. `terraform.tfvars` or `*.auto.tfvars`) in a random place which is _not_ a module. That seems like a totally reasonable use case / naming, so we should account for it!

I have a patch which seems to be addressing the problem based on quick manual testing:

 - https://github.com/hashicorp/terraform-ls/pull/1447

![Screenshot 2023-10-05 at 17 56 20](https://github.com/hashicorp/vscode-terraform/assets/287584/b4780d9e-da98-49f9-a028-9996a3affaf4)

I will post update when it gets merged & reaches a release.

**Comment by radeksimko** [comment]
A new version [2.28.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.28.1) was just released. This fixes the reported bug. The update should appear automatically in VS Code.

Thank you for the timing and level of detail in your report @sheppyj

--- 

In case you experience any different validation related bug, please do let us know through a new issue.

**Comment by ufonalim** [comment]
@radeksimko I've same issue with *.tfvars' "Unexpected attribute" outside of module. plugin version is 2.28.2, what else I can check?

**Comment by radeksimko** [comment]
@ufonalim Please file a new issue and attach more details, we'll be happy to look into it.

Just because the error message is the same does not always mean it's (a) the same bug, or (b) it is a bug at all.

Thanks!
