### ISSUE TITLE
v2.28.0 - "cloud" block says "organization" is required - but it is not and it is highlighted as an issue

### ISSUE THREAD

**Issue by scott-doyland-burrows** [hashicorp/vscode-terraform#1577]
### Extension Version

v2.28.0

### VS Code Version

1.82.2

### Operating System

Windows 10 (using WSL)

### Terraform Version

1.6.0

### Steps to Reproduce

Create a ```cloud``` block as below and it shows an issue:

![image](https://github.com/hashicorp/vscode-terraform/assets/61512176/f8f9046f-98ef-4694-9c8e-5f94b5da7e32)

This was working perfectly in previous versions.

### Expected Behavior

The ```cloud``` block can use the environment variable ```TF_CLOUD_ORGANIZATION``` to obtain the ```organization``` value - which is what we use in all our terraform code.

The vscode terraform extension should not expect an ```organization``` defined in the ```cloud``` block.

### Actual Behavior

![image](https://github.com/hashicorp/vscode-terraform/assets/61512176/f8f9046f-98ef-4694-9c8e-5f94b5da7e32)

### Terraform Configuration

```terraform
terraform {
  cloud {
  }
}
```

### Project Structure

```sh
N/A
```

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by radeksimko** [comment]
Hi @scott-doyland-burrows 
Thanks for the report.

I can see that both `organization` and `workspaces` are documented as required at https://developer.hashicorp.com/terraform/cli/cloud/settings#organization

Do you mind expanding on why do you believe they are not required?

**Comment by radeksimko** [comment]
Oh I have missed part of your issue - I shall read more carefully - I can see it now!

> The cloud block can use the environment variable TF_CLOUD_ORGANIZATION to obtain the organization value - which is what we use in all our terraform code.

**Comment by radeksimko** [comment]
This should be a relatively simple fix of swapping `IsOptional` for `IsRequired` [here](https://github.com/hashicorp/terraform-schema/blob/478ebd8e912526660047f28ab9b15bac4c194fef/internal/schema/1.1/terraform.go#L26) and I'll look into updating the docs as well to reflect this.

Thanks again for the report.

**Comment by scott-doyland-burrows** [comment]
Thanks, both organization and workspace can be set via envars.

**Comment by radeksimko** [comment]
https://github.com/hashicorp/terraform-schema/pull/271 has a patch (now pending review). I will post update here once we get it merged & released (hopefully soon).

**Comment by radeksimko** [comment]
A new version [2.28.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.28.1) was just released. This fixes the reported bug. The update should appear automatically in VS Code.

Thank you for the detailed report @scott-doyland-burrows and sorry for mis-reading it initially.

--- 

In case you experience any different validation related bug, please do let us know through a new issue.

**Comment by scott-doyland-burrows** [comment]
Brilliant - thanks.
