### ISSUE TITLE
`terraform_remote_state` `config` incorrectly flagged with errors

### ISSUE THREAD

**Issue by gdmoore85** [hashicorp/vscode-terraform#1580]
### Extension Version

v2.28.1

### VS Code Version

Version: 1.82.2 (Universal)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:59:47.790Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

### Operating System

macOS Ventura 13.6

### Terraform Version

Terraform v1.5.7 on darwin_arm64

### Steps to Reproduce

Creating remote datasource generates unexpected attribute errors. This does not generate an error in v2.27.2.
![Screenshot 2023-10-06 at 3 05 39 PM](https://github.com/hashicorp/vscode-terraform/assets/48772443/d139d496-a76a-4894-9006-1d2b2aa97d33)

### Expected Behavior

Would expect extension to not generate error.

### Actual Behavior

Unexpected attribute error is generated

### Workarounds

None as this does not impact the terraform run

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ghs** [comment]
Same issue as https://github.com/hashicorp/vscode-terraform/issues/1579

**Comment by radeksimko** [comment]
Thank you for the report @gdmoore85 

I was able to reproduce this with Terraform CLI uninstalled.

<img width="1017" alt="Screenshot 2023-10-09 at 09 59 30" src="https://github.com/hashicorp/vscode-terraform/assets/287584/6f31d579-78e1-44dd-b86e-a97b2b211a4c">

```hcl
data "terraform_remote_state" "name" {
  backend = "remote"
  config = {
    organization = "value"
  }
}
```

--- 

I can confirm this is indeed a bug and will investigate it further and hopefully find a fix.

While we investigate, you can either install Terraform CLI (e.g. via `brew install hashicorp/tap/terraform`) or temporarily disable the validation via `"terraform.validation.enableEnhancedValidation": false` in settings.

**Comment by radeksimko** [comment]
I have two PRs resolving the bug, which are both currently pending review:
 - https://github.com/hashicorp/terraform-ls/pull/1453
 - https://github.com/hashicorp/terraform-schema/pull/275

We will post updates when they reach a release.

**Comment by dbanck** [comment]
A new version [2.28.2](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.28.2) was just released. This fixes the reported bug. The update should appear automatically in VS Code.

Thank you for the the report @gdmoore85 

--- 

In case you experience any different validation related bug, please do let us know through a new issue.
