### ISSUE TITLE
"config/terraform/*.tf" locals are ignored since v2.28.0

### ISSUE THREAD

**Issue by alexpilon666** [hashicorp/vscode-terraform#1584]
### Extension Version

v2.28.1

### VS Code Version

Version: 1.83.0
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:11:49.843Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-86-generic

### Operating System

Kubuntu 22.04.3 LTS

### Terraform Version

Terraform v1.6.0 on linux_amd64

### Steps to Reproduce

1. Create file named `terraform/config/common.tf` at the root of your repository. This file contains multiple `local` variables, one of which being `environment` with a value of `dev`
2. Create a terraform stack (we use Terraspace) in `app/stacks/test` and create a `locals.tf` file.
3. In `locals.tf`, create a local value `test=local.environment`
4. VSCode's Terraform extension will underline in red the `local.environment` declaration in `locals.tf` with the error `No declaration found for "local.environment" Terraform`

### Expected Behavior

Nothing should be underlined and declared as an error, as the `environment` local variable has been declared in `terraform/config/common.tf`. 

### Actual Behavior

Every reference to a local variable from `terraform/config/common.tf` now creates an error in VSCode. We have almost 100 stacks in Terraform/Terraspace right now, and those stacks always use one or more references to local variables from `terraform/config/common.tf`, meaning all of our stacks are shown in red in VSCode due to this.

This was not a problem prior to v2.28.0 of the extension.

### Terraform Configuration

```terraform
#config/terraform/common.tf
locals {
  environment = "dev"
}

#app/stacks/test/locals.tf
locals {
  test=local.environment
}
```

### Project Structure

```sh
.
├── app
│   └── stacks
│       ├── test
│       │   ├── locals.tf
├── config
│   ├── app.rb
│   └── terraform
│       ├── backend.tf
│       ├── common.tf
│       └── provider.tf
└── Terrafile
```

### Anything Else?

N/A

### Workarounds

N/A

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by radeksimko** [comment]
This looks like a situation very similar to one explained in https://github.com/hashicorp/vscode-terraform/issues/1581 where locals aren't available. Correct me if I misunderstood.

Regardless of the exact reasons - whether that's internal or any other tooling such as Terraspace - this is not how locals were designed to be used. This is a use case for variables as I tried to explain in my earlier comment in https://github.com/hashicorp/vscode-terraform/issues/1581#issuecomment-1753028165

The extension (and the language server) will always aim to mimic Terraform CLI's own behaviours as closely as possible and missing local values would be raised as errors there too if you run any `terraform` command which involves configuration (init, plan, apply, destroy, validate, ...).

All that said, we have previously discussed the possibility of making various validations configurable - I will create an issue to track that feature so we at least formalise the idea and link here for more context.

The best workaround I can offer you right now is to use this option which turns off all validations, except for HCL:

```hcl
"terraform.validation.enableEnhancedValidation": false,
```

You can read more about the difference between enhanced validation and HCL at https://github.com/hashicorp/terraform-ls/blob/main/docs/validation.md

On a semi-related note, we have [recently announced stacks](https://www.hashicorp.com/blog/new-terraform-testing-and-ux-features-reduce-toil-errors-and-costs) among other features, which are currently available in private beta. You can also [watch the keynote](https://live.hashiconf.com/on-demand/ea133c4d-abf5-465f-a960-c8ebce71fc40) (the feature is covered from `31:20` mark).

**Comment by radeksimko** [comment]
I have yet to create the issue for configurable validations but for now I'm going to close this issue as I believe it describes the same problem as https://github.com/hashicorp/vscode-terraform/issues/1581
