### ISSUE TITLE
Keywords are not shown when invoking completions explicitly

### ISSUE THREAD

**Issue by ArthurCentaurea** [hashicorp/vscode-terraform#1588]
### Extension Version

v2.28.1

### VS Code Version

Version: 1.83.0 (user setup)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:12:16.321Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

### Operating System

Linux 5.15.90.1-microsoft-standard-WSL2

### Terraform Version

Terraform v1.5.7 on linux_amd64

### Steps to Reproduce

Code snippet:
```tf
resource "newrelic_nrql_alert_condition" "test" {
  open_violation_on_expiration = $$
}
```
Explicitly invoke completions at `$$` by pressing `Ctrl + Space` and start typing

### Expected Behavior

`true` and `false` keywords are in the completion list

### Actual Behavior

They are not:
![Code_ZMSVySMJ9k](https://github.com/hashicorp/vscode-terraform/assets/143425365/352da130-5c83-4506-8e0d-b10426921d55)
Here i fist invoke completions by pressing `Ctrl + Space` and observe no keywords. Then I just start typing and keywords appear in the list

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by radeksimko** [comment]
Hi @ArthurCentaurea 
I was not able to reproduce the bug. See my attached screen recording below.

https://github.com/hashicorp/vscode-terraform/assets/287584/1e206fed-7864-4f2d-9815-c2665f9a52ab

--- 

A few questions to help us get to the bottom of this:

1. Can you confirm you have the corresponding `newrelic` entry under `required_providers`? This is how we know which provider does the resource belong to and can provide relevant completion.
2. Can you confirm the version of LS (language server) in the bottom bar is 0.32.1, as shown on my recording?
3. With the above done, can you provide us [the whole log](https://github.com/hashicorp/terraform-ls/blob/main/docs/TROUBLESHOOTING.md#stderr-default) (after attempting the completion)?

Thanks!

**Comment by ArthurCentaurea** [comment]
Well, I never thought this can be a thing, but it seems that this bug repros only with a very specific file structure and their content.
I created a separate test directory with 2 files: `variables.tf` and `main.tf`.
Content of `variables.tf`:
```tf
variable "newrelic_user_key" {
  type        = string
  description = "New Relic's user API key (prefixed with 'NRAK')"
  sensitive   = true
}

variable "newrelic_account_id" {
  type        = number
  description = "New Relic account ID"
  sensitive   = true
}

variable "newrelic_host" {
  type        = string
  description = "New Relic host for which we want to configure alerting"
}

variable "newrelic_alert_email" {
  type        = string
  description = "Email which will recieve alerts from New Relic"
}
```
Content of `main.tf`:
```tf
terraform {
  required_providers {
    newrelic = {
        source = "newrelic/newrelic"
    }
  }
}

resource "newrelic_infra_alert_condition" "cpu_usage" {
  policy_id   = newrelic_alert_policy.alert_policy.id
  name        = "GitLab CPU usage"
  type        = "infra_metric"
  event       = "SystemSample"
  select      = "cpuPercent"
  comparison  = "above"
  where       = "(`hostname` = '${var.newrelic_host}')"
  
  critical {
    duration      = 5
    value         = 80
    time_function = "all"
  }
}

resource "newrelic_infra_alert_condition" "ram_usage" {
  policy_id   = newrelic_alert_policy.alert_policy.id
  name        = "GitLab RAM usage"
  type        = "infra_metric"
  event       = "SystemSample"
  select      = "memoryUsedPercent"
  comparison  = "above"
  where       = "(`hostname` = '${var.newrelic_host}')"
  
  critical {
    duration      = 5
    value         = 80
    time_function = "all"
  }
}

resource "newrelic_infra_alert_condition" "disk_usage" {
  policy_id   = newrelic_alert_policy.alert_policy.id
  name        = "GitLab disk usage"
  type        = "infra_metric"
  event       = "SystemSample"
  select      = "diskUsedPercent"
  comparison  = "above"
  where       = "(`hostname` = '${var.newrelic_host}')"
  
  critical {
    duration      = 5
    value         = 90
    time_function = "all"
  }
}

resource "newrelic_nrql_alert_condition" "backup_watcher" {
  policy_id = newrelic_alert_policy.alert_policy.id
  name      = "GitLab backup watcher"
  expiration_duration = 86400 # 24 hours in seconds
  open_violation_on_expiration = 
  close_violations_on_expiration = true

  nrql {
    query   = "SELECT count(*) FROM GitLabBackup"
  }

  critical {
    operator              = "below"
    threshold             = 1
    threshold_duration    = 300
    threshold_occurrences = "ALL"
  }
}

resource "newrelic_alert_channel" "email_channel" {
  name = "Email Channel"
  type = "email"
  
  config {
    recipients  = var.newrelic_alert_email
    include_json_attachment = "1"
  }
}

resource "newrelic_alert_policy_channel" "policy_email_channel" {
  policy_id  = newrelic_alert_policy.alert_policy.id
  channel_ids = [newrelic_alert_channel.email_channel.id]
}
```
Init terraform by running `terraform init`
Go to line 61 and explicitly invoke completions after `=`
Start typing `tru`. You won't see `true` keyword completion there

What is incredibly weird is the fact that `false` is shown even when completions invoked explicitely, while in my original case it isn't shown either. I've already shared too much of my code and i don't think I can share more. But I guess, the underlying issue is responsible for both bugs.

![Code_RnKqxFl1ij](https://github.com/hashicorp/vscode-terraform/assets/143425365/14162e48-2fef-4cd0-93d3-866fb4952c41)

The version of the LS is `0.32.1`. I don't wont to share logs publicly yet since you should be able to repro the bug with instructions above and logs contain a lot of sensetive data AFAICT (at least a lot of my local paths)

**Comment by radeksimko** [comment]
I tried to follow your instructions as precisely as possible and I'm still unable to reproduce the issue. To be clear I'm not necessarily implying there isn't a bug, but simply that if we're unable to reproduce it, we are unable to fix it.

See my new attempt below.


https://github.com/hashicorp/vscode-terraform/assets/287584/cdc808d0-abbe-4f71-9595-0a60bedcdda0



Regarding the log - I understand your concerns but if you say that it's reproducible with the configuration you already shared, then the log should not contain anything more than the config you shared, assuming that is the root of the VS Code workspace. You can find&replace the base paths in the URIs if you wish to hide sensitive parts of the path etc. or simply create the folder in a separate path that does not have anything sensitive.

There could be some custom configuration which is affecting the completion - can you check and disable any such custom settings in VS Code? Also can you check for any custom `terraform.*` config options?

I also noticed you use WSL and I remember reading some other issues related to either mis-configuration or performance due to the additional layer between VS Code and the language server. @jpogran Do you have any questions/suggestions as what to check here, as someone with far more WSL/Windows experience?
