### ISSUE TITLE
Missing support for latest import syntax

### ISSUE THREAD

**Issue by OmarHawk** [hashicorp/vscode-terraform#1591]
### Extension Version

v2.28.1

### VS Code Version

Version: 1.83.0 (user setup)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:12:16.321Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

### Operating System

Windows 10 Enterprise 22H2

### Terraform Version

Terraform 1.5.x

### Steps to Reproduce

Declare one of the new import blocks. 

An error appears, telling it is not supported there.

![image](https://github.com/hashicorp/vscode-terraform/assets/2911492/593dfbce-337c-43e1-90fe-5c5d6aa16b8f)

But it is possible. A plan runs through without errors...

### Expected Behavior

Should not show an error

### Actual Behavior

Shows an error.

### References

- https://developer.hashicorp.com/terraform/language/import

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by radeksimko** [comment]
Hi @OmarHawk 
We certainly support the `import` block but it is possible that we're detecting a version of Terraform/language in your environment which does _not_ have that block yet.

Can you click on the `{}` icon in the bottom bar to check what's being detected?

![2023-10-12 14 24 41](https://github.com/hashicorp/vscode-terraform/assets/287584/888f4066-e44f-46b7-b618-b758c06b1b1e)

We run `terraform version` to check installed version and then read the `required_version` under `terraform` block from the configuration. These get evaluated in that order, i.e. the installed version currently always wins, even if it doesn't match the requirement.

**Comment by OmarHawk** [comment]
ah, sry for the bug report then, I didn't know about this kind of thing. After making sure the detected terraform is on a proper version it works!

**Comment by radeksimko** [comment]
No need to apologise.

The decisions around how to decide what language version to validate against is something we could still re-assess in the future, if it continues to be confusing for folks.

e.g. we could prioritise the constraint in code over installed version at all times, or when there's mismatch with the constraint or something along these lines.

I am not sure what exact behaviour would be most intuitive at this point.
