### ISSUE TITLE
HCL files are not correctly parsed

### ISSUE THREAD

**Issue by artisticcheese** [hashicorp/vscode-terraform#1593]
### Extension Version

v2.28.1

### VS Code Version

Version: 1.83.1 (system setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

### Operating System

Windows 11

### Terraform Version

Terraform v1.5.0 on windows_amd64

### Steps to Reproduce

1. Create HCL file
2.  Add include {} block there
3. Syntax highlight would show an error

### Expected Behavior

Shall not be showing incorrect syntax

### Actual Behavior

Error is being shown
![image](https://github.com/hashicorp/vscode-terraform/assets/13176884/e327cd15-8630-4b53-ba39-1d34c995b537)

### Terraform Configuration

```terraform
include {
  path = find_in_parent_folders()
}
```

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
Hi @artisticcheese,

It looks like you're using Terragrunt?

We don't currently support Terragrunt files in the extension or the language server. AFAIK, Terragrunt uses `.hcl` as file extension by default, so it shouldn't cause any conflicts with our extension, which works with `.tf` and `.tfvars` files.

If you want to work with `.tf` files containing Terragrunt code, you can use this option, which turns off all validations, except for HCL syntax errors:
```
"terraform.validation.enableEnhancedValidation": false,
```
