### ISSUE TITLE
Attribute and Block Not Expected in Linux Web App

### ISSUE THREAD

**Issue by jgill44** [hashicorp/vscode-terraform#1609]
### Extension Version

v2.28.2

### VS Code Version

Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

### Operating System

Windows 11

### Terraform Version

1.6.2

### Steps to Reproduce

Create an azurerm_linux_web_app resource and include  virtual_network_subnet_id and stick_settings block.  

### Expected Behavior

Should not throw unexpected attribute and unexpected block error.

### Actual Behavior

Extension reports that virtual_network_subnet_id is an unexpected attribute and sticky_setting is an unexpected block.

### Terraform Configuration

```terraform
variable "web_apps" {
  type = map(object({
    web_app_name                                    = string
    service_plan_id                                 = string
    rgname                                          = string
    location                                        = string
    virtual_network_subnet_id                       = string
    app_setting_names                               = list(string)
  }))
}
resource "azurerm_linux_web_app" "web_apps" {
  for_each                  = var.web_apps
  name                      = each.value.web_app_name
  resource_group_name       = each.value.rgname
  location                  = each.value.location
  service_plan_id           = each.value.service_plan_id
  virtual_network_subnet_id = each.value.subnet_id
 
  sticky_settings {
    app_setting_names = each.value["app_setting_names"]
  }
}
```

### Workarounds

Downgrade to v2.27.2 resolves the issue..

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
Hi @jgill44,

I can't reproduce the bug.

Can you share the `required_providers` block from your configuration, which should include the provider version you're using?

By default, we bundle the schema of the latest version of the azurerm provider with the language server, which is then used for validation and autocompletion. When a user runs `terraform init`, we use the provider schema from disk, which should give the most accurate results.

Support for `sticky_settings` was introduced in azurerm 3.4.0, so I assume you have an older provider version installed?

**Comment by jgill44** [comment]
Hi @dbanck.  I am using the latest provider.  I tried reverting to v2.28.1 and v2.28.0 also.  Both of those also throw the error.  v2.72.2 does not.  

```terraform
provider "azurerm" {
  features {}
}

terraform {
  required_providers {
    azurerm = {
      source  = "registry.terraform.io/hashicorp/azurerm"
      version = ">=3.0.0"
    }
  }
}
```
Thanks for looking into this.

**Comment by dbanck** [comment]
Thanks! Your version constraint allows the latest version, but I'm still not sure if that's is being used here.

Can you hover over the provider block label and take a screenshot? That will show the current schema version.
![CleanShot 2023-10-26 at 18 04 42](https://github.com/hashicorp/vscode-terraform/assets/45985/1abebdb0-849f-4d45-be31-3f7ed0d96c8b)

And share the contents of the `.terraform.lock.hcl`?
