### ISSUE TITLE
Intellisense not displaying all items

### ISSUE THREAD

**Issue by eliassal** [hashicorp/vscode-terraform#1613]
### Extension Version

v2.28.2

### VS Code Version

Version 1.83.1

### Operating System

Windows 10 64bit

### Terraform Version

v1.6.2

### Steps to Reproduce

1. Fire VSC
2. Create main.tf
3. add terraform....
4. add provider
5. type resource
6. Ctrl + space
7. A long list displayed but no azurerm_rersource_group item
8. Ok, I enter manually azurerm_rersource_group then beside it the name
9. inside curly brackets I do Ctrl + space
10. A list displayed missing name, location......but I can see count, atlas,fore.....

### Expected Behavior

See all items required by a resource in intellisens

### Actual Behavior

Items missing in intellisense

### Terraform Configuration

```terraform
terraform {
  required_version = ">=1.6.2"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3.78.0"
    }
  }
}

provider "azurerm" {
  features {}
  skip_provider_registration = true

}

resource "azurerm_rersource_group" "rg" {
  
}
```

### Project Structure

```sh
Only main.tf in the directory and I did a tf init so there is a directory .terraform and a file .terrafofm.lock.hd
```

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
Hi @eliassal,

there is no resource called `azurerm_rersource_group` in the azurerm provider. Did you mean [`azurem_resource_group`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_group) (without the `r`)?

It should show up in the resource autocompletion
<img width="647" alt="CleanShot 2023-10-30 at 16 45 17@2x" src="https://github.com/hashicorp/vscode-terraform/assets/45985/67c904dd-7c93-4d21-8540-ddb7d7558226">

and completing the attribute should work, too
<img width="471" alt="CleanShot 2023-10-30 at 16 49 21@2x" src="https://github.com/hashicorp/vscode-terraform/assets/45985/8364275a-3760-432d-b9a4-a177bf02f809">

**Comment by eliassal** [comment]
So many thanks dbanck, my bad, dont know wht there was an additional r, now it is working fine as expected

**Comment by radeksimko** [comment]
Glad it's now working for you! 👍🏻
