### ISSUE TITLE
Unknown configuration options: ["validation"]

### ISSUE THREAD

**Issue by zerodayyy** [hashicorp/vscode-terraform#1619]
### Extension Version

v2.28.2

### VS Code Version

Version: 1.83.1 (Universal)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:46:55.789Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0

### Operating System

macOS Sonoma Version 14.0 (23A344)

### Terraform Version

Terraform v1.5.5 on darwin_arm64

### Steps to Reproduce

1. Install extension
2. Open VSCode

### Expected Behavior

Extension loads without errors

### Actual Behavior

Following pop-up appears:

![CleanShot 2023-11-06 at 20 02 47@2x](https://github.com/hashicorp/vscode-terraform/assets/49662783/441113ce-aeac-4106-bc7f-51e0efde7bc6)

### Anything Else?

I don't have any VSCode configuration for Terraform extension that may be even remotely connected with "validation" neither in UI nor in JSON, hence this message is very confusing

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jpogran** [comment]
@zerodayyy this message occurs when terraform-ls (the language server for this extension) sees a setting it doesn't know about from the extension. This happens during initialization. This most often occurs when their is an older terraform-ls version present than what the extension expects.

I see you installed extension version 2.28.2, do you use terraform-ls from another source? More specifically, do you set `terraform.languageServer.path` to something else? We bundle terraform-ls inside the extension, so choosing another terraform-ls binary is not a common case, but I thought to ask to confirm.

Another place to confirm is if there are any workspace settings (a .vscode/settings.json) file or if you're using a remote development extension like Remote Dev Containers, machine specific configuration can be specified there and apply unexpectedly.

**Comment by zerodayyy** [comment]
Yes, I was in fact using an external terraform-ls from Homebrew. Removing `terraform.languageServer.path` setting fixed the issue!
