### ISSUE TITLE
databricks_catalog_workspace_binding flagging required attributes as "Unexpected" 

### ISSUE THREAD

**Issue by dbhaigh** [hashicorp/vscode-terraform#1627]
### Extension Version

v2.29.0

### VS Code Version

Version: 1.84.2 (system setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

### Operating System

Windows 11 Home 22H2 - build 22621.2428

### Terraform Version

Terraform v1.5.4 on windows_amd64

### Steps to Reproduce

Define a databricks_catalog_workspace_binding

provide definitions for securable_name, securable_type, and binding_type - all REQUIRED attributes as per https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/catalog_workspace_binding (please note that the examples feature t he deprecated attirbute cataog_name - I'll be flagging that issue next :P )

The code will be flagged red as incorrect, generating error messages regarding "Unexpected attributes", and that the DEPRECATED attribute "catalog_name" is required

This is what it looks like in vscode

![image](https://github.com/hashicorp/vscode-terraform/assets/71402661/862154a5-cfd9-4b52-b1db-6b36333d477a)

It shouldn't - the extension needs updating 

### Expected Behavior

The extensions in VSCode doesn't flag this as incorrect - it's expected as per the lined document above

### Actual Behavior

It flags the attributes as unexpected and marks the resource block as in error

### Workarounds

Ignore the error message in VSCode and apply anyway

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
Hi @dbhaigh,

Thanks for taking the time to report this issue. The language server bundles all official and partner provider schemas to provide auto-completion, validation, etc. out of the box. So users don't have to install the provider.

Here it looks like we ended up bundling version [1.19.0](https://registry.terraform.io/providers/databricks/databricks/1.19.0/docs) with the latest language server release instead of the latest 1.30.0. I will investigate this.

In the meantime, you could run `terraform init` to download the provider and the language server will use that schema instead of the bundled one.

**Comment by dbhaigh** [comment]
Running terraform init won't help me - I don't have terraform initiated locally, for the code I am working on is a local copy of a devops repo

But - so long as you guys are now aware of the problem and are working on it?  I can live with the red-highlights until it's fixed

I can also update another, related, issue I've flagged up with the docs people regarding the provided example for "databricks_catalog_workspace_binding" being out-of-date

Thanks for the 411 - appreciate it

Cheers

-=A=-

.

**Comment by dbanck** [comment]
@dbhaigh We just released a new version [2.29.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.29.1). This updates the schema to the latest version. The update should appear automatically in VS Code.

--- 

In case you experience any different validation related bug, please do let us know through a new issue.

**Comment by dbhaigh** [comment]
Verified - all the erroneous red has vanished from my coed

Cheers for that

-=A=-

.
