### ISSUE TITLE
Can't enable or disable extension per workspace

### ISSUE THREAD

**Issue by br3ndonland** [hashicorp/vscode-terraform#1629]
### Extension Version

v2.29.0

### VS Code Version

Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:57.054Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0

### Operating System

macOS Sonoma 14.0

### Terraform Version

Terraform v1.5.7 on darwin_arm64

### Steps to Reproduce

1. Navigate to extensions
2. Click the gear
3. View "Enable (Workspace)" or "Disable (Workspace)" in the popup menu

### Expected Behavior

As of 2.28.2 (2023-10-16), it was possible to enable or disable the extension per workspace in VSCode.

<img src="https://github.com/hashicorp/vscode-terraform/assets/26674818/65842890-e7a9-451a-93cc-92762ee6f42a" alt="Screenshot of VSCode showing HashiCorp Terraform extension details" width="50%" />

### Actual Behavior

As of 2.29.0 (2023-11-08), the extension cannot be enabled or disabled per workspace in VSCode.

<img src="https://github.com/hashicorp/vscode-terraform/assets/26674818/77df2237-5894-4dcf-a5c7-e3b88d34285b" alt="Screenshot of VSCode showing HashiCorp Terraform extension details" width="50%" />

This change does not appear to be mentioned in the release notes for 2.29.0.

### Workarounds

Downgrade to extension v2.28.2

### References

- https://code.visualstudio.com/docs/editor/extension-marketplace#_manage-extensions

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jpogran** [comment]
Hey @br3ndonland thanks for bringing this to our attention. This was not intended and I don't immediately know what we did yet that caused it to not be able to be disabled/enabled per workspace, but I'm going to try and figure out.

**Comment by br3ndonland** [comment]
Thanks for the update @jpogran. I totally understand that some aspects of the VSCode Extensions API are outside your control, and appreciate your efforts with the upstream discussion in https://github.com/microsoft/vscode-discussions/discussions/930. If you figure out a solution and need some help testing development builds of the extension, I'm happy to help.

**Comment by jpogran** [comment]
Hi @br3ndonland, I just published a pre-release version of the extension with a potential fix. If you validate that it works for you, I'll merge it to main and publish a stable version soon.

<img width="635" alt="image" src="https://github.com/hashicorp/vscode-terraform/assets/272569/82c50f24-322a-4434-952e-f0e16b92d173">

**Comment by paul-at-cybr** [comment]
Works for me!
![image](https://github.com/hashicorp/vscode-terraform/assets/5486775/8a207e45-8ba5-45bf-ac55-5409716125c6)

**Comment by br3ndonland** [comment]
v2.29.2024011610 looks good, thanks @jpogran!

<img src="https://github.com/hashicorp/vscode-terraform/assets/26674818/0d48db5d-e16e-4ced-80b5-7beb378f4c84" alt="Screenshot of VSCode showing that the extension can be enabled per workspace" width="75%" />

**Comment by tuananhlai** [comment]
The fix works for me! But I had to manually select the version v2.29.2024011610 as suggested by @panfiva.

**Comment by jpogran** [comment]
Thanks all for the feedback. We've merged this and released it in the latest stable: 2.29.3. @br3ndonland let me know if things don't work for you in stable.
