### ISSUE TITLE
Allow disabling of terraform cloud 

### ISSUE THREAD

**Issue by mokshasoul** [hashicorp/vscode-terraform#1631]
### Extension Version

v2.29.0

### Problem Statement

Terraform cloud is currently not opt-in, and is always activated with the add in

### Expected User Experience

I would like to see an option that disables terraform cloud completely

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
Hi @mokshasoul,

The icon in the activity bar is the only place where the Terraform Cloud functionality shows up. If you don't want to use Terraform Cloud, you can right-click on the icon to hide the functionality and continue using the extension as usual.


<img width="371" alt="CleanShot 2023-11-17 at 18 06 53@2x" src="https://github.com/hashicorp/vscode-terraform/assets/45985/b3dc1edd-ba15-4fff-ba0b-797ac1571d90">


Let me know if this solves the problem or if there is anything else you want to disable.

**Comment by mokshasoul** [comment]
Hi @dbanck I also do not want it to show up when I'm doing CMD+SHIFT+P this is my main issue

**Comment by jpogran** [comment]
Hey @mokshasoul, thanks for the additional detail about what the main issue is. Controlling the visibility of commands in the Command Palette is normally a straightforward process, but is complicated a bit with how VS Code handles view container visibility. I'll work to figure out a solution that ties their visibility to the icon being hidden.

**Comment by mokshasoul** [comment]
@jpogran so in essence its just that typing  `terraform` something very fast `Terraform Cloud` comes on top:
<img width="964" alt="image" src="https://github.com/hashicorp/vscode-terraform/assets/9151046/26fd3e64-2f83-4984-87b1-08c79703506a">

But IMO if someone is not using terraform cloud then there's no reason for the commands to be there, its more an inconvenience rather than a bug

**Comment by jpogran** [comment]
Thanks @mokshasoul for the bump. This got a little delayed because of the holidays and catching up after that.

I recently merged https://github.com/hashicorp/vscode-terraform/pull/1643, which works to hide Terraform Cloud commands if the TFC view is not visible. The PR has a couple of screenshots to show what that looks like. It will be going out in the next release.

Unfortunately, due to the way views work inside VS Code, I'm not able to hide the automatically generated view commands as those are created when the extension activates by VS Code. I'm still working on what to do here, but hopefully this helps things in the interim.

**Comment by mokshasoul** [comment]
oh wow that's great, yea no problem I totally forgot to reply. Thanks a lot for your work !!
