### ISSUE TITLE
Allow signing out of Terraform Cloud account

### ISSUE THREAD

**Issue by lovre-nc** [hashicorp/vscode-terraform#1634]
### Extension Version

v2.29.0

### Problem Statement

I wanted to try out the cloud features of the extension. I signed in using my cloud account. 
I concluded that I don't need the features and want to sign out again. I did not find a way to do that.

### Proposal

I would like to have a sign out command and/or button.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
Hi @lovre-nc,

In the Activity Bar, next to the Settings gear icon, there is a User Account icon, where all extensions that use VS Code Authentication can surface operations. Clicking this icon will bring up a menu listing authenticated users, selecting your user account for TFC will bring up a menu to log out.

![CleanShot 2023-11-20 at 11 56 46@2x](https://github.com/hashicorp/vscode-terraform/assets/45985/92a53440-181f-4b52-9d9c-fe757b1d54ff)

**Comment by lovre-nc** [comment]
That's super nice! Unfortunately not many extensions use that feature so I wasn't aware of it or looking there. At least the next person searching for sign-out here will find it. 

Thank you, @dbanck!
