### ISSUE TITLE
Completion not working in a new file

### ISSUE THREAD

**Issue by SGA-Yuze-Li** [hashicorp/vscode-terraform#1648]
### Extension Version

2.29.0

### VS Code Version

Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19044

### Operating System

エディション	Windows 10 Enterprise バージョン	21H2 インストール日	‎2022/‎11/‎15 OS ビルド	19044.3693 エクスペリエンス	Windows Feature Experience Pack 1000.19053.1000.0

### Terraform Version

Terraform v1.6.5 on linux_amd64

### Steps to Reproduce

create a .tf file and coding like "provider", "module", "resource", "data" and "variable"

### Expected Behavior

![image](https://github.com/hashicorp/vscode-terraform/assets/127734100/377f8e48-682d-47c1-bafe-b2a9bfc50df8)

like this image, the orange icon should be there, and when I input "pro", the auto filled result "provider" should be there.
But Not.

### Actual Behavior

![image](https://github.com/hashicorp/vscode-terraform/assets/127734100/402d9d01-feb6-4c7a-8516-ec2a0b1ea260)
![image](https://github.com/hashicorp/vscode-terraform/assets/127734100/45901ecb-b46f-4b12-8d18-52a8f2b3cc63)
![image](https://github.com/hashicorp/vscode-terraform/assets/127734100/cbe5d77a-ac86-43f8-ac93-a6e4ff9da2aa)

lots of differences.

### Terraform Configuration

```terraform
resour

module 

vari

provide
```

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by radeksimko** [comment]
Hi @SGA-Yuze-Li 
I am not able to reproduce the issue you described.

Would you mind providing some more details?

 - Full list of active extensions (use `code --list-extensions` to obtain it). We have in the past received similar reports from people who installed some other Terraform extensions and either never installed ours (`hashicorp.terraform`) or installed multiple which ended up conflicting with each other. On that note - if you could try to disable or uninstall any other non-HashiCorp Terraform/HCL extensions or confirm there aren't any such conflicting extensions  that would be great!
 - You say this happens in a new file. While completion should still work in a new file, it has to be saved (even as an empty file) in order to have detected the right syntax (i.e. have `*.tf` extension). Can you confirm you have done that? Or can you check if this is reproducible in existing files that are already on disk?

**Comment by SGA-Yuze-Li** [comment]
Hi @radeksimko, here is the result of `code --list-extensions`, looks like no conflicting.

> C:\Windows> code --list-extensions
> eamodio.gitlens
> GitHub.remotehub
> hashicorp.terraform
> MS-CEINTL.vscode-language-pack-ja
> MS-CEINTL.vscode-language-pack-zh-hans
> ms-vscode-remote.remote-wsl
> ms-vscode.azure-repos
> ms-vscode.remote-repositories

About the second confirmation, I made sure of the file extension is `.tf` and also saved it. And my files is in my disk (Linux in Windows.)
![image](https://github.com/hashicorp/vscode-terraform/assets/127734100/fe5a59a8-cd24-4825-a538-c14880f62ec7)

**Comment by radeksimko** [comment]
@SGA-Yuze-Li After chatting with the team, I have one more question for you:

Can you check what is the language ID being detected?
![Screenshot 2023-12-18 at 10 55 37](https://github.com/hashicorp/vscode-terraform/assets/287584/867107ba-2b33-479d-bb51-970e89dc9f3e)

This should match what you see above, i.e. `Terraform`, *not* Terraform-vars *nor* HCL. If it does not match then can you check your settings for any custom associations of files and remove those and retry?

**Comment by SGA-Yuze-Li** [comment]
@radeksimko here is the screenshot, please check. The difference between your screenshot and mine is the #2 and #3, I don't have the "1.6.1" and "any" but "-" in my PC.
![image](https://github.com/hashicorp/vscode-terraform/assets/127734100/03d3502d-5f6b-40c0-82ee-7f0d1810ace8)

**Comment by radeksimko** [comment]
Thanks for checking, can you open the `Output` panel (see https://github.com/hashicorp/terraform-ls/blob/main/docs/TROUBLESHOOTING.md#stderr-default for full instructions) and copy anything that is in the log under `HashiCorp Terraform` and provide it for review as a [gist](https://gist.github.com)?

**Comment by SGA-Yuze-Li** [comment]
Hi @radeksimko , please check this link.
https://gist.github.com/SGA-Yuze-Li/6cd37ce9d7beb29b6dc9be9c850609ed

If anything is necessary, please feel free to contact me

**Comment by SGA-Yuze-Li** [comment]
@jpogran , thank you sooo much!! It works!!

**Comment by SGA-Yuze-Li** [comment]
Let me close this issue because cleared
