### ISSUE TITLE
tfvars named deploy-vars.dev.tfvars reporting incorrect syntax

### ISSUE THREAD

**Issue by bugged84** [hashicorp/vscode-terraform#1672]
### Extension Version

v2.29.2

### VS Code Version

Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

### Operating System

Windows 10 Enterprise Version 22H2 (19045.3803)

### Terraform Version

Terraform v1.3.6 on windows_amd64

### Steps to Reproduce

Create simple Terraform configuration
Create variables file deploy-vars.dev.tfvars

syntax error
![image](https://github.com/hashicorp/vscode-terraform/assets/23638686/9b9325ff-2014-497e-bfad-7a5245a86d8b)

### Expected Behavior

Valid HCL tfvars aren't highlighted.

### Actual Behavior

Error;
Unexpected attribute: An attribute named "hello" is not expected here Terraform

### Terraform Configuration

```terraform
output.tf
variable "hello" {
  type = string
}

output "hello" {
  value = var.hello
}

deploy-vars.dev.tfvars
hello = "world"
```

### Project Structure

```sh
.
├── deploy-vars.dev.tfvars
└── output.tf
```

### Workarounds

Reverting to previous version of extension 2.27.2

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by radeksimko** [comment]
Hi @bugged84 
I was unable to reproduce the issue - see screenshot below after following the steps:

<img width="811" alt="Screenshot 2024-01-19 at 10 56 31" src="https://github.com/hashicorp/vscode-terraform/assets/287584/75fd0436-9e2c-4ee4-88d0-84756774105a">

Can you check what is the reported installed version of the LS in the bottom bar and confirm it matches the version on this screenshot?

<img width="233" alt="Screenshot 2024-01-19 at 10 58 45" src="https://github.com/hashicorp/vscode-terraform/assets/287584/9b38da29-748d-44c9-8dbd-dda87b2124b8">

Relatedly - can you check/share any non-default settings in VS Code and check that you do not have any other extensions installed that would be claiming `*.tf` or `*.tfvars` files?

**Comment by bugged84** [comment]
Here's the LS info.

![image](https://github.com/hashicorp/vscode-terraform/assets/23638686/b89ceea3-028e-47f0-a676-1452f2693cce)

I don't know of an easy way to answer the "default settings / other extensions" question without blowing away my install and starting over. I'm a little hesitant to try that just yet, since my configuration works fine with v2.27.2 and lower, and only fails with later versions of the HashiCorp Terraform extension installed. FWIW, I believe I'm running a pretty unmodified setup with extensions for ESLint, Prettier, GraphQL syntax highlighting, and C# language support, and I don't recall having to make any changes to the default VS Code config.

Another thing worth mentioned is that the error doesn't appear when first opening the project folder, but rather only after making an edit to the file.

![image](https://github.com/hashicorp/vscode-terraform/assets/23638686/939be927-6d16-4749-8012-11702028236f)

**Comment by dbanck** [comment]
Thank you for confirming the LS versions!

Can you check if the language for `.tfvars` files is `terraform-vars` and not `Terraform`?
![CleanShot 2024-01-19 at 17 36 53@2x](https://github.com/hashicorp/vscode-terraform/assets/45985/b1a229fc-eb13-4bd5-b2d9-fb8eaf418b1b)

With the v2.28.0 release of the extension, we shipped the enhanced validation feature, which validates your configuration on the fly. But it relies on correct language ids for files. So if this was misconfigured in the past, it wouldn't really show up in older versions.

**Comment by bugged84** [comment]
Ah ok, after switching the language from `Terraform` to `terraform-vars` using the picklist, and then restarting VS Code, the error has gone away.

So updating my settings.json from this...
![image](https://github.com/hashicorp/vscode-terraform/assets/23638686/d71b3fb7-a358-4d38-a8eb-7a011d1bda2c)

...to this would be the the correct solution?
![image](https://github.com/hashicorp/vscode-terraform/assets/23638686/76164bd0-e5d2-4b2f-a0c6-74cbc8dcce04)

**Comment by radeksimko** [comment]
In general the correct file association [already comes with the extension](https://github.com/hashicorp/vscode-terraform/blob/6e1b79a2e8f521427f3bb6341c33a31845e54496/package.json#L65-L90) and is applied by default, so there should be no need to add anything like that to your settings.

Either way, glad it's now solved!

**Comment by dbanck** [comment]
That's great to hear!

You don't need to do any custom file association configuration. The extension will do this for you. You can delete the whole `"files.associations"` block from your config.
