### ISSUE TITLE
"Unexpected block" false alerts

### ISSUE THREAD

**Issue by david-forster10** [hashicorp/vscode-terraform#1684]
### Extension Version

v2.29.3

### VS Code Version

Version: 1.85.2 (user setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.14393

### Operating System

Windows Server 2016 Datacenter 64-bit  (Virtual workstation)

### Terraform Version

Terraform v1.7.0 on windows_amd64

### Steps to Reproduce

1) Install Visual Studio Code
2) Install Terraform plugin
3) Create file with a data resource and declare lifecycle condition
4) Define variable with a verification block

### Expected Behavior

No errors should be flagged as per:

https://developer.hashicorp.com/terraform/language/data-sources#custom-condition-checks
https://developer.hashicorp.com/terraform/language/values/variables#custom-validation-rules

### Actual Behavior

Received errors for "unexpected block"

### Terraform Configuration

```terraform
data "aws_route53_zone" "default" {
  zone_id = var.zone_id
  name = var.domain
  private_zone = true

  lifecycle {
    precondition {
      condition     = var.zone_id == "" && var.domain == ""
      error_message = "One of zone_id or domain must be provided to select the correct Hosted Zone"
    }
  }
}

/* optional variables */
variable "zone_id" {
  description = "Hosted Zone ID where the Route53 entry will be created"
  type        = string
  default     = ""

  validation {
    condition = var.zone_id != ""
    error_message = "One of zone_id or domain must be provided to select the correct Hosted Zone"
  }
}
```

### Anything Else?

Trialled with multiple extensions active, as well as just the Terraform plugin and same behaviour seen both times.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
Hi @david-forster10!

Thanks for taking the time to report this issue. I can't reproduce the problem.

Can you share more details on which blocks are marked as unexpected and share the log output from Terraform LS?
![CleanShot 2024-02-05 at 11 08 56@2x](https://github.com/hashicorp/vscode-terraform/assets/45985/b8350a15-680e-4a9e-a586-564e763e425f)

Thanks!

**Comment by david-forster10** [comment]
Thanks for getting back, I've had to redact directory paths due to the nature of our environment (indicated with the use of "#REDACTED#"), but please see below the log output, and I've attached a screenshot showing the underlined errors
<img width="423" alt="terraform validation error" src="https://github.com/hashicorp/vscode-terraform/assets/26306667/977006f8-7731-4bd5-ab2c-adb095cae2a4">

> 2024/02/05 10:31:04 opts.go:215: Received request batch of size 1 (qlen=0)
2024/02/05 10:31:04 opts.go:215: Dequeued request batch of length 1 (qlen=0)
2024/02/05 10:31:04 rpc_logger.go:32: Incoming notification for "textDocument/didChange": {"textDocument":{"uri":"file:///#REDACTED#/temp.tf","version":6},"contentChanges":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"rangeLength":0,"text":"data \"aws_route53_zone\" \"default\" {\r\n  zone_id = var.zone_id\r\n  name = var.domain\r\n  private_zone = true\r\n\r\n  lifecycle {\r\n    precondition {\r\n      condition     = var.zone_id == \"\" && var.domain == \"\"\r\n      error_message = \"One of zone_id or domain must be provided to select the correct Hosted Zone\"\r\n    }\r\n  }\r\n}\r\n\r\n/* optional variables */\r\nvariable \"zone_id\" {\r\n  description = \"Hosted Zone ID where the Route53 entry will be created\"\r\n  type        = string\r\n  default     = \"\"\r\n\r\n  validation {\r\n    condition = var.zone_id != \"\"\r\n    error_message = \"One of zone_id or domain must be provided to select the correct Hosted Zone\"\r\n  }\r\n}"}]}
2024/02/05 10:31:04 jobs.go:140: JOBS: Enqueueing new job "691": "OpTypeParseModuleConfiguration" for {"file:///#REDACTED#"} (IsDirOpen: true, IgnoreState: true)
2024/02/05 10:31:04 jobs.go:299: retrying on obj is nil
2024/02/05 10:31:04 jobs.go:299: retrying on obj is nil
2024/02/05 10:31:04 jobs.go:140: JOBS: Enqueueing new job "692": "OpTypeLoadModuleMetadata" for {"file:///#REDACTED#"} (IsDirOpen: true, IgnoreState: true)
2024/02/05 10:31:04 jobs.go:299: retrying on obj is nil
2024/02/05 10:31:04 jobs.go:140: JOBS: Enqueueing new job "693": "OpTypeGetModuleDataFromRegistry" for {"file:///#REDACTED#"} (IsDirOpen: true, IgnoreState: false)
2024/02/05 10:31:04 jobs.go:140: JOBS: Enqueueing new job "694": "OpTypeParseVariables" for {"file:///#REDACTED#"} (IsDirOpen: true, IgnoreState: true)
2024/02/05 10:31:04 jobs.go:299: retrying on obj is nil
2024/02/05 10:31:04 jobs.go:140: JOBS: Enqueueing new job "695": "OpTypeSchemaVarsValidation" for {"file:///#REDACTED#"} (IsDirOpen: true, IgnoreState: true)
2024/02/05 10:31:04 jobs.go:140: JOBS: Enqueueing new job "696": "OpTypeDecodeVarsReferences" for {"file:///#REDACTED#"} (IsDirOpen: true, IgnoreState: true)
2024/02/05 10:31:04 jobs.go:321: JOBS: Dispatching next job "691" (scheduler prio: 1, job prio: 0, isDirOpen: true): "OpTypeParseModuleConfiguration" for {"file:///#REDACTED#"}
2024/02/05 10:31:04 jobs.go:461: JOBS: Finishing job "691": "OpTypeParseModuleConfiguration" for {"file:///#REDACTED#"} (err = %!s(<nil>), deferredJobs: [])
2024/02/05 10:31:04 jobs.go:321: JOBS: Dispatching next job "692" (scheduler prio: 1, job prio: 0, isDirOpen: true): "OpTypeLoadModuleMetadata" for {"file:///#REDACTED#"}
2024/02/05 10:31:04 module_calls.go:64: indexing declared module calls for "file:///#REDACTED#": 2
2024/02/05 10:31:04 jobs.go:140: JOBS: Enqueueing new job "697": "OpTypePreloadEmbeddedSchema" for {"file:///#REDACTED#"} (IsDirOpen: true, IgnoreState: true)
2024/02/05 10:31:04 jobs.go:140: JOBS: Enqueueing new job "698": "OpTypeSchemaModuleValidation" for {"file:///#REDACTED#"} (IsDirOpen: true, IgnoreState: true)
2024/02/05 10:31:04 jobs.go:140: JOBS: Enqueueing new job "699": "OpTypeDecodeReferenceTargets" for {"file:///#REDACTED#"} (IsDirOpen: true, IgnoreState: true)
2024/02/05 10:31:04 jobs.go:140: JOBS: Enqueueing new job "700": "OpTypeDecodeReferenceOrigins" for {"file:///#REDACTED#"} (IsDirOpen: true, IgnoreState: true)
2024/02/05 10:31:04 jobs.go:140: JOBS: Enqueueing new job "701": "OpTypeReferenceValidation" for {"file:///#REDACTED#"} (IsDirOpen: true, IgnoreState: true)
2024/02/05 10:31:04 jobs.go:461: JOBS: Finishing job "692": "OpTypeLoadModuleMetadata" for {"file:///#REDACTED#"} (err = %!s(<nil>), deferredJobs: ["697" "699" "700"])
2024/02/05 10:31:04 jobs.go:321: JOBS: Dispatching next job "694" (scheduler prio: 1, job prio: 0, isDirOpen: true): "OpTypeParseVariables" for {"file:///#REDACTED#"}
2024/02/05 10:31:04 jobs.go:299: retrying on obj is nil
2024/02/05 10:31:04 jobs.go:461: JOBS: Finishing job "694": "OpTypeParseVariables" for {"file:///#REDACTED#"} (err = %!s(<nil>), deferredJobs: [])
2024/02/05 10:31:04 jobs.go:321: JOBS: Dispatching next job "695" (scheduler prio: 1, job prio: 0, isDirOpen: true): "OpTypeSchemaVarsValidation" for {"file:///#REDACTED#"}
2024/02/05 10:31:04 jobs.go:321: JOBS: Dispatching next job "693" (scheduler prio: -1, job prio: -1, isDirOpen: true): "OpTypeGetModuleDataFromRegistry" for {"file:///#REDACTED#"}
2024/02/05 10:31:04 jobs.go:461: JOBS: Finishing job "693": "OpTypeGetModuleDataFromRegistry" for {"file:///#REDACTED#"} (err = %!s(<nil>), deferredJobs: [])
2024/02/05 10:31:04 jobs.go:461: JOBS: Finishing job "695": "OpTypeSchemaVarsValidation" for {"file:///#REDACTED#"} (err = %!s(<nil>), deferredJobs: [])
2024/02/05 10:31:04 jobs.go:321: JOBS: Dispatching next job "696" (scheduler prio: 1, job prio: 0, isDirOpen: true): "OpTypeDecodeVarsReferences" for {"file:///#REDACTED#"}
2024/02/05 10:31:04 jobs.go:299: retrying on obj is nil
2024/02/05 10:31:04 jobs.go:461: JOBS: Finishing job "696": "OpTypeDecodeVarsReferences" for {"file:///#REDACTED#"} (err = %!s(<nil>), deferredJobs: [])
2024/02/05 10:31:04 jobs.go:299: retrying on obj is nil
2024/02/05 10:31:04 jobs.go:321: JOBS: Dispatching next job "697" (scheduler prio: 1, job prio: 0, isDirOpen: true): "OpTypePreloadEmbeddedSchema" for {"file:///#REDACTED#"}
2024/02/05 10:31:04 jobs.go:461: JOBS: Finishing job "697": "OpTypePreloadEmbeddedSchema" for {"file:///#REDACTED#"} (err = %!s(<nil>), deferredJobs: [])
2024/02/05 10:31:04 jobs.go:299: retrying on obj is nil
2024/02/05 10:31:04 jobs.go:321: JOBS: Dispatching next job "698" (scheduler prio: 1, job prio: 0, isDirOpen: true): "OpTypeSchemaModuleValidation" for {"file:///#REDACTED#"}
2024/02/05 10:31:04 jobs.go:299: retrying on obj is nil
2024/02/05 10:31:04 provider_schema.go:306: PSS: getting provider schema (#REDACTED#, registry.terraform.io/-/aws, )
2024/02/05 10:31:05 jobs.go:461: JOBS: Finishing job "698": "OpTypeSchemaModuleValidation" for {"file:///#REDACTED#"} (err = %!s(<nil>), deferredJobs: [])
2024/02/05 10:31:05 jobs.go:321: JOBS: Dispatching next job "699" (scheduler prio: 1, job prio: 0, isDirOpen: true): "OpTypeDecodeReferenceTargets" for {"file:///#REDACTED#"}
2024/02/05 10:31:05 provider_schema.go:306: PSS: getting provider schema (#REDACTED#, registry.terraform.io/-/aws, )
2024/02/05 10:31:05 jobs.go:299: retrying on obj is nil
2024/02/05 10:31:05 jobs.go:461: JOBS: Finishing job "699": "OpTypeDecodeReferenceTargets" for {"file:///#REDACTED#"} (err = %!s(<nil>), deferredJobs: [])
2024/02/05 10:31:05 jobs.go:321: JOBS: Dispatching next job "700" (scheduler prio: 1, job prio: 0, isDirOpen: true): "OpTypeDecodeReferenceOrigins" for {"file:///#REDACTED#"}
2024/02/05 10:31:05 provider_schema.go:306: PSS: getting provider schema (#REDACTED#, registry.terraform.io/-/aws, )
2024/02/05 10:31:05 jobs.go:299: retrying on obj is nil
2024/02/05 10:31:05 jobs.go:461: JOBS: Finishing job "700": "OpTypeDecodeReferenceOrigins" for {"file:///#REDACTED#"} (err = %!s(<nil>), deferredJobs: [])
2024/02/05 10:31:05 jobs.go:299: retrying on obj is nil
2024/02/05 10:31:05 jobs.go:299: retrying on obj is nil
2024/02/05 10:31:05 jobs.go:321: JOBS: Dispatching next job "701" (scheduler prio: 1, job prio: 0, isDirOpen: true): "OpTypeReferenceValidation" for {"file:///#REDACTED#"}
2024/02/05 10:31:05 provider_schema.go:306: PSS: getting provider schema (#REDACTED#, registry.terraform.io/-/aws, )
2024/02/05 10:31:05 jobs.go:461: JOBS: Finishing job "701": "OpTypeReferenceValidation" for {"file:///#REDACTED#"} (err = %!s(<nil>), deferredJobs: [])
2024/02/05 10:31:05 jobs.go:299: retrying on obj is nil
2024/02/05 10:31:05 opts.go:215: Posting server call "client.refreshModuleProviders" 
2024/02/05 10:31:05 opts.go:215: Posting server notification "textDocument/publishDiagnostics" {"uri":"file:///#REDACTED#","diagnostics":[]}
2024/02/05 10:31:05 opts.go:215: Posting server notification "textDocument/publishDiagnostics" {"uri":"file:///#REDACTED#/data.tf","diagnostics":[]}
2024/02/05 10:31:05 opts.go:215: Posting server notification "textDocument/publishDiagnostics" {"uri":"file:///#REDACTED#/outputs.tf","diagnostics":[]}
2024/02/05 10:31:05 opts.go:215: Posting server notification "textDocument/publishDiagnostics" {"uri":"file:///#REDACTED#/main.tf","diagnostics":[]}
2024/02/05 10:31:05 opts.go:215: Posting server notification "textDocument/publishDiagnostics" {"uri":"file:///#REDACTED#/temp.tf","diagnostics":[{"range":{"start":{"line":5,"character":2},"end":{"line":5,"character":11}},"severity":1,"source":"Terraform","message":"Unexpected block: Blocks of type \"lifecycle\" are not expected here"},{"range":{"start":{"line":19,"character":2},"end":{"line":19,"character":12}},"severity":1,"source":"Terraform","message":"Unexpected block: Blocks of type \"validation\" are not expected here"}]}
2024/02/05 10:31:05 opts.go:215: Posting server notification "textDocument/publishDiagnostics" {"uri":"file:///#REDACTED#/variables.tf","diagnostics":[{"range":{"start":{"line":4,"character":2},"end":{"line":4,"character":12}},"severity":1,"source":"Terraform","message":"Unexpected block: Blocks of type \"validation\" are not expected here"}]}
2024/02/05 10:31:05 opts.go:215: Received response for callback "114"
2024/02/05 10:31:05 opts.go:215: Posting server call "client.refreshModuleCalls" 
2024/02/05 10:31:05 opts.go:215: Received response for callback "115"
2024/02/05 10:31:05 opts.go:215: Posting server call "client.refreshTerraformVersion" 
2024/02/05 10:31:05 opts.go:215: Received request batch of size 1 (qlen=0)
2024/02/05 10:31:05 opts.go:215: Dequeued request batch of length 1 (qlen=0)
2024/02/05 10:31:05 rpc_logger.go:32: Incoming request for "workspace/executeCommand" (ID 170): {"command":"terraform-ls.module.terraform","arguments":["uri=file:///#REDACTED#"]}
2024/02/05 10:31:05 rpc_logger.go:53: Response to "workspace/executeCommand" (ID 170): {"v":0,"discovered_version":"0.12.16"}
2024/02/05 10:31:05 opts.go:215: Completed 1 requests [0s elapsed]
2024/02/05 10:31:05 opts.go:215: Received response for callback "116"
2024/02/05 10:31:05 opts.go:215: Received request batch of size 1 (qlen=0)
2024/02/05 10:31:05 opts.go:215: Dequeued request batch of length 1 (qlen=0)
2024/02/05 10:31:05 rpc_logger.go:32: Incoming request for "textDocument/codeLens" (ID 171): {"textDocument":{"uri":"file:///#REDACTED#/temp.tf"}}
2024/02/05 10:31:05 provider_schema.go:306: PSS: getting provider schema (#REDACTED#, registry.terraform.io/-/aws, )
2024/02/05 10:31:05 rpc_logger.go:53: Response to "textDocument/codeLens" (ID 171): []
2024/02/05 10:31:05 opts.go:215: Completed 1 requests [10.0024ms elapsed]
2024/02/05 10:31:05 opts.go:215: Received request batch of size 1 (qlen=0)
2024/02/05 10:31:05 opts.go:215: Dequeued request batch of length 1 (qlen=0)
2024/02/05 10:31:05 rpc_logger.go:32: Incoming request for "textDocument/semanticTokens/full" (ID 172): {"textDocument":{"uri":"file:///#REDACTED#/temp.tf"}}
2024/02/05 10:31:05 provider_schema.go:306: PSS: getting provider schema (#REDACTED#, registry.terraform.io/-/aws, )
2024/02/05 10:31:05 rpc_logger.go:53: Response to "textDocument/semanticTokens/full" (ID 172): {"data":[0,0,4,10,16,0,5,18,11,16402,0,19,9,11,144,1,2,7,9,16,0,10,3,18,0,0,4,7,18,0,1,2,4,9,16,0,7,3,18,0,0,4,6,18,0,1,2,12,9,16,0,15,4,12,0,11,0,8,10,32768,0,9,9,11,32768,1,2,11,9,32768,0,14,56,13,0,1,2,4,9,32768,0,14,6,20,0,1,2,7,9,32768,0,14,2,13,0]}
2024/02/05 10:31:05 opts.go:215: Completed 1 requests [8.9584ms elapsed]
2024/02/05 10:31:05 opts.go:215: Received request batch of size 1 (qlen=0)
2024/02/05 10:31:05 opts.go:215: Dequeued request batch of length 1 (qlen=0)
2024/02/05 10:31:05 rpc_logger.go:32: Incoming request for "textDocument/documentSymbol" (ID 173): {"textDocument":{"uri":"file:///#REDACTED#/temp.tf"}}
2024/02/05 10:31:05 provider_schema.go:306: PSS: getting provider schema (#REDACTED#, registry.terraform.io/-/aws, )
2024/02/05 10:31:05 rpc_logger.go:53: Response to "textDocument/documentSymbol" (ID 173): [{"name":"data \"aws_route53_zone\" \"default\"","kind":5,"range":{"start":{"line":0,"character":0},"end":{"line":11,"character":1}},"selectionRange":{"start":{"line":0,"character":0},"end":{"line":11,"character":1}},"children":[{"name":"zone_id","kind":14,"range":{"start":{"line":1,"character":2},"end":{"line":1,"character":23}},"selectionRange":{"start":{"line":1,"character":2},"end":{"line":1,"character":23}}},{"name":"name","kind":14,"range":{"start":{"line":2,"character":2},"end":{"line":2,"character":19}},"selectionRange":{"start":{"line":2,"character":2},"end":{"line":2,"character":19}}},{"name":"private_zone","kind":17,"range":{"start":{"line":3,"character":2},"end":{"line":3,"character":21}},"selectionRange":{"start":{"line":3,"character":2},"end":{"line":3,"character":21}}},{"name":"lifecycle","kind":5,"range":{"start":{"line":5,"character":2},"end":{"line":10,"character":3}},"selectionRange":{"start":{"line":5,"character":2},"end":{"line":10,"character":3}},"children":[{"name":"precondition","kind":5,"range":{"start":{"line":6,"character":4},"end":{"line":9,"character":5}},"selectionRange":{"start":{"line":6,"character":4},"end":{"line":9,"character":5}},"children":[{"name":"condition","kind":13,"range":{"start":{"line":7,"character":6},"end":{"line":7,"character":59}},"selectionRange":{"start":{"line":7,"character":6},"end":{"line":7,"character":59}}},{"name":"error_message","kind":15,"range":{"start":{"line":8,"character":6},"end":{"line":8,"character":99}},"selectionRange":{"start":{"line":8,"character":6},"end":{"line":8,"character":99}}}]}]}]},{"name":"variable \"zone_id\"","kind":5,"range":{"start":{"line":14,"character":0},"end":{"line":23,"character":1}},"selectionRange":{"start":{"line":14,"character":0},"end":{"line":23,"character":1}},"children":[{"name":"description","kind":15,"range":{"start":{"line":15,"character":2},"end":{"line":15,"character":72}},"selectionRange":{"start":{"line":15,"character":2},"end":{"line":15,"character":72}}},{"name":"type","kind":14,"range":{"start":{"line":16,"character":2},"end":{"line":16,"character":22}},"selectionRange":{"start":{"line":16,"character":2},"end":{"line":16,"character":22}}},{"name":"default","kind":15,"range":{"start":{"line":17,"character":2},"end":{"line":17,"character":18}},"selectionRange":{"start":{"line":17,"character":2},"end":{"line":17,"character":18}}},{"name":"validation","kind":5,"range":{"start":{"line":19,"character":2},"end":{"line":22,"character":3}},"selectionRange":{"start":{"line":19,"character":2},"end":{"line":22,"character":3}},"children":[{"name":"condition","kind":13,"range":{"start":{"line":20,"character":4},"end":{"line":20,"character":33}},"selectionRange":{"start":{"line":20,"character":4},"end":{"line":20,"character":33}}},{"name":"error_message","kind":15,"range":{"start":{"line":21,"character":4},"end":{"line":21,"character":97}},"selectionRange":{"start":{"line":21,"character":4},"end":{"line":21,"character":97}}}]}]}]
2024/02/05 10:31:05 opts.go:215: Completed 1 requests [10.9995ms elapsed]
2024/02/05 10:31:06 opts.go:215: Received request batch of size 1 (qlen=0)
2024/02/05 10:31:06 opts.go:215: Dequeued request batch of length 1 (qlen=0)
2024/02/05 10:31:06 rpc_logger.go:32: Incoming request for "textDocument/documentLink" (ID 174): {"textDocument":{"uri":"file:///#REDACTED#/temp.tf"}}
2024/02/05 10:31:06 provider_schema.go:306: PSS: getting provider schema (#REDACTED#, registry.terraform.io/-/aws, )
2024/02/05 10:31:06 rpc_logger.go:53: Response to "textDocument/documentLink" (ID 174): []
2024/02/05 10:31:06 opts.go:215: Completed 1 requests [9.9985ms elapsed]
2024/02/05 10:31:34 opts.go:215: Received request batch of size 1 (qlen=0)
2024/02/05 10:31:34 opts.go:215: Dequeued request batch of length 1 (qlen=0)
2024/02/05 10:31:34 rpc_logger.go:32: Incoming request for "textDocument/hover" (ID 175): {"textDocument":{"uri":"file:///#REDACTED#/temp.tf"},"position":{"line":5,"character":6}}
2024/02/05 10:31:34 provider_schema.go:306: PSS: getting provider schema (#REDACTED#, registry.terraform.io/-/aws, )
2024/02/05 10:31:34 hover.go:35: Looking for hover data at "temp.tf" -> hcl.Pos{Line:6, Column:7, Byte:114}
2024/02/05 10:31:34 hover.go:37: received hover data: (*lang.HoverData)(nil)
2024/02/05 10:31:34 rpc_logger.go:48: Error for "textDocument/hover" (ID 175): [-32098] temp.tf (6,7): unknown block type "lifecycle"
2024/02/05 10:31:34 opts.go:215: Completed 1 requests [9.0484ms elapsed]
[Error - 10:31:34 AM] Request textDocument/hover failed.
  Message: temp.tf (6,7): unknown block type "lifecycle"
  Code: -32098 
2024/02/05 10:31:38 opts.go:215: Received request batch of size 1 (qlen=0)
2024/02/05 10:31:38 opts.go:215: Dequeued request batch of length 1 (qlen=0)
2024/02/05 10:31:38 rpc_logger.go:32: Incoming request for "textDocument/hover" (ID 176): {"textDocument":{"uri":"file:///#REDACTED#/temp.tf"},"position":{"line":19,"character":8}}
2024/02/05 10:31:38 provider_schema.go:306: PSS: getting provider schema (#REDACTED#, registry.terraform.io/-/aws, )
2024/02/05 10:31:38 hover.go:35: Looking for hover data at "temp.tf" -> hcl.Pos{Line:20, Column:9, Byte:498}
2024/02/05 10:31:38 hover.go:37: received hover data: (*lang.HoverData)(nil)
2024/02/05 10:31:38 rpc_logger.go:48: Error for "textDocument/hover" (ID 176): [-32098] temp.tf (20,9): unknown block type "validation"
2024/02/05 10:31:38 opts.go:215: Completed 1 requests [18.9639ms elapsed]
[Error - 10:31:38 AM] Request textDocument/hover failed.
  Message: temp.tf (20,9): unknown block type "validation"
  Code: -32098

**Comment by dbanck** [comment]
Thanks for providing the log! 

These blocks are part of the core schema and their availability depends on your Terraform version. I see, you said you're using 1.7.0, but can you check which version the LS detects?
There is a little popup in the bottom right corner of VS Code.

<img width="283" alt="CleanShot 2024-02-05 at 11 52 14@2x" src="https://github.com/hashicorp/vscode-terraform/assets/45985/3d694bb6-844a-424e-828f-956d605ee376">

**Comment by david-forster10** [comment]
Thank you!

As this is a dev machine, Chocolatey had been previously used to install 0.12.x of Terraform and was being treated as the primary binary instead of 1.7.0 when I upgraded. I've removed the Chocolatey managed version and it's working as expected
