### ISSUE TITLE
Variable falsely marked as not declared in for_each block.

### ISSUE THREAD

**Issue by dmitri-s** [hashicorp/vscode-terraform#1696]
### Extension Version

v2.29.2024021318

### VS Code Version

Version: 1.85.1 (Universal)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:06.308Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.3.0

### Operating System

macOS Sonoma Version 14.3.1 (23D60)

### Terraform Version

Terraform v1.7.3 on darwin_arm64

### Steps to Reproduce

1. Open VSCode
2. Open main.tf with code below.
3. See error.

### Expected Behavior

The variable should not be underlined and there should not be a message `No declaration found for "var.cae_settings" Terraform`.

### Actual Behavior

Varaible is underlined and message displayed: `No declaration found for "var.cae_settings" Terraform`.

### Terraform Configuration

```terraform
## Creates Azure Log Analytics Workspace
resource "azurerm_log_analytics_workspace" "log" {

  ####### This is where the false "No declaration found" comes up
  for_each = { for idx, cae in var.cae_settings : idx => cae }
  ############################################################ 

  name                = "${each.value.name}${format("%02d", each.key + 0)}log"
  resource_group_name = var.resource_group.name
  location            = var.resource_group.location
  sku                 = each.value.log_sku
  retention_in_days   = each.value.log_days

  tags = var.tags
}

variable "cae_settings" {
  description = "Settings to be used to create CAE."
  type = list(object({
    name     = string
    log_sku  = string
    log_days = number
    snet_id  = string
  }))
  default = []
}
```

### Anything Else?

I tried both release version (v2.29.4) and pre-release (v2.29.2024021318). It could be that I am using wrong syntax and IntelliSense expects somethign else.

### Workarounds

Pretend that error is not there. If anyone raise questions during code review claim ignorance and confidently state: "**It works on my machine!**" :zany_face:

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
Thanks for taking the time to report this! We're already tracking this issue as #1693, so I'm closing this as a duplicate.

The bug has been fixed and will be part of the next release. :)
