### ISSUE TITLE
Vscode Language Server is preloading wrong provider version - intellisense then not working

### ISSUE THREAD

**Issue by phx-tim-butters** [hashicorp/vscode-terraform#1701]
### Extension Version

v2.29.4

### VS Code Version

Version: 1.87.0 (user setup)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:41:44.469Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22621

### Operating System

Edition	Windows 11 Enterprise Version	22H2 Installed on	‎09/‎05/‎2023 OS build	22621.3155 Experience	Windows Feature Experience Pack 1000.22684.1000.0

### Terraform Version

Terraform v1.7.4 on linux_amd64

### Steps to Reproduce

1. Specify alz provider and version

terraform {
  required_providers {
    alz = {
      source  = "azure/alz"
      version = "0.8.0"
    }
  }

2. Use input variable only present in v.0.8.0 of the provider

provider "alz" {

  lib_urls = [
    "${path.root}/lib",
    "github.com/MyOrg/MyRepo//some/dir?ref=v1.1.0&depth=1",
  ]
}

3. Observe vscode intellisense stating Unexpected Attribute

### Expected Behavior

I expect vscode intellisense by means of the language server to correctly validate the input variable lib_urls

### Actual Behavior

vscode intellisense stating Unexpected Attribute via the Terraform language Server

### Terraform Configuration

```terraform
terraform {
  required_providers {
    alz = {
      source  = "azure/alz"
      version = "0.8.0"
    }
  }

provider "alz" {

  lib_urls = [
    "${path.root}/lib"
  ]
}
```

### Anything Else?

Output for Hashicopr Terraform in vscode shows preloaded schema;

2024/02/29 12:20:07 module_ops.go:368: preloaded schema for registry.terraform.io/azure/alz 0.6.3 in 491.58µs

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by phx-tim-butters** [comment]
> Hi @phx-tim-butters, thanks for the port.
> 
> At the time of the last language server release two weeks ago, 0.6.3 was the latest provider version available. The next language server release will bundle the updated schema and fix the problem. Sorry for the inconvenience.
> 
> In the meantime, when you run `terraform init`, we'll use the matching provider schema from disk.

Hi there, Thanks for your reply.

That expands my understanding of why the Language Server uses certain version. Is there no way of forcing it to utilise the latest version of a provider at all?

**Comment by dbanck** [comment]
We bundle the latest version of all official and partner providers at build time to provide a good out-of-the-box experience. We use these schemas as a fallback, if we can't get a better matching version for your constraint.

When you run `terraform init`, Terraform will install your specific provider version on disk and the language server will pick that schema instead.
If you're curious, you can also find it in the log:
```
jobs.go:321: JOBS: Dispatching next job "6" (scheduler prio: -1, job prio: 0, isDirOpen: false): "OpTypeObtainSchema" for {"file:///Users/dbanck/tmp/issue1701"}
provider_schema.go:109: PSS: adding local schema (/Users/dbanck/tmp/issue1701, registry.terraform.io/azure/alz): 0xc00012fa88
jobs.go:461: JOBS: Finishing job "6": "OpTypeObtainSchema" for {"file:///Users/dbanck/tmp/issue1701"} (err = %!s(<nil>), deferredJobs: [])
```

**Comment by dbanck** [comment]
Exactly! That is how it should to work (and does for me).

**Without `init`**
<img width="950" alt="CleanShot 2024-03-01 at 11 34 48@2x" src="https://github.com/hashicorp/vscode-terraform/assets/45985/a6845336-931a-41ac-8791-7b508d5a24ec">

**After `init`**
<img width="950" alt="CleanShot 2024-03-01 at 11 34 23@2x" src="https://github.com/hashicorp/vscode-terraform/assets/45985/5102d201-4e6a-454c-884e-9ab0a115d5e2">


Can you close and reopen VS Code and then share the full log output with me?

**Comment by phx-tim-butters** [comment]
![image](https://github.com/hashicorp/vscode-terraform/assets/157139775/77aa8fc8-f7c7-48fe-ae0b-52d84b5fc3e8)

I've linked both an image and output from HashiCorp Terraform.

I performed a further Terraform Init, and still the issue continued.

[Output.txt](https://github.com/hashicorp/vscode-terraform/files/14460078/Output.txt)

**Comment by dbanck** [comment]
Oh, I think I know what's happening here. From the log output, it looks like you're hitting https://github.com/hashicorp/terraform-ls/issues/1540

Here is what happens:
1. The language server has parsed the configuration and is reading the required providers
2. It loads the appropriate bundled schema (0.6.3)
3. It runs all kinds of jobs that depend on a schema, such as validation
4. It loads the installed schema from disk (0.8.1), which is slower than 2.
5. It doesn't re-run the validation from 3. with the newer schema

If you change the file, like inserting a space, the validation error should go away, because the language server is now using the newer schema for everything.

**Comment by phx-tim-butters** [comment]
Super star - thank you! That's working. Leave the issue open and link it to the bug? or close it?

**Comment by dbanck** [comment]
Glad we figured this out! I know modifying the file isn't a good workaround, but since it only happens once right after startup, I hope it's not too bad.

I'll add this to the bug report and see if we can prioritize it in the future. I'll close it for now, but let me know if you run into any other problems.

**Comment by phx-tim-butters** [comment]
Oh my word, that's so much better.

It's working now - Many thanks.
