### ISSUE TITLE
Extension report problems in `~/.vscode-server/data/User/History/`

### ISSUE THREAD

**Issue by konstruktoid** [hashicorp/vscode-terraform#1705]
### Extension Version

v2.29.4

### VS Code Version

```
Version: 1.87.0 (user setup)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:41:44.469Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045
```

### Operating System

Windows 10 Pro Version 22H2

### Terraform Version

Terraform v1.7.4 on linux_amd64

### Steps to Reproduce

VSCode with Terraform extension on Windows, ssh remote to Linux with Terraform installed.

![image](https://github.com/hashicorp/vscode-terraform/assets/7956715/f5f0fe9d-24ca-42af-bbd7-6ad92bf8e4da)

### Expected Behavior

I assume the extension shouldn't care about old versions of a file.

### Actual Behavior

It reports problems in files placed in the history directory

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jpogran** [comment]
Thanks for the report @konstruktoid. When you use the SSH extension to remote into the linux server, do you open your home folder (`~` or `/home/<user_name>`) inside Code, in comparison to opening something like `~/src/some/path`?

Our extension searches inside the open directory for all Terraform files, to provide features like intellisense and go to reference. If you opened the home folder directly, it would explain walking the .vscode-server directory.

**Comment by konstruktoid** [comment]
Thanks @jpogran
I remote into my home directory in order to get access to all repositories at the same time.
