### ISSUE TITLE
Terraform Auto complete Not working

### ISSUE THREAD

**Issue by namithcc** [hashicorp/vscode-terraform#1723]
### Extension Version

v2.26.1

### VS Code Version

1.86

### Operating System

Windows 10 Enterprise 64bit

### Terraform Version

Terraform v1.7.5 on windows_amd64

### Steps to Reproduce

Terraform Auto complete Not working

### Expected Behavior

Extension should help for auto complete for terraform code, when we write new codes

### Actual Behavior

Extension should not helping for auto complete for terraform code

### Gist

NA

### Anything Else?

No

### Workarounds

No

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
Hi @namithcc, Thanks for raising the issue and sorry for the inconvenience! 

I see you're still using v2.26.1, while v2.29.5 is the latest version of the extension. Would it be possible for you to upgrade?

Can you share the log output of the extension? You can find it in the output pane by selecting `HashiCorp Terraform`.

**Comment by namithcc** [comment]
![image](https://github.com/hashicorp/vscode-terraform/assets/39516162/7ea6cedb-de73-4f45-a8be-ebdafc9d85a5)

launching language server: c:\Users\nchandrasekh\.vscode\extensions\hashicorp.terraform-2.30.2024042211-win32-x64\bin\terraform-ls.exe serve
Client: Stopped --> Starting
2024/04/23 13:55:56 serve_command.go:108: Starting terraform-ls 0.33.1
2024/04/23 13:55:56 service.go:106: Preparing new session ...
2024/04/23 13:55:56 langserver.go:102: Starting server (pid 11524; concurrency: 3) ...
2024/04/23 13:55:56 opts.go:215: Received request batch of size 1 (qlen=0)
2024/04/23 13:55:56 opts.go:215: Dequeued request batch of length 1 (qlen=0)
2024/04/23 13:55:56 rpc_logger.go:32: Incoming request for "initialize" (ID 0): {"processId":12532,"clientInfo":{"name":"Visual Studio Code","version":"1.88.0"},"locale":"en","rootPath":

**Comment by dbanck** [comment]
Thank you for confirming that you have the latest version!

Can you provide more information about the case where completion doesn't work as expected? With a snippet of code or a screenshot, I can try to reproduce it.

**Comment by namithcc** [comment]
![image](https://github.com/hashicorp/vscode-terraform/assets/39516162/2ab95a1a-3c8d-432b-980e-1bb1d93aefe6)

when I am trying to add a resource block as in the image, i am not getting auto complete/suggestions

**Comment by dbanck** [comment]
Thank you! That's weird, top-level completion should always work.

Can you share the list of your installed VS Code extensions so I can see if there are any conflicting ones? You can get the list by running `code --list-extensions`.

And secondly, can you please check if the `.tf` file has the correct language id assigned? It should say `Terraform` in the right corner at the bottom.

<img width="226" alt="CleanShot 2024-04-23 at 17 16 31@2x" src="https://github.com/hashicorp/vscode-terraform/assets/45985/60043a64-55fb-48d8-8871-163e1a080d22">
