### ISSUE TITLE
Syntax highlighting broken with `SELECT` statements

### ISSUE THREAD

**Issue by vthaker-alti** [hashicorp/vscode-terraform#1792]
### Extension Version

v2.31.0

### VS Code Version

Version: 1.91.0
Commit: ea1445cc7016315d0f5728f8e8b12a45dc0a7286
Date: 2024-07-01T18:52:41.959Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.5.0-41-generic

### Operating System

Linux 9cc62ba41e90 6.5.0-41-generic #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2 x86_64 GNU/Linux

### Terraform Version

Terraform v1.7.5 on linux_amd64

### Steps to Reproduce

1. Write a string with the word `SELECT` followed by a space
2. The syntax breaks as the LS no longer recognises it as a normal string.
3. Any brackets and comments following the string will not use proper highlighting anymore.

![image](https://github.com/hashicorp/vscode-terraform/assets/116595389/5bcf3a64-2374-4d0c-bd0d-41efe1331eda)

Note: It doesn't matter if you have any word after `SELECT` and space.

![image](https://github.com/hashicorp/vscode-terraform/assets/116595389/6dfa1a46-70a4-4ab6-8223-5a04fb75f335)

### Expected Behavior

The LS should treat it as a normal string

### Actual Behavior

The LS does not treat it as a normal string and breaks syntax highlighting after it

### Terraform Configuration

```terraform
locals {
  query_statement_1 = "SELECT"
  # something
}

locals {
  query_statement_2 = "SELECT "
  # something
}
```

### Project Structure

```sh
.
├── 0-providers.tf
└── 1-split-cost-data-export.tf
```

### Workarounds

Although not ideal, as a workaround we can use a temp local variable for the word `SELECT` to preserve the highlighting

![image](https://github.com/hashicorp/vscode-terraform/assets/116595389/5a96d03b-9a21-4157-af6b-0ece72cda582)

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
Hi @vthaker-alti,

Interesting discovery! At a first glance I can't reproduce the problem:
![CleanShot 2024-07-12 at 14 10 28@2x](https://github.com/user-attachments/assets/bf8114e3-2772-4b46-9fae-3073269231e7)

Our TextMate grammar, which is the source for the syntax highlighting, also doesn't handle the `SELECT` keyword in a special way either.

Do you have other SQL highlighting extensions installed? Can you share the your full list of active extensions (use `code --list-extensions `to get it)?

**Comment by vthaker-alti** [comment]
@dbanck Thank you for your response. You are correct, I installed an extension `iuyoy.highlight-string-code` ages ago that was causing the issue.

![image](https://github.com/user-attachments/assets/f0a3d041-fd34-4cf5-a778-60e0351cadeb)

After disabling it the issue went away. I uninstalled the extension now. Thanks for the tip.

Closing the issue as it was a user error.
