### ISSUE TITLE
"Format On Save" fails even when Terraform is on PATH

### ISSUE THREAD

**Issue by rymancl** [hashicorp/vscode-terraform#1808]
### Extension Version

v2.32.1

### VS Code Version

Version: 1.91.1 (Universal)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:07:54.982Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

### Operating System

macOS Sonoma 14.5

### Terraform Version

Terraform v1.9.0 on darwin_arm64

### Steps to Reproduce

Modify TF file and save.

VSCode `settings.json`:
```json
  "[terraform]": {
    "editor.defaultFormatter": "hashicorp.terraform",
    "editor.formatOnSave": true,
    "editor.formatOnSaveMode": "modificationsIfAvailable"
  },
  "[terraform-vars]": {
    "editor.defaultFormatter": "hashicorp.terraform",
    "editor.formatOnSave": true,
    "editor.formatOnSaveMode": "modificationsIfAvailable"
  },
```

`$PATH`:
```sh
-> echo $PATH | tr ':' '\n' | grep -i terraform
/Users/me/.local/share/mise/installs/terraform/1.9/bin
/Users/me/.local/share/mise/installs/iam-policy-json-to-terraform/latest/bin
```

```sh
-> which terraform
/Users/me/.local/share/mise/installs/terraform/1.9/bin/terraform
```

### Expected Behavior

Formatting happens on save

### Actual Behavior

No formatting on safe. 
Error in `Hashicorp Terraform` console:

> 2024/07/29 10:32:30 rpc_logger.go:32: Incoming request for "textDocument/codeAction" (ID 39): {"textDocument":{"uri":"file:///path/to/file/redacted/main.tf"},"range":{"start":{"line":0,"character":0},"end":{"line":103,"character":0}},"context":{"diagnostics":[],"only":["source.formatAll.terraform"],"triggerKind":2}}
2024/07/29 10:32:30 code_action.go:37: Code actions requested: "source.formatAll.terraform"
2024/07/29 10:32:30 code_action.go:46: Code actions supported: map[source.formatAll.terraform:true]
2024/07/29 10:32:30 code_action.go:19: code action failed: Terraform (CLI) is required. Please install Terraform or make it available in $PATH

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
Hi @rymancl,

I ran into a similar issue (but not Terraform related) with mise a while ago.
While the `PATH` design of mise works great in most cases, some things still require the use of shims.

Appending the mise shims directory to your path, so that we only use it as a fallback, should fix this problem. Here's what I'm doing (I'm using fish as shell):
```
# Add the shims to the end of PATH as a fallback for VS Code
set -x PATH $PATH ~/.local/share/mise/shims
```
