### ISSUE TITLE
VS Code -> HCP Terraform error: Failed to fetch organizations - Response validation failed

### ISSUE THREAD

**Issue by justinclayton** [hashicorp/vscode-terraform#1841]
### Extension Version

v2.32.3

### VS Code Version

Version: 1.93.0
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z (6 days ago)
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0

### Operating System

macOS Sonoma 14.5 (23F79)

### Terraform Version

Terraform v1.8.4 on darwin_arm64

### Steps to Reproduce

1. Perform successful auth login (supply token)
2. Refresh organizations

### Expected Behavior

Get returned a list of organizations so I can use the extension sidebar

### Actual Behavior

The above error in the title.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jpogran** [comment]
Hi @justinclayton, thanks for reporting this issue. This type of error usually means either the token used did not have permission to enumerate organizations, or the response returned was not in the shape we expected.

Assuming the token you used does have the correct permissions, can you try to login again and open the 'HashiCorp Terraform' output channel and paste the redacted content here? Or email me at james dot pogran at hashicorp dot com? The full error will be logged there and that will help us figure things out.
