### ISSUE TITLE
*.auto.tfvars errors out on valid tfvars config

### ISSUE THREAD

**Issue by neo4u** [hashicorp/vscode-terraform#1850]
### Extension Version

v2.32.3

### VS Code Version

Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

### Operating System

macOS Sequoia Version: 15.0 (24A335)

### Terraform Version

Terraform v1.4.6

### Steps to Reproduce

create a xyz.auto.tfvars file and create a variable.

```
xyz = 123
```

### Expected Behavior

We don't expect to see a lint error.asdfasdfasdf

### Actual Behavior

we see a lint error.asdfasdfasdf

<img width="742" alt="image" src="https://github.com/user-attachments/assets/ce55fc42-1ed1-4c0a-b00f-c8fd5c6a3607">

### Anything Else?

no

### Workarounds

name the file as xyz.tfvars which defeats the purpose.

### References

none

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
Hi @neo4u,

Thanks for the report! I have a few questions to better understand your issue.

Can you share more information about your workspace? Have you defined the variable you're referring to in the `.auto.tfvars' file in the same folder?

I have tried to reproduce the problem in a minimal example, but it works as expected.
![CleanShot 2024-10-24 at 11 12 18@2x](https://github.com/user-attachments/assets/9fcf87bb-2619-4677-8d70-bfaf09e4da1a)
