### ISSUE TITLE
Terraform Script Field Hover  Data Type Issue 

### ISSUE THREAD

**Issue by vynalavamshi** [hashicorp/vscode-terraform#1851]
### Extension Version

Latest version 

### VS Code Version

Lastest version 

### Operating System

Windows 

### Terraform Version

Latest 

### Steps to Reproduce

Hi 

While I am working with Terraform script in VS Code, when I Hover on any Terraform script filed it should show me that particular data type of the field, but it is loading infinitely, can you please me on this issue 

### Expected Behavior

It should Show me that particular data type of the field of Terraform Script 

### Actual Behavior

While I am working with Terraform script in VS Code, when I Hover on any Terraform script filed it should show me that particular data type of the field, but it is loading infinitely, can you please me on this issue 

### Terraform Configuration

```terraform
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "storageaccountname"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "GRS"

  tags = {
    environment = "staging"
  }
}
```

### Anything Else?

Help me on this Please 

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
Hi @vynalavamshi,

Thanks for the report. Which field are you trying to hover over? 

Can you please share the language server log output? And if possible, a screenshot of the actual behaviour? This will help us isolate the issue.

**Comment by vynalavamshi** [comment]
If I Hover on any of the filed  of Terraform script 



Expected result :

It should show that field data type 

Actual Result:

Infinitely Loading Hover

**Comment by dbanck** [comment]
Can you please share the full language server log output when this issue occurs? You can find it in VS Code's "Output" pane (View -> Output), then select "HashiCorp Terraform" at the top right.

**Comment by vynalavamshi** [comment]
> Can you please share the full language server log output when this issue occurs?
> 
> You can find it in VS Code's "Output" pane (View -> Output), then select "HashiCorp Terraform" at the top right.
> 
> 

![IMG_20241024_171338553.jpg](https://github.com/user-attachments/assets/adabba87-e1d6-4510-a20f-9d02bc564f3e)

**Comment by vynalavamshi** [comment]
> Can you please share the full language server log output when this issue occurs?
> 
> You can find it in VS Code's "Output" pane (View -> Output), then select "HashiCorp Terraform" at the top right.
> 
> 

![IMG_20241024_171447863.jpg](https://github.com/user-attachments/assets/03e5127b-773f-42fd-abd4-57e6d5221d80)

![IMG_20241024_171437669.jpg](https://github.com/user-attachments/assets/9def3721-04ec-4643-8059-0a3587a890de)

**Comment by dbanck** [comment]
Thanks for providing more information!

It looks like you have several Terraform extensions installed. Can you please uninstall all but the HashiCorp Terraform one?

**Comment by vynalavamshi** [comment]
> Thanks for providing more information!
> 
> It looks like you have several Terraform extensions installed. Can you please uninstall all but the HashiCorp Terraform one?

After uninstalled all, Except hashicorp Terraform I cannot see loading and I cannot see the field data type and no output is displayed it is empty and no problem is displayed

**Comment by dbanck** [comment]
That's odd! If the language server is running, there should be some log output available. You can find it here:
![https://user-images.githubusercontent.com/45985/239918316-8ad0a91b-c724-4f89-ae8f-1a992385bd77.png](https://user-images.githubusercontent.com/45985/239918316-8ad0a91b-c724-4f89-ae8f-1a992385bd77.png)

If not, can you please share your user settings? Ideally as JSON
![CleanShot 2024-10-24 at 16 01 15@2x](https://github.com/user-attachments/assets/0bb4b0a1-c0ec-4c0d-a0a7-63111d063a8d)

**Comment by vynalavamshi** [comment]
> That's odd! If the language server is running, there should be some log output available. You can find it here:
> ![https://user-images.githubusercontent.com/45985/239918316-8ad0a91b-c724-4f89-ae8f-1a992385bd77.png](https://user-images.githubusercontent.com/45985/239918316-8ad0a91b-c724-4f89-ae8f-1a992385bd77.png)
> 
> If not, can you please share your user settings? Ideally as JSON
> ![CleanShot 2024-10-24 at 16 01 15@2x](https://github.com/user-attachments/assets/0bb4b0a1-c0ec-4c0d-a0a7-63111d063a8d)
> 

![IMG_20241024_201243135.jpg](https://github.com/user-attachments/assets/42174ec3-3115-4ef3-a78d-98fbc98a7348)


Above is Output Snippet 


+++
Below is Json file snippets 
+++

![IMG_20241024_201309282.jpg](https://github.com/user-attachments/assets/928b72c1-5d39-4b95-bcde-104be6da6775)

![IMG_20241024_200756783.jpg](https://github.com/user-attachments/assets/e2f708fd-aafe-4094-b7ed-a69bef0c7dd3)

![IMG_20241024_201327373.jpg](https://github.com/user-attachments/assets/638d9088-2986-4174-af5d-1d8ed83bd6a4)

![IMG_20241024_201334912.jpg](https://github.com/user-attachments/assets/8b77a19e-f801-4cbe-8862-5ca40f72c2f8)

**Comment by dbanck** [comment]
Thanks for the screenshots! It looks like you have `"terraform.languageServer.enabled": false,` in your settings. Please try to remove this line or set it to `true`.

**Comment by dbanck** [comment]
That's great to hear.

I'm going to close this issue for now. Feel free to open another one if you run into any more problems.
