### ISSUE TITLE
"Unexpected attribute: An attribute named "private_endpoint_network_policies" is not expected here" and "Unexpected attribute: An attribute named "bgp_route_propagation_enabled" is not expected here"

### ISSUE THREAD

**Issue by dbhaigh** [hashicorp/vscode-terraform#1865]
### Extension Version

v2.33.0

### VS Code Version

Version: 1.94.2 (system setup)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

### Operating System

Windows 11 Home Version

### Terraform Version

v1.9.5

### Steps to Reproduce

create the terrafrm for an azurerm_subnet
set private_endpoint_network_policies = "Enabled"

or create the terraform for an azurerm_route_table
set bgp_route_propagation_enabled = false

### Expected Behavior

I expect the two settings to NOT be underlined red and be told that they are not expected here

### Actual Behavior

the two settings are marked red with the message that they are not expected here

However everything deploys correctly if I leave those settings in place

### Workarounds

My work-around has been to ignore the error message as a red herring as the latest subnet and route table modules still support these settings

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
@dbhaigh We have released a new version [2.34.0](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.34.0). This updates the schema to the latest version and should fix the validation error. The update should show up automatically in VS Code.

--- 

If you experience any other validation related bug, please let us know via a new issue.
