### ISSUE TITLE
Stuck on `Running 'HashiCorp Terraform' Formatter`

### ISSUE THREAD

**Issue by shinebayar-g** [hashicorp/vscode-terraform#1876]
### Extension Version

v2.33.0

### VS Code Version

Version: 1.95.2 (Universal)
Commit: e8653663e8840adaf45af01eab5c627a5af81807
Date: 2024-11-07T11:07:22.054Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0

### Operating System

24.1.0 Darwin Kernel Version 24.1.0

### Terraform Version

Terraform v1.9.8 on darwin_arm64

### Steps to Reproduce

We have a few thousand resources in our state and the extension just never works reliably. I have `"editor.formatOnSave": true,` enabled and whenever I save a file it just hang on `Running 'HashiCorp Terraform' Formatter`

![image](https://github.com/user-attachments/assets/e684394b-28ba-45e3-9595-4c17625c24c8)

![image](https://github.com/user-attachments/assets/4a18a415-23b8-43f4-9731-5d20047dc0d7)

### Expected Behavior

VSCode Extension works reliably

### Actual Behavior

It just hangs

### Anything Else?

[Zed Terraform extension](https://zed.dev/docs/languages/terraform) works fine and doesn't have this problem. I think it's not a language server issue at least.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mb-lakera** [comment]
Same here. Since recently it just started to hang when saving:

![image](https://github.com/user-attachments/assets/5d4e75ea-5a3b-4e33-9981-c88418e8138a)

**Comment by dbanck** [comment]
Thank you both for reporting this!

This issue may be related to this one: https://github.com/hashicorp/terraform-ls/issues/1857, so downgrading to the previous extension version may be a workaround for now.

To confirm a theory, are you by any chance using the AWS provider?

**Comment by mb-lakera** [comment]
Thank you for your response, I'll give it a try

> are you by any chance using the AWS provider?

Yes, I do

**Comment by arl-lakera** [comment]
thanks @dbanck ! Same here, I am using the AWS provider.

**Comment by shinebayar-g** [comment]
> Thank you both for reporting this!
> 
> This issue may be related to this one: [hashicorp/terraform-ls#1857](https://github.com/hashicorp/terraform-ls/issues/1857), so downgrading to the previous extension version may be a workaround for now.
> 
> To confirm a theory, are you by any chance using the AWS provider?

Thanks for the suggestion. I have downgraded to version `2.32.3` for now. I'll observe if it helps.

I use GCP provider.

**Comment by shinebayar-g** [comment]
Update: Extension `2.32.3` is noticeably better. It reduced the indefinite loading spinner to around 10 seconds.

**Comment by mb-lakera** [comment]
Same here, so far `2.32.3` works fine. It does take sometimes quite a few seconds, but that is not a problem in comparison to the hanging `2.33.0`

**Comment by shinebayar-g** [comment]
Updated: I tried installing the https://github.com/hashicorp/terraform-ls/ by myself and set the `"terraform.languageServer.path": "/opt/homebrew/bin/terraform-ls"` in my settings. It's performing much better.

**Comment by dbanck** [comment]
We have released a new version of vscode-terraform: [2.34.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.34.1), which includes many bug fixes and some performance improvements (https://github.com/hashicorp/hcl-lang/pull/426 being the most significant).
The update should show up automatically in VS Code.

Please let us know if it solves (or improves) the issues you were experiencing. I tried the new version on an older Celeron box with some sample configurations and it felt similar to 2.32.3.

**Comment by shinebayar-g** [comment]
Hi @dbanck , thanks for the update. It's working much better compared to previous versions.

I've noticed that some resources' `Go to Definition` is not working when they're updated. Could this be related to the recent changes? Otherwise, great improvement!

**Comment by dbanck** [comment]
Thanks for the quick feedback!

Do you mind opening a new issue for the `Go to Definition` problem you are seeing? This will allow us to dig into this separately.

**Comment by shinebayar-g** [comment]
Sure, will do. This is already so much better and usable. Thanks for the fix.
