### ISSUE TITLE
Incorrectly Highlights Syntax as Incorrect for Cloudflare Provider

### ISSUE THREAD

**Issue by noah-kaufman-aem** [hashicorp/vscode-terraform#1878]
### Extension Version

v2.33.0

### VS Code Version

Version: 1.95.2 (user setup)
Commit: e8653663e8840adaf45af01eab5c627a5af81807
Date: 2024-11-07T11:07:22.054Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

### Operating System

Windows 11

### Terraform Version

v1.9.5

### Steps to Reproduce

Set up the Cloudflare provider, and then attempt to define a subdomain on a DNS zone like this:

resource "cloudflare_zone" "product_domain" {
  account_id = "insert-account-id-here"
  zone       = "subdomain.myzone.com"
  type       = "full"
}

The Terraform plug-in will highlight this syntax as being incorrect and will suggest syntax that will not pass a "terraform validate" command. This is the CORRECT syntax, and the suggested syntax is wrong.

### Expected Behavior

The plug-in should indicate that this syntax is correct.

### Actual Behavior

The syntax is marked as incorrect.

### Workarounds

NONE.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
Thanks for the report @noah-kaufman-aem!

I believe https://github.com/hashicorp/vscode-terraform/issues/1869 already covers this, so I'm going to close this as a duplicate to keep the conversation in one place.
