### ISSUE TITLE
Error: Unexpected Block 'pod_identity_association' in aws_eks_addon Resource Configuration

### ISSUE THREAD

**Issue by BernardTheFour** [hashicorp/vscode-terraform#1887]
### Extension Version

 v2.34.0 

### VS Code Version

Version: 1.95.3 (user setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

### Operating System

Ubuntu 22.04.3 LTS (WSL)

### Terraform Version

Terraform v1.10.0 on linux_amd64

### Steps to Reproduce

1. Install terraform official vscode extension [https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform](https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform)
2. Use resource "aws_eks_addon" with AWS provider version v5.78.0
3. Use pod_identity_association block for VPC CNI

### Expected Behavior

The syntax is correct and no error. Please refer to this documentation [https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster)

### Actual Behavior

Unexpected block: Blocks of type "pod_identity_association" are not expected here - Terraform

### Terraform Configuration

```terraform
resource "aws_eks_addon" "vpc_cni" {
  count         = var.self_manage_system_addons != null ? 1 : 0
  cluster_name  = try(aws_eks_cluster.encrypted[0].id, aws_eks_cluster.unencrypted[0].id)
  addon_name    = "vpc-cni"
  addon_version = var.self_manage_system_addons.vpc_cni_version

  resolve_conflicts_on_update = "NONE"

  service_account_role_arn = var.self_manage_system_addons.cni_iam_service_role_arn

  // Unexpected block: Blocks of type "pod_identity_association" are not expected here
  pod_identity_association { 
    role_arn        = var.self_manage_system_addons.cni_iam_service_role_arn
    service_account = "aws-node"
  }
}

terraform {
  backend "s3" {
    bucket       = "xxxx"
    key          = "xxxx"
    region       = "xxxx"
    session_name = "xxxx"
  }

  required_providers {
    aws = {
      source  = "registry.terraform.io/hashicorp/aws"
      version = "5.78.0"
    }
  }
}

provider "aws" {
  region = local.aws_region
  default_tags {
    tags = local.aws_tags
  }
}
```

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
Hi @BernardTheFour,

Thanks for the detailed report 🙂  Unfortunately I can't reproduce the error.

In version [v5.75.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.75.0) of the aws provider, `pod_identity_association` was added. The language server in vscode-terraform v2.34.0 ships with [v5.76.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.76.0), so it should be aware of the block.

Can you please check the output log in VSCode for the terraform-ls version you are using? This should also tell us if you're using a custom terraform-ls version by setting a custom path (`"terraform.languageServer.path"`) (which you usually want to avoid).
![CleanShot 2024-12-03 at 09 50 38@2x](https://github.com/user-attachments/assets/e8791d5b-aebf-40f0-9bac-8b43eba2c513)

**Comment by BernardTheFour** [comment]
Thanks, problem solved, on its own.
I don't know what happened, all I did is just to reload the vscode window.

**Comment by BernardTheFour** [comment]
Thanks, problem solved, on its own.
I don't know what happened, all I did is just to reload the vscode window.
