### ISSUE TITLE
Add install instructions

### ISSUE THREAD

**Issue by frankclaassens** [hashicorp/vscode-terraform#191]
It would be great if you could add install instructions in the readme for those new to VSCODE.

Thanks

**Comment by mauve** [comment]
I am a little bit unsure what instructions I can provide which are not already covered by the official vscode code? I would welcome a PR if you have the time,

**Comment by paultyng** [comment]
You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out. I'll see if we can get this in the README if its not already in there.

**Comment by aeschright** [comment]
The README covers this information now.
