### ISSUE TITLE
Initialised module from GitHub not being recognised

### ISSUE THREAD

**Issue by madi-parloa** [hashicorp/vscode-terraform#1915]
### Extension Version

v2.34.0

### VS Code Version

Version: 1.95.3 (Universal)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.6.0

### Operating System

macOS Sonoma Version 14.7 Apple M3 Pro

### Terraform Version

Terraform v1.10.1 on darwin_arm64

### Steps to Reproduce

1. Add this module to your `main.tf` file:
```
module "alias_no_refresh" {
  source = "git::https://github.com/terraform-aws-modules/terraform-aws-lambda.git//modules/alias"

  refresh_alias = false
  name          = "current-no-refresh"
}
```
2. Run `teraform init` or `terraform get`
3. Hover on `refresh_alias`

### Expected Behavior

Should show a popup with information about this input variable

### Actual Behavior

No popup. HashiCorp Terraform Extension output logs show:
```
2024/12/10 22:03:38 opts.go:215: Received request batch of size 1 (qlen=0)
2024/12/10 22:03:38 opts.go:215: Dequeued request batch of length 1 (qlen=0)
2024/12/10 22:03:38 rpc_logger.go:32: Incoming request for "textDocument/hover" (ID 99): {"textDocument":{"uri":"file:///Users/<redacted>/Documents/<redacted>/<redacted>-infra/<redacted>/modules/main/main.tf"},"position":{"line":26,"character":4}}
2024/12/10 22:03:38 hover.go:41: Looking for hover data at "main.tf" -> hcl.Pos{Line:27, Column:5, Byte:522}
2024/12/10 22:03:38 hover.go:43: received hover data: (*lang.HoverData)(nil)
2024/12/10 22:03:38 rpc_logger.go:48: Error for "textDocument/hover" (ID 99): [-32098] main.tf (27,5): unknown attribute "refresh_alias"
2024/12/10 22:03:38 opts.go:215: Completed 1 requests [3.703208ms elapsed]
[Error - 10:03:38 PM] Request textDocument/hover failed.
  Message: main.tf (27,5): unknown attribute "refresh_alias"
  Code: -32098 
```

### Anything Else?

I also tried doing the same on GitHub Codespaces with the same results.

### Workarounds

https://github.com/hashicorp/vscode-terraform/issues/1440#issuecomment-2241792580

### References

 - #1440

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
Hi @madi-parloa,

Thanks for the report! I'm able to reproduce the problem. I'm sure it's worked before, as I've used your example in the past when working on https://github.com/hashicorp/terraform-ls/pull/1760.

Bisecting 0.34.0 and the current language server version shows that https://github.com/hashicorp/terraform-ls/commit/0a919116030691221ab18f67c8188c9adc1bc182 is the first bad commit where things stopped working. I or someone else on the team will look into this.

**Comment by madi-parloa** [comment]
Unfortunately, the error is still there for me in version 2.34.2
@ansgarm were you able to reproduce with an expected behavior?
