### ISSUE TITLE
CodeLens usage has horrible UX

### ISSUE THREAD

**Issue by oliversalzburg** [hashicorp/vscode-terraform#193]
![QbJ1uCMtdW](https://user-images.githubusercontent.com/1658949/60084955-c0325e80-9738-11e9-9e54-af9db938a1c1.gif)

This constant jumping up and down of the code you're looking at is so annoying. Am I doing something wrong here? How do others work like this?

Every time you start a new line in a block, the CodeLens row is hidden, when you finish the keyword, it pops back in. Especially when you work at the end of larger documents, this is unbearable.

**Comment by mauve** [comment]
I think that is a "feature" of vscode, we just provide the codelenses, the rendering is done by vscode itself.

**Comment by mauve** [comment]
there is supposed to have been some improvement for that in a recent vscode version.

**Comment by oliversalzburg** [comment]
I have followed the related tickets in VS Code, a fix in that area was applied, but it is not effective here.

The change in VS Code revolved around the CodeLens only appearing shortly after a document was opened and having this skipping all the time when switching between open editors. The change has limited effect, because it only applies to a certain amount of open editor windows. Overall CodeLens is still a very broken feature UX wise.

This specific case is different, as the CodeLens is hidden when the document is temporarily syntactically incorrect. When editing a longer document, the editor becomes unusable unless CodeLens is disabled.

I am honestly asking how anyone is able to work with this, because I can't :D

**Comment by mauve** [comment]
you can disable the codelens feature for terraform specifically. I currently have no time to work on the plugin so if you have the time to apply a fix somehow then that would be greatly appreciated.

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.
