### ISSUE TITLE
Syntax highlighting: # and \" inside strings

### ISSUE THREAD

**Issue by rimutaka** [hashicorp/vscode-terraform#194]
1. `#` inside `request_mapping_template = "## dummy\n{}"` is rendered as a beginning of a comment. They should not be highlighted.
2. Escaped double quotes `\"` are rendered as starting/ending a string value. They should be ignored. 

![image](https://user-images.githubusercontent.com/5926028/60234588-ed2d6f80-98f8-11e9-9f96-762348f45048.png)

**Comment by Dovry** [comment]
Same issue, but just to hightlight the problem better visually.

before escaping `"` in `override_special`
![image](https://user-images.githubusercontent.com/15201298/65862560-c86cec00-e36e-11e9-8672-98e6eaf202d6.png)

after scaping `"` in `override_special`
![image](https://user-images.githubusercontent.com/15201298/65862606-e8041480-e36e-11e9-8629-c73120e57f07.png)

Theme is [1984](https://marketplace.visualstudio.com/items?itemName=juanmnl.vscode-theme-1984) light

**Comment by jpogran** [comment]
@rimutaka is this still an issue? I can't get syntax highlighting to break after including comments inside a string:

![image](https://user-images.githubusercontent.com/272569/148997867-498a41e0-fe3d-41b7-bcb9-810eb3498421.png)

@dovry is this still an issue? I can't quite reproduce your issue. Words inside line comments do not highlight for me, regardless of whether there are other parts of the file that have escaped or not escaped characters. Can you double check that there isn't another extension installed that supports highlighting Terraform files which is conflicting with ours?

![image](https://user-images.githubusercontent.com/272569/148998287-c73b67ca-1fc2-4ee8-b50a-44b6a13295d6.png)

![image](https://user-images.githubusercontent.com/272569/148998315-7dc00a5b-d605-4586-9a81-da2970fb5f43.png)

I'm going to close this for now, but if this is still an issue please respond and we'll re-open.

**Comment by dovry** [comment]
@jpogran I reinstalled the extension to verify that tthis does not seem to be a problem for me anymore.

![image](https://user-images.githubusercontent.com/15201298/149124177-a0cd209e-17e9-4b31-a880-8ca61416a71e.png)
