### ISSUE TITLE
Proxy Authentication Required

### ISSUE THREAD

**Issue by mayureshs** [hashicorp/vscode-terraform#196]
Running Terrafrom commands within VSCode gives Proxy Authentication error below. However running the same Terraform command in Command Prompt works fine. I have confirmed that VS code has no proxy entry in its settings file.

google_compute_project_metadata.ssh: google_compute_project_metadata.ssh: Error reading Project metadata for project "PROJECT_ID": Get https://www.googleapis.com/compute/v1/projects/PROJECT_ID?alt=json&prettyPrint=false: Post https://oauth2.googleapis.com/token: Proxy Authentication Required

**Comment by mauve** [comment]
Do you have some settings, e.g. backend settings or environment variables set which you do not specify when running from within vscode?

**Comment by mayureshs** [comment]
@mauve There is enterprise proxy but for vs code i dont need to specify anything to reach for other resources/extensions with in vscode.

**Comment by mauve** [comment]
Are you sure that you have the required environment variables and authentication stuff specified when running from within vscode?

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.
