### ISSUE TITLE
Multiple Versions of Terraform

### ISSUE THREAD

**Issue by spaceygithub** [hashicorp/vscode-terraform#201]
I'm sorry to ask what is almost certainly a dumb question but I've got multiple versions of Terraform installed on my windows machine. I have to be very careful to target the right version when running anything that might change the remote state as I don't want to upgrade that to a new version. So, I set  required_version = "= 0.11.11" in most of the code I have. 

I notice the settings for this module has a section to specify terraform.path and below this it suggests you can specify multiple paths and versions.

![image](https://user-images.githubusercontent.com/35881878/61709733-c6235b80-ad47-11e9-8f7b-e06e7a1bfcf7.png)

I've tried setting 
"terraform.paths": ["C:\\HashiCorp\\Terraform\\terraform_0.11.11.exe", "C:\\HashiCorp\\Terraform\\terraform_0.11.10.exe"]
but I can't find the right syntax. I don't see another issue / question addressing this or any instructions on the wiki but might have missed it. 
Regarding the versions of terraform, is the module clever enough to link the right path / version to the required_version statement? or do i need to change version somehow?

Thanks for all those who contribute to this module, I can see how it will help me no end.

**Comment by mauve** [comment]
The syntax looks to be correct, you can check the `output` tab to see which terraform executables it detects during startup (or when the configuration is changed). During startup it will print out several different things depending on if version parsing works correctly or not, the success case looks like this: https://github.com/mauve/vscode-terraform/blob/3d0d10adbc5bd3c84378027aca169a39ab84ffad/src/runner.ts#L194

When the plugin invokes terraform it will pick the correct binary version (the best match according to the `required_version` value).

**Comment by paultyng** [comment]
The way to manually set the executable path in the extension / LS has changed, you can find instructions here: https://github.com/hashicorp/vscode-terraform/wiki/Manually-Setting-the-Terraform-Executable-Path
