### ISSUE TITLE
IntelliSense support for Docker

### ISSUE THREAD

**Issue by kasunsjc** [hashicorp/vscode-terraform#204]
Hi,

I would like to suggest a feature request to support IntelliSense for docker/kubernetes resources.

Thanks

**Comment by paultyng** [comment]
Completion data (including providers, attributes, blocks, etc) in the [hashicorp/terraform-ls](https://github.com/hashicorp/terraform-ls) is now provided by the provider itself, and its the same schema and provider lists Terraform itself uses, so should no longer have these types of issues.
