### ISSUE TITLE
Linting failed, more information in the output tab.

### ISSUE THREAD

**Issue by jbovet** [hashicorp/vscode-terraform#205]
Issue Type: <b>Bug</b>

Linting failed, more information in the output tab.

Extension version: 1.3.12
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by brentarias** [comment]
I'm having the same "linting failed, more information in the output tab" problem.  In my output tab, no information is provided at all...so even that isn't working.  I get this error when I explicitly request linting to be performed.  I do not have the "linting on save" feature enabled.

In my extensions explorer, it says my "Terraform" extension is version 1.4.0.  However the details web page offered when I click on the Terraform extension says "release v1.3.12".  So I'm not sure which is correct.  My VS Code version is 1.38.1.  My OS is Windows 10 v1709.

The Terraform extension is performing its other duties successfully.  It provides syntax highlighting and intellisense as expected.

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.
