### ISSUE TITLE
Linting not working

### ISSUE THREAD

**Issue by vazkarvishal** [hashicorp/vscode-terraform#207]
Hello,

The linting does not seem to be working as expected.

![image](https://user-images.githubusercontent.com/13076513/62713744-23c8d080-b9f5-11e9-8349-3acf81341ca8.png)

Even though this is valid code, I am getting linting errors. Any suggestions?

Thanks,
Vish

**Comment by killyosaur** [comment]
you working in TF 0.12? if so that is valid for TF 0.12.x but not TF 0.11.x (which is the only version of the HCL language supported at the moment)

**Comment by mauve** [comment]
I will do a release which supports TF 0.12 in a few days.

**Comment by vazkarvishal** [comment]
Thanks @mauve, Let me know when you have pushed an update and I will update the extension.

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.
