### ISSUE TITLE
Terraform LSP consuming too much CPU

### ISSUE THREAD

**Issue by goranvrbaski** [hashicorp/vscode-terraform#211]
Hello,

I have a problem with Terraform LSP. When I open a project that contains terraform files my CPU goes crazy. It happens on projects with different file count. I've tested with a project that contains only one file (main.tf) and also with a project with multiple files (100+).

https://prnt.sc/p0mcz7

**Comment by juliosueiras** [comment]
@goranvrbaski is the issue still happening after the newest version?

**Comment by stefaniuk** [comment]
I've got the latest version of VSCode as well as the extension. Every time I open a project containing Terraform files the CPU usage goes annoyingly high triggering a noisy fan.

I'm on the latest macOS and all the brew packages are up-to-date. This is an unlikely an issue with my configuration and it appears to me that it is the `terraform-lsp` process only.

**Comment by chrisbalmer** [comment]
Same issue here. The moment I open a Terraform file, `terraform-lsp` jumps up in the process list consuming almost 2 CPU cores. Latest VSCode and plugin version 1.4.0.

**Comment by chrisbalmer** [comment]
Changing the language server to v0.0.10 using the "Terraform: Install/Update Language Server" command fixed the issue for me.

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.
