### ISSUE TITLE
Executable paths setting needs restart

### ISSUE THREAD

**Issue by oker1** [hashicorp/vscode-terraform#212]
If the paths are changed the changes are not reflected until editor is restarted.

**Comment by radeksimko** [comment]
I believe that all v2, or at least the latest 2.7.0 version of the extension prompts for reload.

![2021-02-24 17 37 55](https://user-images.githubusercontent.com/287584/109041783-4ef23e00-76c7-11eb-8445-ed316b3d415b.gif)

Therefore I'm going to close this issue, but feel free to open a new one if the problem persists.
