### ISSUE TITLE
VSCode preserveFocus

### ISSUE THREAD

**Issue by benmontour-wf** [hashicorp/vscode-terraform#213]
Currently with terraform-lsp installed alongside the this extension the Output window to steal window focus on occasion. There is another issue for VSCode where they state that extension authors need to add preserveFocus: true. This prevents a workflow disruption to the user by not forcing their editor to switch to the Output view. Issue comment linked below.
https://github.com/Microsoft/vscode/issues/31474#issuecomment-319032829
I did open an Issue with terraform-lsp but they have stated that this is an issue with the client extension vs them as the server, so I'm opening this Issue.

**Comment by paultyng** [comment]
The way the LS and extension are integrated has changed in the 2.0.0 candidate, this should only happen if the LS encounters an error, and hopefully we can add special casing to handle expected errors (ie. workspace uninitialized) as opposed to stealing focus.

**Comment by paultyng** [comment]
Related to #329

**Comment by paultyng** [comment]
I'm going to close this in favor of #329 (or other specific issues for error handling). I think its still best if unexpected errors are shown somewhere, and currently the trace window is the best place for that.
