### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by smiller171** [hashicorp/vscode-terraform#215]
- Issue Type: `Bug`
- Extension Name: `terraform`
- Extension Version: `1.4.0`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.38.1`

```json 
{
	"messages": [
		{
			"type": 1,
			"message": "Command `terraform.validate` appears multiple times in the `commands` section.",
			"extensionId": {
				"value": "mauve.terraform",
				"_lower": "mauve.terraform"
			},
			"extensionPointId": "commands"
		},
		{
			"type": 1,
			"message": "Command `terraform.reindex` appears multiple times in the `commands` section.",
			"extensionId": {
				"value": "mauve.terraform",
				"_lower": "mauve.terraform"
			},
			"extensionPointId": "commands"
		},
		{
			"type": 1,
			"message": "Command `terraform.preview-graph` appears multiple times in the `commands` section.",
			"extensionId": {
				"value": "mauve.terraform",
				"_lower": "mauve.terraform"
			},
			"extensionPointId": "commands"
		},
		{
			"type": 1,
			"message": "Command `terraform.show-plan` appears multiple times in the `commands` section.",
			"extensionId": {
				"value": "mauve.terraform",
				"_lower": "mauve.terraform"
			},
			"extensionPointId": "commands"
		}
	],
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 667,
		"activateCallTime": 13,
		"activateResolvedTime": 437,
		"activationEvent": "onLanguage:terraform"
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot set property 'excludePaths' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot set property 'excludePaths' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot set property 'excludePaths' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot set property 'excludePaths' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot set property 'excludePaths' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot set property 'excludePaths' of undefined"
		}
	]
}
```

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.
