### ISSUE TITLE
cidrsubnet Function not recognized

### ISSUE THREAD

**Issue by MasterSpider** [hashicorp/vscode-terraform#217]
This function is not recognised: https://www.terraform.io/docs/configuration/functions/cidrsubnet.html
Error Unknown token

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.

**Comment by radeksimko** [comment]
It's worth noting the new language server does not recognize any functions yet - this is tracked under https://github.com/hashicorp/terraform-ls/issues/37 but it should not error because of that, it just won't come up in completion (yet) and elsewhere.
