### ISSUE TITLE
Syntax Highlighting for variable type bool

### ISSUE THREAD

**Issue by AndyHollings** [hashicorp/vscode-terraform#230]
Syntax Highlighting for variable type bool fails to recognise correct syntax.

**Steps to reproduce NB this syntax IS VALID**

variable foo {
    type = bool
    default = false
    description = "foo is false"
}

**Steps to reproduce NB this syntax IS NOT VALID, quoted bool is not allowed in .12**
variable foo {
    type = "bool"
    default = false
    description = "foo is false"
}

**Comment by Svince123** [comment]
I have it too

**Comment by alexjurkiewicz** [comment]
<img width="274" alt="Screen Shot 2020-06-15 at 7 56 38 pm" src="https://user-images.githubusercontent.com/379509/84644305-57905300-af42-11ea-934e-24dfb41f96bd.png">

This appears to work fine in v2.0.1
