### ISSUE TITLE
"templatefile" function parsed paths incorrectly

### ISSUE THREAD

**Issue by Vermyndax** [hashicorp/vscode-terraform#231]
This bit of code in a Terraform file:

`templatefile("${path.module}/files/launch-template-user-data.tpl", {`

...is parsed incorrectly, and claims the file doesn't exist on disk:

> Call to function "templatefile" failed: no file exists at /files/launch-template-user-data.tpl.

The file actually does exist, and the Terraform template finds the file and applies correctly.

**Comment by ossareh** [comment]
I confirm the same experience

| sofware | version |
| :---: | :---: |
| vscode | 1.39.1 |
| mauve.terraform | 1.4.0 |

**Comment by voodevil** [comment]
I'm seeing similar behavior with the file() statement:
`file("${path.root}/testfile.xml")` returns 

> This object does not have an attribute named "root".

`file("testfile.xml")` returns

> Call to function "file" failed: no file exists at testfile.xml.

If I hardcode the full path, it works.

vscode: 1.39.2
mauve.terraform: 1.4.0

**Comment by caleb15** [comment]
Same issue as @voodevil , `file` is not parsing relative file paths correctly. If I make the file path relative to the root of the workspace it's fine but if it's relative to the file itself it fails. We only run terraform from the folder that contains the file, not the workspace root, so in our use case it should not give an error.

**Comment by tristan-cartledge-sd** [comment]
I can confirm the same issue
  
`template = "${file("${path.module}/tasks/task_definition.json")}"`

we don't run from the workspace root either and rely on `${path.module}`

**Comment by ronmcmillian** [comment]
I can confirm the same as well 

`content = file("${path.module}/configs/ch2-asw-01.conf")`

Throws the same error

**Comment by dblooman** [comment]
Is there a way to disable the warning?

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.
