### ISSUE TITLE
Expired certificate warning on https://api.github.com

### ISSUE THREAD

**Issue by acdha** [hashicorp/vscode-terraform#233]
Issue Type: <b>Bug</b>

If I attempt to install the Terraform Language Server, I get an error saying that the certificate for https://api.github.com has expired. The same URL loads in curl, httpie, all browsers, my system clock is correct, etc. but I did notice that Github has disabled TLS versions lower than 1.2 and was wondering whether it was possible that the error message was incorrect.

Extension version: 1.4.0
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 1700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.

**Comment by acdha** [comment]
2.0.0rc1 did fix this issue

**Comment by paultyng** [comment]
There is a minor change coming in rc2 that we are going to query releases from releases.hashicorp.com that should also prevent recurrence here. But if you are using some sort of corporate proxy you may need to add that domain to the allow list.

**Comment by acdha** [comment]
Thanks — that may be an issue for us

**Comment by paultyng** [comment]
@acdha do you do an online `terraform init` currently? For 0.11 and 0.12 it is already communicating with `releases.hashicorp.com` to download providers so if you are downloading providers already, it should be fine. If you were currently "side loading" your providers manually though due to this limitation, it may still exist.

**Comment by acdha** [comment]
This was a vanilla install but it doesn’t happen with the 2.0 releases so it must have been fixed along the way.
