### ISSUE TITLE
linter marks string and bool as typo

### ISSUE THREAD

**Issue by AndyHollings** [hashicorp/vscode-terraform#237]
Both these are marked as typo's

varable var1 {
**type = string**
}

varable var2 {
**type = bool**
}

When in fact a) both correct and b) in the case of bool unquoted is a requirement, quoted bool is syntacially incorrect.

**Comment by danvy** [comment]
Same issue here

**Comment by jvanceACX** [comment]
In a vacuum it would be pretty minor, but it seems to break parsing for the rest of the file so you can no longer see reference counts.

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.
