### ISSUE TITLE
Language Server Crashes Conitnually

### ISSUE THREAD

**Issue by smifffystuff** [hashicorp/vscode-terraform#251]
After updated the extension and enabling the language server, c=i can see that the language server keep crashing:

2019/11/28 15:45:50 Server started
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x60 pc=0xd82c12]

goroutine 22 [running]:
github.com/juliosueiras/terraform-lsp/tfstructs.GetDiagnostics(0xc00045e040, 0x33, 0xc000014030, 0x2a, 0x0, 0x0, 0x1)
	/home/travis/gopath/src/github.com/juliosueiras/terraform-lsp/tfstructs/diags.go:51 +0x642
main.TextDocumentDidChange(0x11c8580, 0xc00052c240, 0xc00038e000, 0x31, 0x2, 0xc000010000, 0x1, 0x4, 0x0, 0x0)
	/home/travis/gopath/src/github.com/juliosueiras/terraform-lsp/main.go:458 +0x155
reflect.Value.call(0xe8d380, 0x1040ed8, 0x13, 0xff7573, 0x4, 0xc00052c3f0, 0x2, 0x2, 0xc000459c00, 0xc00000bdc8, ...)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/reflect/value.go:447 +0x45b
reflect.Value.Call(0xe8d380, 0x1040ed8, 0x13, 0xc00052c3f0, 0x2, 0x2, 0xe51100, 0xc00052c3f0, 0x1)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/reflect/value.go:308 +0xab
reflect.Value.Call-fm(0xc00052c3f0, 0x2, 0x2, 0x1, 0xc00042e2c0, 0x1)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:211 +0x67
github.com/creachadair/jrpc2/handler.newHandler.func7(0x11c8580, 0xc00052c240, 0xc0002c4680, 0xc0002c4070, 0xc000473ee8, 0x10, 0xc000473ee0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:222 +0x232
github.com/creachadair/jrpc2/handler.Func.Handle(0xc00051c120, 0x11c8580, 0xc00052c240, 0xc0002c4680, 0x0, 0x0, 0x11c8580, 0xc00052c240)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:23 +0x4b
github.com/creachadair/jrpc2.(*Server).invoke(0xc000532000, 0x11c8500, 0xc0000300a8, 0x11bd8e0, 0xc00051c120, 0xc0002c4680, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:294 +0x1b7
github.com/creachadair/jrpc2.(*Server).dispatch.func1(0xc000454170, 0xc000532000, 0xc000370000)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:185 +0x108
created by github.com/creachadair/jrpc2.(*Server).dispatch
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:183 +0x141
[Info  - 15:46:10] Connection to server got closed. Server will restart.

This happens after every keystroke whilst editing a .tf file.

I have terraform 0.12.16 installed and vscode 1.40.2.

**Comment by GolubevV** [comment]
Same story with:

- Terraform binary: 0.12.13
- VSCode: 1.41.1
- Terraform plugin:  1.4.0
- Terraform LSP: 0.0.9

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.
