### ISSUE TITLE
Installing language server errors when terraform is not found

### ISSUE THREAD

**Issue by NZSmartie** [hashicorp/vscode-terraform#258]
As a Windows user, I have terraform installed in Windows Subsystem for Linux and do all my AWS and Terraform work in there. 
Since I do not have a terraform binary available in Windows, Installation of the terraform-lsp language server will flash this error message in Visual Studio Code then disappear as the terminal closes immediately.

![image](https://user-images.githubusercontent.com/1032029/70397971-869da780-1a7b-11ea-9010-7bb556c21d3c.png)
> ```
> terraform: The term 'terraform' is not recognized as the name of a cmdlet, function, script file or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> + terraform init
> + ~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (terraform:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> ```

Note that I had to enable and disable the language server several times to try and get this screenshot as the terminal closes right away (then transcribed it to help make searching for it easier). making it difficult to understand the problem.

**Comment by NZSmartie** [comment]
A fix is to either:
* Install terraform
* Set up remote-WSL for VSCode and re-open the window in WSL mode, then re-install the terraform extension

I've just done the later and it works. However, a friendly error dialog box would be a good way to inform the user about the lack of terraform on the Windows host.

**Comment by thefluffysysop** [comment]
Wow thank you @NZSmartie , I had no idea what was going wrong until I saw your post. I have the same issue. In our case, we (are forced to) code on a (Physical!) Windows 2008R2 well away from the actual execution environment. (Have pity on us).

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.
