### ISSUE TITLE
Please add VSCode support for appsync resolvers and functions

### ISSUE THREAD

**Issue by wolfgangmeyers** [hashicorp/vscode-terraform#259]
I've noticed that the code-completion support is missing for a couple of appsync resources types:

Appsync resolvers: https://www.terraform.io/docs/providers/aws/r/appsync_resolver.html
Appsync functions:
https://www.terraform.io/docs/providers/aws/r/appsync_function.html

I've been working without these well enough but it would be helpful if they were supported.

**Comment by wolfgangmeyers** [comment]
Odd, they do seem to be supported. But when you first start writing either of those, the autocomplete doesn't list them. Then if you dismiss the popup and then hit ctrl-space, they show up in autocomplete.

**Comment by paultyng** [comment]
Completion data (including providers, attributes, blocks, etc) in the [hashicorp/terraform-ls](https://github.com/hashicorp/terraform-ls) is now provided by the provider itself, and its the same schema and provider lists Terraform itself uses, so should no longer have these types of issues.
