### ISSUE TITLE
No autocomplete support for Logic Apps resource

### ISSUE THREAD

**Issue by brandonh-msft** [hashicorp/vscode-terraform#262]
not seeing any of the resource types for Logic Apps in the auto-complete. These should be added:
- [ ] [azurerm_logic_app_action_custom](https://www.terraform.io/docs/providers/azurerm/r/logic_app_action_custom.html)
- [ ] [azurerm_logic_app_action_http](https://www.terraform.io/docs/providers/azurerm/r/logic_app_action_http.html)
- [ ] [azurerm_logic_app_trigger_custom](https://www.terraform.io/docs/providers/azurerm/r/logic_app_trigger_custom.html)
- [ ] [azurerm_logic_app_trigger_http_request
](https://www.terraform.io/docs/providers/azurerm/r/logic_app_trigger_http_request.html)
- [ ] [azurerm_logic_app_trigger_recurrence](https://www.terraform.io/docs/providers/azurerm/r/logic_app_trigger_recurrence.html)
- [ ] [azurerm_logic_app_workflow](https://www.terraform.io/docs/providers/azurerm/r/logic_app_workflow.html)

I actually question the usefulness of anything other than `azurerm_logic_app_trigger_custom` and `azurerm_logic_app_workflow` so I've submitted #261 for these

**Comment by paultyng** [comment]
Completion data (including providers, attributes, blocks, etc) in the [hashicorp/terraform-ls](https://github.com/hashicorp/terraform-ls) is now provided by the provider itself, and its the same schema and provider lists Terraform itself uses, so should no longer have these types of issues.
