### ISSUE TITLE
AWS provider resources not recognized with CodeLense in NewVersion

### ISSUE THREAD

**Issue by theSchueler** [hashicorp/vscode-terraform#264]
Hey, 

is there a way for me to enable the AWS provider schema for the experimental version?

Thank you so much for this plugin, it has helped a lot.

Best regards,

**Comment by paultyng** [comment]
Completion data (including providers, attributes, blocks, etc) in the [hashicorp/terraform-ls](https://github.com/hashicorp/terraform-ls) is now provided by the provider itself, and its the same schema and provider lists Terraform itself uses, so should no longer have these types of issues.
