### ISSUE TITLE
There is no variable named "count". Terraform Schema

### ISSUE THREAD

**Issue by rbrtl** [hashicorp/vscode-terraform#268]
Using v0.0.9 of the Terraform Language Server in the plugin and all my uses of the `count` object are highlighted as syntax errors with the above message.

**Comment by mixedCase** [comment]
That was reported in LSP's issue https://github.com/juliosueiras/terraform-lsp/issues/29 and was band-aided in https://github.com/juliosueiras/terraform-lsp/commit/f0e2305f9c34bca907b74e418dadc0e63f1a304d but no release has happened since September. Both the LSP and this extension seem semi-abandoned.

**Comment by djsly** [comment]
indeed, I'm kinda sad... note that juliosueiras provided an update, he's working on release v0.0.10 with many fixes. I'm still having some hope

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.
