### ISSUE TITLE
"Install providers" task always opens at VSCode (re)start

### ISSUE THREAD

**Issue by jlucktay** [hashicorp/vscode-terraform#276]
Every time I (re)open my VSCode windows, regardless of whether or not there is any Terraform code in the workspace/folder being opened, there will be an extra terminal opened for the "Install providers" task.

This extra terminal won't have any extra activity or commands or text in it, just a regular terminal as though I had opened a normal one, except it is named `Terraform: Install providers` as seen below.

In this screenshot, I have just done the `Developer: Reload Window` task to restart VSCode, and the extra terminal was opened immediately:

![image](https://user-images.githubusercontent.com/460028/74012865-23e56100-4983-11ea-8f0d-6e7219b76888.png)

It happens on all folders and workspaces.
This particular workspace has a `godoc` task that runs automatically, and the `godoc` task terminal numbered 3 is expected but the Terraform terminal numbered 2 is not.

**Comment by paultyng** [comment]
Completion data (including providers, attributes, blocks, etc) in the [hashicorp/terraform-ls](https://github.com/hashicorp/terraform-ls) is now provided by the provider itself, and its the same schema and provider lists Terraform itself uses, so should no longer have these types of issues.

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.
