### ISSUE TITLE
Adding new azuread provider

### ISSUE THREAD

**Issue by SimonTheLeg** [hashicorp/vscode-terraform#277]
hey guys,

I wanted to add the new Azure Active Directory Provider (https://www.terraform.io/docs/providers/azuread/index.html) to the Plugin.  However I am having some trouble finding out how to do it.

From here https://github.com/mauve/vscode-terraform/blob/master/src/data/README.md I can see that the `terraform-docs-scrape` tool is being used, but the tool itself does not have any description.

Could you give me some pointers how to add a new provider?

**Comment by paultyng** [comment]
Completion data (including providers, attributes, blocks, etc) in the [hashicorp/terraform-ls](https://github.com/hashicorp/terraform-ls) is now provided by the provider itself, and its the same schema and provider lists Terraform itself uses, so should no longer have these types of issues.

**Comment by SimonTheLeg** [comment]
just so I understand your comment: You mean **in the future** this will not be required anymore with the planned changes in terraform-ls and the planned changes to this plugin, right? (https://www.hashicorp.com/blog/supporting-the-hashicorp-terraform-extension-for-visual-studio-code/)

But at the moment this issue still persists? Just making sure I don't have it configured wrongly on my machine, while in reality it already should already be working :D

**Comment by paultyng** [comment]
Yeah, sorry, I realized I was maybe closing these a bit early, and I should close them at launch. You can try using the new LS with the existing plugin, but we haven't tried it out that much yet as we are just focusing on shipping the v2.0 version. Probably easiest to just subscribe to #316 for a notification when its ready to test.
