### ISSUE TITLE
Include a way to directly control which providers are loaded in LSP with ability to add your own

### ISSUE THREAD

**Issue by thefluffysysop** [hashicorp/vscode-terraform#280]
Related to #277, and also mentioned [here](https://github.com/juliosueiras/terraform-lsp/issues/28). 

The extension comes pre-packaged with a collection of providers used by the LSP. 
We need an easy way to add/remove providers and to be able to control their loading from the config. 

I am running into this on Windows, where the list of providers loaded from the providers.tf file ( .vscode\extensions\mauve.terraform-1.4.0\lspbin\providers.tf ), is quite limited. 

I was seeking to add the VMware NSX-T and vSphere providers.

**Comment by paultyng** [comment]
Completion data (including providers, attributes, blocks, etc) in the [hashicorp/terraform-ls](https://github.com/hashicorp/terraform-ls) is now provided by the provider itself, and its the same schema and provider lists Terraform itself uses, so should no longer have these types of issues.
