### ISSUE TITLE
How to manually install terraform-lsp

### ISSUE THREAD

**Issue by RobCannon** [hashicorp/vscode-terraform#283]
Can you document the way to manually install terraform-lsp so the extension won't try to download it?

My scenario:
We are creating linux servers in an isolated environment that do not have access to the internet.  We are using the VSCode SSH Remote feature to connect to those servers and we are editing terraform project there.

We can preinstall terraform-lsp there and configure VSCode to find it.  I downloaded terraform-lsp and installed it to /usr/local/bin/.

I set this configuration:

    "terraform.languageServer": {
        "pathToBinary": "/usr/local/bin/terraform-lsp",
        "enabled": true,
        "args": []
    },

But, when I start a project, it still asks to download terraform-lsp

Would you like to install Terraform Language Server from juliosueiras/terraform-lsp? 
 This provides experimental Terraform 0.12 support

I cancel and eventually I get this error message:

Failed starting language server. Error: HttpError: request to https://api.github.com/repos/juliosueiras/terraform-lsp/releases failed, reason: connect ETIMEDOUT 199.19.250.205:80

Is there anything else in the configuration I should do?  Or maybe a place to put the terraform-lsp binary?  Note, since we are pre-building images for the SSH server, it needs to be somewhere that all users can access.

Finally, the Remote SSH extension has a way to download extensions from the computer running VSCode and then transfer the extension through the SSH session to install it there.  I don't know if this is supplied in a way that other extensions can use, but that would be a great solution for all of this.

**Comment by RealOrangeOne** [comment]
I too am getting this issue. I have the language server installed with my system package manager, so there's no need for the extension to install it. 

Maybe a flag to stop the extension controlling it altogether is the ideal implementation? `terraform.languageServer.useSystem: true` or alike?

**Comment by awilkins** [comment]
My workaround at present : check out the source tree for `terraform-lsp`, build it, and place a softlink to the binary in the extension folder. I'm doing this because I'm fixing bugs in it as and when I can (I have what I would guess is some fairly complex code with lots of constructed maps and local vars and the LSP crashing has been quite frequent.)

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.
