### ISSUE TITLE
Terraform - Unknown token:4:20 IDENT string [4,20]

### ISSUE THREAD

**Issue by lindaburns** [hashicorp/vscode-terraform#284]
I am having issues with my 'variables.tf' code. 
The type = string for variable "resource_group_name" gets this error message:  Unknown token:4:20 IDENT string [4,20]

I cannot figure out how to fix this....

variable "resource_group_name" {
    **type        =  string**
    description = "The name of the resource group"
  }

![terraformError](https://user-images.githubusercontent.com/45107355/75618614-ee293780-5b3e-11ea-818c-eacf16b82575.jpg)

Can someone please help.  
Thanks

**Comment by tenwit** [comment]
That happens whenever the 0.11 parsing logic (terraform.indexing) encounters terraform 0.12 code. Turn off terraform indexing in your settings.json and all those IDENT errors will go away.

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.
