### ISSUE TITLE
Support "experiments" Terraform setting

### ISSUE THREAD

**Issue by evoio** [hashicorp/vscode-terraform#288]
Terraform 0.12.20 introduced experimental features that are enabled using the "[experiments](https://www.terraform.io/docs/configuration/terraform.html#experimental-language-features)" configuration option. Currently this is highlighted as an invalid argument:

![image](https://user-images.githubusercontent.com/9166525/76203526-b3826780-61ee-11ea-8a82-e6622f37a81b.png)

Please can this be added so that it does not throw an error.

**Comment by paultyng** [comment]
Completion data (including providers, attributes, blocks, etc) in the [hashicorp/terraform-ls](https://github.com/hashicorp/terraform-ls) is now provided by the provider itself, and its the same schema and provider lists Terraform itself uses, so should no longer have these types of issues.
