### ISSUE TITLE
ETXTBSY: text file is busy, open '/home/<user-name>/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-lsp'

### ISSUE THREAD

**Issue by beinnova** [hashicorp/vscode-terraform#289]
Hi,
I'm trying to use the extension but get the error above. It appears every time I run the `Install\Update language server.

My OS is Unbuntu 18.04

Thanks in advance

**Comment by sysreport** [comment]
same error here.
OS is LinuxMint 19.1 and VSC 1.43.0

**Comment by gflex** [comment]
also same on CentOS 7.6 with vscode 1.43.0

**Comment by tenwit** [comment]
If you disable the server before updating, you should avoid this. If necessary, you can kill the language server manually (`lsof` the file, then kill the process that has it open).

**Comment by mwilson-cb** [comment]
@tenwit that worked for me. Thank you!

**Comment by norhe** [comment]
I encountered this issue as well.  
Ubuntu 19.10
vscode 1.45.1

**Comment by radeksimko** [comment]
I wasn't able to reproduce this on any recent v2 version. Please do let us know if you continue experiencing this problem and in which version of the extension - we can take a look into it.

Thank you.
