### ISSUE TITLE
TF explorer is blank, no outlines, symbols showing in search, peek, ...?

### ISSUE THREAD

**Issue by WascawyWabbit** [hashicorp/vscode-terraform#295]
terraform version 0.12.24
vscode: latest
plugin: 1.4
lsp: 0.10

demo file:

```hcl
resource "azurerm_resource_group" "demo" {
    name        = var.demo
    location    = "uksouth"
}

variable "demo" {
    type = string
    default = "demo"
}
```
LSP support enabled.  Indexing disabled.

tf init

Working:
- (partial) Keywords like variable and resource are highlighted, but not things like "name", "location", "var", "string", "os_profile" in VM definitions, ...
- CTRL-SPACE suggestions are working

Not working:
- symbol browse (file, workspace)
- definition peek
- terraform explorer

(the above tested with a complex multi-file workspace with the same result)

Is this expected behaviour for TF 0.12.x?

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.
