### ISSUE TITLE
Failed to download common providers: Error: ETXTBSY

### ISSUE THREAD

**Issue by robatron** [hashicorp/vscode-terraform#297]
I'm getting this error after installing this extension: 

```
Failed to download common providers: Error: ETXTBSY: text file is busy, copyfile '/home/robmc/.vscode-server/extensions/mauve.terraform-1.4.0/lspbin/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.42.0_x4' -> '/home/robmc/.vscode-server/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.42.0_x4'
```

I've tried re-installing the extension, and re-loading vscode. Any tips?

**Comment by paultyng** [comment]
Completion data (including providers, attributes, blocks, etc) in the [hashicorp/terraform-ls](https://github.com/hashicorp/terraform-ls) is now provided by the provider itself, and its the same schema and provider lists Terraform itself uses, so should no longer have these types of issues.
