### ISSUE TITLE
Provider consul does not exist

### ISSUE THREAD

**Issue by unacceptable** [hashicorp/vscode-terraform#304]
# Error message:

```
{
	"resource": "REDACTED/azure-hd-insights-spark/provider.tf",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Provider consul does not exist",
	"source": "Terraform Schema",
	"startLineNumber": 1,
	"startColumn": 10,
	"endLineNumber": 1,
	"endColumn": 18
}
```
![Screen Shot 2020-04-13 at 10 13 01 AM](https://user-images.githubusercontent.com/18185488/79132149-68b8ba00-7d6f-11ea-9de3-a74a9c3769ca.png)

# Provider file:

```
provider "consul" {
    address = "consul.vault:8500"
}
```

**Comment by paultyng** [comment]
Completion data in the [hashicorp/terraform-ls](https://github.com/hashicorp/terraform-ls) is now provided by the provider itself, and its the same schema Terraform itself uses, so should no longer have these types of issues.
