### ISSUE TITLE
FileMD5 is reporting that it cannot find a file, but I'm pretty sure it is

### ISSUE THREAD

**Issue by alexanderbanks** [hashicorp/vscode-terraform#305]
Error: VSCode highlights `filemd5("lambda.zip")` and gives me a `Call to function "filemd5" failed: no file exists at lambda.zip.`
Terraform version: Terraform v0.12.24
VSCode-Terraform version: 1.4.0

```
resource "aws_s3_bucket_object" "source" {
  bucket = aws_s3_bucket.lambda_source_bucket.bucket
  key = "lambda.zip"
  source = "lambda.zip"

  etag = filemd5("lambda.zip")
}
```

Terraform is both uploading the zip file and correctly setting the MD5 hash in the etag, which makes me think this is an issue with the VSCode extension? I can provide more info if you tell me what to check.

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.
