### ISSUE TITLE
Please added support for terraform cloud provider

### ISSUE THREAD

**Issue by severity1** [hashicorp/vscode-terraform#308]
the terraform cloud provider is an official provider, it would be nice to have support for this.

```
data "tfe_workspace" "sourceable_workspace" {
  for_each = {
    for k in local.trigger_workspaces : "${k.name}.${k.trigger_workspace}" => k
  }

  name         = each.value.trigger_workspace
  organization = each.value.organization
}
```

at the moment this extension complains that these datasources and resources under the terraform provider does not exist.

**Comment by severity1** [comment]
disabling language Server and reloading vscode  fixed the issue however I'm not sure if that is ideal.

```
"terraform.languageServer": {
        "enabled": false,
        "args": []
    },
```

**Comment by paultyng** [comment]
Completion data in the [hashicorp/terraform-ls](https://github.com/hashicorp/terraform-ls) is now provided by the provider itself, and its the same schema Terraform itself uses, so should no longer have these types of issues.
