### ISSUE TITLE
Mitchell Hashimoto just announced they're working on an official Terraform vs-code extension

### ISSUE THREAD

**Issue by NeckBeardPrince** [hashicorp/vscode-terraform#310]
https://twitter.com/mitchellh/status/1253029782649892864

Edit: Want to make it clear that this is nothing against the original author of this extension. They worked very hard and we should be grateful for the work they've done.

**Comment by mitchellh** [comment]
I apologize but there is a misunderstanding! I perhaps could've stated this better, but this is misreading my tweet. By the "it" on "we're working on it" I meant we're working on a strategy around Terraform + VSCode and we'll publicly discuss it soon. Our intent is to support VSCode with Terraform but we haven't finalized what path that takes. We're also talking with @mauve about it. 😄

**Comment by NeckBeardPrince** [comment]
@mitchellh Understood. Thanks for clearing that up. I was just so damned excited I jumped the gun.

**Comment by paultyng** [comment]
We have finalized that path a bit more now 😉 #316
