### ISSUE TITLE
ERROR: dynamic block in a 'aws_iam_policy_document' data resource's block is not expected

### ISSUE THREAD

**Issue by eduardohki** [hashicorp/vscode-terraform#311]
Hello,

I have a few modules that use a dynamic block inside a `aws_iam_policy_document` data resource, which is returning the error `Blocks of type "dynamic" are not expected here`.

I validated that this error is issued when the Terraform Language Server is enabled.

Module Version: `1.4.0`
Language Server Version: `v0.0.11-beta1`

An example:
```tf
data "aws_iam_policy_document" "lambda_exec_role_policy" {
  statement {
    sid    = "LambdaExecRolePolicy"
    effect = "Allow"
    principals {
      identifiers = [
        "lambda.amazonaws.com",
      ]
      type = "Service"
    }
    dynamic "principals" { # <-- here
      for_each = (length(var.cross_account_ids) > 0) ? [1] : []
      content {
        identifiers = concat(
          [format("arn:aws:iam::%s:root", data.aws_caller_identity.current.account_id)],
          formatlist("arn:aws:iam::%s:root", var.cross_account_ids)
        )
        type = "AWS"
      }
    }
    actions = [
      "sts:AssumeRole",
    ]
  }
}
```

**Comment by paultyng** [comment]
A new language server is coming for our next release, see #316 or the new [terraform-ls](https://github.com/hashicorp/terraform-ls) repo. I believe this issue applies to the previous language server, so going to close, but feel free to chime in here if that is not the case.
