### ISSUE TITLE
Can't get majority of features to work

### ISSUE THREAD

**Issue by cyrus-mc** [hashicorp/vscode-terraform#313]
Running latest version of vscode 1.44.2 and latest extension. I have enabled and installed latest LSP.

The majority of the features don't work. 

Auto-completion doesn't work. See attached screenshot:

<img width="697" alt="Screen Shot 2020-05-05 at 9 29 54 PM" src="https://user-images.githubusercontent.com/9330844/81139002-f3c54400-8f18-11ea-9635-e6be6e094aeb.png">

- Show variable on hover

- CodeLens support (no references appear above variable definitions)

- Document Link support (the resource doesn't appear as a link to follow)

- Outline View support (the active editor cannot provide outline information)

My settings.json

> {
    "workbench.colorTheme": "Visual Studio Light",
    "window.zoomLevel": 0,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "terraform.indexing": {
        "enabled": false,
        "liveIndexing": true,
        "delay": 500,
        "exclude": [
            ".terraform/**/*",
            "**/.terraform/**/*"
        ]
    },
    "terraform.languageServer": {
        "enabled": true,
        "args": []
    },
    "[terraform]": {
    },
    "terraform.codelens.enabled": true,
    "terraform.telemetry.enabled": true,
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "task.problemMatchers.neverPrompt": {
      "shell": true
    },
    "git.autofetch": true,
    "diffEditor.ignoreTrimWhitespace": false,
    "go.useLanguageServer": true,
    "java.semanticHighlighting.enabled": false
}

**Comment by paultyng** [comment]
A new version is coming that should address 0.12 support among other things, see #316
