### ISSUE TITLE
So Long, and Thanks for All the Fish!

### ISSUE THREAD

**Issue by mauve** [hashicorp/vscode-terraform#314]
HashiCorp and I have just - after a few months of discussions - started the process of handing over maintainership of `vscode-terraform` to HashiCorp. This is something I am really happy about and it lifts a ton of weight off my shoulders. 

A little over a year ago my work situation changed so that I haven't been able to commit any time to `vscode-terraform` at all. This is something which I have felt very bad about as the extension has a lot of users (a little under 100k MAU 💯💯) who I did not want to let down. 

I started the extension a few years ago to scratch some personal itches: 

   - I needed to learn Terraform 
   - I really wanted to learn how to do VSCode extensions 
   - and I wanted to learn TypeScript 

I had no idea that somebody else wanted this extension :) so I was very happily surprised when people started downloading it. For a while I think the extension was even in top-10 in the category of extensions for programming-languages🥇 😊  

Thanks for using my extension! I have been very happy to have you all as users ❤ and contributors. 

🎉🎉

Kind regards,

Mikael Olenfalk

(for reference: https://en.wikipedia.org/wiki/So_Long,_and_Thanks_for_All_the_Fish)

**Comment by NeckBeardPrince** [comment]
Thank you very much for all your hard work!

**Comment by paultyng** [comment]
We just posted an update on this transfer to our blog: https://www.hashicorp.com/blog/supporting-the-hashicorp-terraform-extension-for-visual-studio-code

**Comment by jeohist** [comment]
Thank you so much for all your hard work. You saved a lot of developers a lot of time and headaches.

**Comment by hikerspath** [comment]
Even though nearly all my tf0.12 code is red, there is no plugin that stands up to this one.  Thanks for all the work you did.

**Comment by abhinavkorpal** [comment]
@mauve Thank you very much for all your hard work!

**Comment by charlex** [comment]
Does any one have any ideas on what to do with the bounty ($250) from the 0.12 support ticket? Perhaps if the rules allow, the bounty could be repurposed as a donation to @mauve for his work?

https://www.bountysource.com/issues/70767330-feat-terraform-0-12-support-was-hcl2-support

**Comment by paultyng** [comment]
I think @emmm-dee originally created the bounty? https://github.com/hashicorp/vscode-terraform/issues/157#issuecomment-525521811

I'll leave this issue open for a bit for you all to figure that out but definitely should not go to (us) HashiCorp, I agree it should be distributed to previous community maintainers if anything.

**Comment by mercuriete** [comment]
Thanks for all the work!
You always will have this community around such a good plugin!
❤️❤️

**Comment by emmm-dee** [comment]
> I think @emmm-dee originally created the bounty? [#157 (comment)](https://github.com/hashicorp/vscode-terraform/issues/157#issuecomment-525521811)
> 
> I'll leave this issue open for a bit for you all to figure that out but definitely should not go to (us) HashiCorp, I agree it should be distributed to previous community maintainers if not just dropped.

Indeed I created it, however the bounty gets "claimed" by a solver. If an applicable person tries to claim the reward it can be given but I can't just choose someone to give it to, it's a "claim" system. 

Someone should definitely get it though since right now the money is just sitting in limbo not helping anyone.

**Comment by juliosueiras** [comment]
I don't need it, so it should goto @mauve

**Comment by nbetm** [comment]
@mauve  Thank you so much for all your hard work! This has been one of my top-3 vscode extensions!

**Comment by chenrui333** [comment]
@mauve thanks for all the efforts to the community!!

**Comment by clebio** [comment]
@paultyng , any word on when this will be available to VS Code? I'm on VSCode version 1.45.1 (latest), but the Terraform extension doesn't see any updates past 1.4.0.

**Comment by ldormoy** [comment]
@mauve thanks for the good work!
