### ISSUE TITLE
HTTP 403 when trying to install Language Server

### ISSUE THREAD

**Issue by rba1-source** [hashicorp/vscode-terraform#315]
I'm behind a corporate firewall and whilst I can download and install the Terraform extension for VSCode, when I try to use the "Install/Update Language server" command from the Command Palette, it shows me a list of versions in the dropdown list but gives me a 403 response when I choose one:

`Downloading Terraform language server failed with Error: Unexpected HTTP response: 403`

Can you let me know what ports/protocols/urls should be open through a firewall to allow this feature?

**Comment by paultyng** [comment]
@rba1-source hopefully this will be resolved soon by #316, we recently took ownership and haven't updated this. The domain for downloading the LS will be `releases.hashicorp.com`.

**Comment by nikolay** [comment]
@paultyng I know you have big plans, but can't you release `v1.14` before `v2` along with the language server update?
