### ISSUE TITLE
New version of the extension coming soon!

### ISSUE THREAD

**Issue by paultyng** [hashicorp/vscode-terraform#316]
See our [blog post](https://www.hashicorp.com/blog/supporting-the-hashicorp-terraform-extension-for-visual-studio-code) about taking over this extension from Mikael (see his [goodbye note here as well](https://github.com/hashicorp/vscode-terraform/issues/314). Current outstanding tasks:

* [x] Transfer [VS Code marketplace entry](https://marketplace.visualstudio.com/items?itemName=mauve.terraform) to HashiCorp (discussing this with VS Code Marketplace support currently)
* [ ] Push 2.0 source version to this repo (currently in an internal repo for testing, but will be fully open source going forward)
* [ ] Release a 2.0 version which defaults to using our [language server](https://github.com/hashicorp/terraform-ls) but can be set to use others, like [juliosueiras/terraform-lsp](https://github.com/juliosueiras/terraform-lsp).

The code and feature support has changed quite a bit in the 2.0 version, so many issues are no longer relevant and will be closed. Some issues regarding things like language features, autocomplete, etc, are Language Server dependent and they will be transferred to that repository.

**Comment by smiller171** [comment]
Is it possible to run the new language server with this extension at all right now?

**Comment by paultyng** [comment]
I think its possible to use the new language server with the existing version, the are implemented to the same protocol, but I'm not sure what the UX would be like and we haven't really tested it.

**Comment by avoidik** [comment]
it worked for me with the latest vscode mauve.terraform plugin, [terraform-ls](https://releases.hashicorp.com/terraform-ls/0.2.1/) renamed to **terraform-lsp** and replaced  juliosueiras **terraform-lsp**, this is my configuration

```json
    "terraform.indexing": {
        "enabled": false,
        "liveIndexing": false
    },
    "terraform.languageServer": {
        "enabled": true,
        "args": ["serve"]
    },
```

**Comment by KrishnaPravin** [comment]
@paultyng is there an ETA planned for the v2.0? Eagerly awaiting😀

**Comment by garry-harthill-cko** [comment]
@KrishnaPravin indeed. i think right now i'd take it in any state it's currently in 😄

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.

**Comment by smiller171** [comment]
@paultyng `v2.0.0-rc.1` doesn't work at all for me. The language server crashes insisting I haven't initialized even though I have

**Comment by paultyng** [comment]
@smiller171 do you mind opening a new issue with the logs of the `terraform-ls` output window?

**Comment by smiller171** [comment]
@paultyng already done https://github.com/hashicorp/vscode-terraform/issues/329
