### ISSUE TITLE
Getting error when i try to get the output of a resource in terraform v0.12.25

### ISSUE THREAD

**Issue by tvkrishnaAWS** [hashicorp/vscode-terraform#322]
Hi All,

i am using the terraform v0.12.25 version, when i try to get the output of a resource, it thrown error.
can anyone help me to fix this?
FYI...
Error: Unknown token: 12:11 IDENT aws_eip.my_eip
![image](https://user-images.githubusercontent.com/55243913/82728177-93057c00-9d0c-11ea-8f78-36c56974da65.png)

Thanks

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.
