### ISSUE TITLE
'Blocks of type "dynamic" are not expected here' on nested block

### ISSUE THREAD

**Issue by pgreda** [hashicorp/vscode-terraform#324]
Hi,

I'm using:
```
Terraform v0.12.25
Code: 1.45.1
Language server: v0.0.11-beta-1
```

Following code works ok with terraform validate and terraform apply:

```
resource "aws_ec2_fleet" "fr-k8s-masters" {
  terminate_instances                 = true
  terminate_instances_with_expiration = true

  launch_template_config {
    launch_template_specification {
      launch_template_id = aws_launch_template.master_worker.id
      version            = aws_launch_template.master_worker.latest_version
    }
    dynamic "override" {
      for_each = aws_subnet.management
      content {
        max_price = var.master_spot_max_price
        subnet_id = override.value.id
      }
    }
  }

  target_capacity_specification {
    default_target_capacity_type = "spot"
    total_target_capacity        = var.master_total_instance_number
    on_demand_target_capacity    = var.master_total_instance_number - var.master_spot_instances_number
    spot_target_capacity = var.master_spot_instances_number
  }

  spot_options {
    instance_pools_to_use_count = length(aws_subnet.management)
    allocation_strategy         = "lowestPrice"
  }
}
```

The dynamic override section genetrates following error in VS Code:
Blocks of type "dynamic" are not expected here.

Best regards,
PG
![2020-05-27 15_40_52-ec2 tf - lab-k8s  WSL_ Ubuntu-18 04  - Visual Studio Code](https://user-images.githubusercontent.com/51679278/83027665-a8dab000-a030-11ea-991b-0ed1c2b62c11.png)

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.
