### ISSUE TITLE
Color coding: "Unknown token" often in first line of a node

### ISSUE THREAD

**Issue by gsscoder** [hashicorp/vscode-terraform#345]
It's more easy if I show you a screenshot:
![tf-color-coding](https://user-images.githubusercontent.com/1194228/84016952-51b4d380-a97e-11ea-8a90-954e542452c1.png)

It happens also in variables declarations.

Thanks for the extension.

Regards,
Giacomo S. S.

**Comment by paultyng** [comment]
@gsscoder is this in the new RC we released last week? HashiCorp recently took over this repository (#316), and we will be releasing a new version soon. This looks like you are using an older version with Terraform 0.12 or greater? If so, the RC (and forthcoming Marketplace release) of 2.0.0 should fix you.

**Comment by gsscoder** [comment]
@jpogran thanks for replying, at the moment we decided to postpone the use of Terraform.
