### ISSUE TITLE
Intellisense and tab completion of variables no longer working

### ISSUE THREAD

**Issue by Liquidmantis** [hashicorp/vscode-terraform#353]
I just installed both RC1 and RC2, and compared to the prior version (the current marketplace release), variable are no longer populating in the Intellisense pop-up and won't tab complete.

I'm brand new to Terraform, but while building tf files before 2.0 I could type "var." and would start to get fuzzy-matching recommendations for autocompletion, based on my variables file.  Is this related to the new language server and the pending commit that parses the tfvars file?  I don't really grok all the language support magic so I apologize if that's a stupid question.

**Comment by radeksimko** [comment]
👋  @Liquidmantis 
Thank you for trying out the new release candidates of the extension and the language server.

Completion of named references (such as `var.xyz`, `output.xyz`, `module.xyz` etc.) is going to be handled by the language server and is tracked under https://github.com/hashicorp/terraform-ls/issues/38

I'm going to close this one, but I'd encourage you to subscribe to that issue. The extension should prompt for language server upgrades automatically as we release new versions and once the server supports this functionality, it will become available in your VSCode.
