### ISSUE TITLE
Language server install hangs

### ISSUE THREAD

**Issue by ScottGuymer** [hashicorp/vscode-terraform#361]
When I take the options to activate the language server it just seems to hang and keeps doing the same in every subsequent session.

Tried removing/reinstalling the plugin and had the same issue

![image](https://user-images.githubusercontent.com/956825/84291779-d867dd00-ab45-11ea-93ac-b3b85bcbec10.png)

I remember trying this early in its development and had the same issue, maybe this is some hangover problem from trying to adopt earlier but the uninstall didn't seem to fix it.

**Comment by ScottGuymer** [comment]
AFAIK this was the extension from the marketplace..

**Comment by ScottGuymer** [comment]
reinstalled today and it _seems_ like its all installed correctly now..

**Comment by paultyng** [comment]
@ScottGuymer ok, I'll close this, but please feel free to open a new issue if you continue getting weird behavior.
