### ISSUE TITLE
Bundle javascript files

### ISSUE THREAD

**Issue by aeschright** [hashicorp/vscode-terraform#364]
As recommended by vsce:

> This extension consists of 658 files, out of which 226 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore

**Comment by aeschright** [comment]
Unfortunately we're going to have to work around this issue with the extension tests: https://github.com/microsoft/vscode/issues/85779

**Comment by jpogran** [comment]
Confirmed, we now minify the extension on publish.
