### ISSUE TITLE
Language Server doesn't initialize when no providers exist

### ISSUE THREAD

**Issue by frugecn** [hashicorp/vscode-terraform#367]
When creating a module where no providers are needed, language server does not initialize.

Use-Case
I create a template that is designed for tags that is universal to any cloud vendor.  It is designed to be used as a module with pre-defined tags that the enterprise requires and then allows for any additional tags.  Implementation is to use as a module and in the resource tags = module.tagging.tags.

Because this use-case doesn't require any providers, it is only using locals, language server fails to initialize.

Desired need:
Because format is now based on the language server, formatting is not provided because the language server is not initialized.

**Comment by dmakeienko** [comment]
same problem, full log below.
Also, to clarify my project structure of **project.tfm** vscode workspace:
`.
├── modules
│   ├── apigateway
│   ├── dynamodb
│   ├── iam
│   ├── lambda
│   ├── s3
│   ├── sqs
│   └── vpc
├── big-module
│   └── small-module
│           └── provider.tf
`

`Launching language server: /home/makeienko/.vscode/extensions/hashicorp.terraform-2.0.1/lsp/terraform-ls serve
2020/06/11 08:46:50 service.go:63: Preparing new session ...
2020/06/11 08:46:50 langserver.go:79: Starting server (pid 27095) ...
2020/06/11 08:46:50 server.go:469: Received 1 new requests
2020/06/11 08:46:50 server.go:165: Processing 1 requests
2020/06/11 08:46:50 server.go:223: Checking request for "initialize": {"processId":26625,"rootPath":"/home/makeienko/projects/project.tfm","rootUri":"file:///home/makeienko/projects/project.tfm","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true}}},"trace":"off","workspaceFolders":[{"uri":"file:///home/makeienko/projects/project.tfm","name":"project.tfm"}]}
2020/06/11 08:46:50 rpc_logger.go:29: Incoming request for "initialize" (ID 0): {"processId":26625,"rootPath":"/home/makeienko/projects/project.tfm","rootUri":"file:///home/makeienko/projects/project.tfm","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true}}},"trace":"off","workspaceFolders":[{"uri":"file:///home/makeienko/projects/project.tfm","name":"project.tfm"}]}
2020/06/11 08:46:50 exec.go:176: Starting /home/makeienko/.tfenv/bin/terraform ["terraform" "version"] in "/tmp"...
2020/06/11 08:46:50 exec.go:142: Waiting for command to finish ...
2020/06/11 08:46:50 exec.go:168: terraform run (/home/makeienko/.tfenv/bin/terraform ["terraform" "version"], in "/tmp", pid 27104) finished with exit code 0
2020/06/11 08:46:50 initialize.go:90: Found compatible Terraform version (0.12.26) at /home/makeienko/.tfenv/bin/terraform
2020/06/11 08:46:50 schema_storage.go:334: Adding workspace for watching: "/home/makeienko/projects/project.tfm"
2020/06/11 08:46:50 watcher.go:88: Adding "/home/makeienko/projects/project.tfm/.terraform/plugins/linux_amd64/lock.json" for watching...
2020/06/11 08:46:50 schema_storage.go:124: Acquiring semaphore before retrieving schema for "/home/makeienko/projects/project.tfm" ...
2020/06/11 08:46:50 schema_storage.go:133: Retrieving schemas for "/home/makeienko/projects/project.tfm" ...
2020/06/11 08:46:50 rpc_logger.go:45: Error for "initialize" (ID 0): [-32098] Workspace not initialized. Please run `terraform init` in /home/makeienko/projects/project.tfm
2020/06/11 08:46:50 exec.go:176: Starting /home/makeienko/.tfenv/bin/terraform ["terraform" "providers" "schema" "-json"] in "/home/makeienko/projects/project.tfm"...
2020/06/11 08:46:50 server.go:204: Completed 1 requests [97.311869ms elapsed]
[Error - 8:46:50 AM] Server initialization failed.
  Message: Workspace not initialized. Please run `terraform init` in /home/makeienko/projects/project.tfm
  Code: -32098 
2020/06/11 08:46:50 exec.go:142: Waiting for command to finish ...
2020/06/11 08:46:50 server.go:469: Received 1 new requests
2020/06/11 08:46:50 server.go:165: Processing 1 requests
2020/06/11 08:46:50 server.go:223: Checking request for "shutdown": 
2020/06/11 08:46:50 rpc_logger.go:29: Incoming request for "shutdown" (ID 1): 
2020/06/11 08:46:50 rpc_logger.go:50: Response to "shutdown" (ID 1): null
2020/06/11 08:46:50 server.go:204: Completed 1 requests [227.002µs elapsed]
2020/06/11 08:46:50 server.go:469: Received 1 new requests
2020/06/11 08:46:50 server.go:165: Processing 1 requests
2020/06/11 08:46:50 server.go:223: Checking request for "exit": 
2020/06/11 08:46:50 rpc_logger.go:29: Incoming notification for "exit": 
2020/06/11 08:46:50 schema_storage.go:116: error obtaining schemas: Unable to retrieve schemas: failed to get schemas: Execution of ["terraform" "providers" "schema" "-json"] canceled.
signal: killed
`

**Comment by anvarich** [comment]
yep, can't work with modules too because extension trying to find scheme which not exist without init. :(

**Comment by awilkins** [comment]
It also doesn't initialize if your source folder isn't a very simple layout

I know the new and fashionale pattern is to use workspaces, but I run with multiple configs in a nested folder tree.

If there's no .terraform folder in the root it doesn't init.

The "bleeding edge" [terraform-lsp](https://github.com/juliosueiras/terraform-lsp) that terraform-ls replaced still works, by the way, I've configured my local fork of it as my LSP because of this, even if it's a bit crashy on complex variables.

```
/
 env/
       one/
              main.tf
 modules/
              mod_1/
```

**Comment by frugecn** [comment]
`Launching language server: c:\Users\<user>\.vscode\extensions\hashicorp.terraform-2.0.1/lsp/terraform-ls serve
2020/06/11 09:44:28 service.go:63: Preparing new session ...
2020/06/11 09:44:28 langserver.go:79: Starting server (pid 14816) ...
2020/06/11 09:44:28 server.go:469: Received 1 new requests
2020/06/11 09:44:28 server.go:165: Processing 1 requests
2020/06/11 09:44:28 server.go:223: Checking request for "initialize": {"processId":22868,"rootPath":"c:\\Users\\<user>\\source\\GitRepos\\Tagging-Update\\Tagging","rootUri":"file:///c%3A/Users/<user>/source/GitRepos/Tagging-Update/Tagging","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true}}},"trace":"off","workspaceFolders":[{"uri":"file:///c%3A/Users/<user>/source/GitRepos/Tagging-Update/Tagging","name":"Tagging"}]}
2020/06/11 09:44:28 rpc_logger.go:29: Incoming request for "initialize" (ID 0): {"processId":22868,"rootPath":"c:\\Users\\<user>\\source\\GitRepos\\Tagging-Update\\Tagging","rootUri":"file:///c%3A/Users/<user>/source/GitRepos/Tagging-Update/Tagging","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true}}},"trace":"off","workspaceFolders":[{"uri":"file:///c%3A/Users/<user>/source/GitRepos/Tagging-Update/Tagging","name":"Tagging"}]}
2020/06/11 09:44:28 exec.go:176: Starting C:\Program Files\Terraform\terraform.exe ["terraform" "version"] in "C:\\Users\\<user>\\AppData\\Local\\Temp"...
2020/06/11 09:44:28 exec.go:142: Waiting for command to finish ...
2020/06/11 09:44:28 exec.go:168: terraform run (C:\Program Files\Terraform\terraform.exe ["terraform" "version"], in "C:\\Users\\<user>\\AppData\\Local\\Temp", pid 24228) finished with exit code 0
2020/06/11 09:44:28 initialize.go:90: Found compatible Terraform version (0.12.26) at C:\Program Files\Terraform\terraform.exe
2020/06/11 09:44:28 schema_storage.go:124: Acquiring semaphore before retrieving schema for "c:\\Users\\<user>\\source\\GitRepos\\Tagging-Update\\Tagging" ...
2020/06/11 09:44:28 schema_storage.go:133: Retrieving schemas for "c:\\Users\\<user>\\source\\GitRepos\\Tagging-Update\\Tagging" ...
2020/06/11 09:44:28 schema_storage.go:334: Adding workspace for watching: "c:\\Users\\<user>\\source\\GitRepos\\Tagging-Update\\Tagging"
2020/06/11 09:44:28 exec.go:176: Starting C:\Program Files\Terraform\terraform.exe ["terraform" "providers" "schema" "-json"] in "c:\\Users\\<user>\\source\\GitRepos\\Tagging-Update\\Tagging"...
2020/06/11 09:44:28 watcher.go:88: Adding "c:\\Users\\<user>\\source\\GitRepos\\Tagging-Update\\Tagging\\.terraform\\plugins\\windows_amd64\\lock.json" for watching...
2020/06/11 09:44:28 rpc_logger.go:45: Error for "initialize" (ID 0): [-32098] Workspace not initialized. Please run `terraform init` in c:\Users\<user>
<img width="409" alt="Terraform-extension-error" src="https://user-images.githubusercontent.com/52329271/84408200-16f2ab80-abc9-11ea-8dee-b57503b4fd84.png">
\source\GitRepos\Tagging-Update\Tagging
2020/06/11 09:44:28 server.go:204: Completed 1 requests [400.9273ms elapsed]
2020/06/11 09:44:28 exec.go:142: Waiting for command to finish ...
[Error - 9:44:29 AM] Server initialization failed.
  Message: Workspace not initialized. Please run `terraform init` in c:\Users\<user>\source\GitRepos\Tagging-Update\Tagging
  Code: -32098 
2020/06/11 09:44:29 exec.go:168: terraform run (C:\Program Files\Terraform\terraform.exe ["terraform" "providers" "schema" "-json"], in "c:\\Users\\<user>\\source\\GitRepos\\Tagging-Update\\Tagging", pid 2716) finished with exit code 0
2020/06/11 09:44:29 schema_storage.go:140: Schemas retrieved in 260.303ms
2020/06/11 09:44:29 server.go:469: Received 1 new requests
2020/06/11 09:44:29 server.go:165: Processing 1 requests
2020/06/11 09:44:29 server.go:223: Checking request for "shutdown": 
2020/06/11 09:44:29 rpc_logger.go:29: Incoming request for "shutdown" (ID 1): 
2020/06/11 09:44:29 rpc_logger.go:50: Response to "shutdown" (ID 1): null
2020/06/11 09:44:29 server.go:204: Completed 1 requests [0s elapsed]
2020/06/11 09:44:29 server.go:469: Received 1 new requests
2020/06/11 09:44:29 server.go:165: Processing 1 requests
2020/06/11 09:44:29 server.go:223: Checking request for "exit": 
2020/06/11 09:44:29 rpc_logger.go:29: Incoming notification for "exit": `

**Comment by konstantin-921** [comment]
Launching language server: /Users/developer/.vscode/extensions/hashicorp.terraform-2.0.1/lsp/terraform-ls serve
2020/06/16 13:31:32 service.go:63: Preparing new session ...
2020/06/16 13:31:32 langserver.go:79: Starting server (pid 11720) ...
2020/06/16 13:31:32 server.go:469: Received 1 new requests
2020/06/16 13:31:32 server.go:165: Processing 1 requests
2020/06/16 13:31:32 server.go:223: Checking request for "initialize": {"processId":11562,"rootPath":"/Users/developer/Documents/JS-training","rootUri":"file:///Users/developer/Documents/JS-training","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true}}},"trace":"off","workspaceFolders":[{"uri":"file:///Users/developer/Documents/JS-training","name":"JS-training"}]}
2020/06/16 13:31:32 rpc_logger.go:29: Incoming request for "initialize" (ID 0): {"processId":11562,"rootPath":"/Users/developer/Documents/JS-training","rootUri":"file:///Users/developer/Documents/JS-training","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true}}},"trace":"off","workspaceFolders":[{"uri":"file:///Users/developer/Documents/JS-training","name":"JS-training"}]}
2020/06/16 13:31:32 exec.go:176: Starting /usr/local/bin/terraform ["terraform" "version"] in "/var/folders/6y/bk7wthmd375_nl7ksm6v_6g80000gn/T/"...
2020/06/16 13:31:32 exec.go:142: Waiting for command to finish ...
2020/06/16 13:31:32 exec.go:168: terraform run (/usr/local/bin/terraform ["terraform" "version"], in "/var/folders/6y/bk7wthmd375_nl7ksm6v_6g80000gn/T/", pid 11721) finished with exit code 0
2020/06/16 13:31:32 initialize.go:90: Found compatible Terraform version (0.12.24) at /usr/local/bin/terraform
2020/06/16 13:31:32 schema_storage.go:334: Adding workspace for watching: "/Users/developer/Documents/JS-training"
2020/06/16 13:31:32 watcher.go:88: Adding "/Users/developer/Documents/JS-training/.terraform/plugins/darwin_amd64/lock.json" for watching...
2020/06/16 13:31:32 schema_storage.go:124: Acquiring semaphore before retrieving schema for "/Users/developer/Documents/JS-training" ...
2020/06/16 13:31:32 schema_storage.go:133: Retrieving schemas for "/Users/developer/Documents/JS-training" ...
2020/06/16 13:31:32 exec.go:176: Starting /usr/local/bin/terraform ["terraform" "providers" "schema" "-json"] in "/Users/developer/Documents/JS-training"...
2020/06/16 13:31:32 rpc_logger.go:45: Error for "initialize" (ID 0): [-32098] Workspace not initialized. Please run `terraform init` in /Users/developer/Documents/JS-training
2020/06/16 13:31:32 server.go:204: Completed 1 requests [77.970787ms elapsed]
2020/06/16 13:31:32 exec.go:142: Waiting for command to finish ...
2020/06/16 13:31:32 exec.go:168: terraform run (/usr/local/bin/terraform ["terraform" "providers" "schema" "-json"], in "/Users/developer/Documents/JS-training", pid 11723) finished with exit code 0
2020/06/16 13:31:32 schema_storage.go:140: Schemas retrieved in 93.093662ms
[Error - 1:31:32 PM] Server initialization failed.
  Message: Workspace not initialized. Please run `terraform init` in /Users/developer/Documents/JS-training
  Code: -32098 
2020/06/16 13:31:32 server.go:469: Received 1 new requests
2020/06/16 13:31:32 server.go:165: Processing 1 requests
2020/06/16 13:31:32 server.go:223: Checking request for "shutdown": 
2020/06/16 13:31:32 rpc_logger.go:29: Incoming request for "shutdown" (ID 1): 
2020/06/16 13:31:32 rpc_logger.go:50: Response to "shutdown" (ID 1): null
2020/06/16 13:31:32 server.go:204: Completed 1 requests [421.525µs elapsed]
2020/06/16 13:31:32 server.go:469: Received 1 new requests
2020/06/16 13:31:32 server.go:165: Processing 1 requests
2020/06/16 13:31:32 server.go:223: Checking request for "exit": 
2020/06/16 13:31:32 rpc_logger.go:29: Incoming notification for "exit":

**Comment by paultyng** [comment]
Going to merge this in with the main issue for tracking the different folder structure support: https://github.com/hashicorp/terraform-ls/issues/32#issuecomment-639543256
