### ISSUE TITLE
Shouldn't try to start the language server for non-terraform workspaces

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [hashicorp/vscode-terraform#368]
I use several vscode workspaces. Only one of them has any terraform files.

Having this extension tell me to run `terraform init` in every non-terraform workspace/repo is ... quite annoying.

Yes, it's possible to disable it per workspace, but ... that is not normal for language extensions in my experience with vscode (or any other editor/IDE). The C++ tooling doesn't pop up notification toasts that it failed to compile my non-existent C++ code every time I open a TypeScript or Go workspace, for example.

**Comment by FernandoMiguel** [comment]
> Hi folks, I'm sorry you're running into that problem. Is anyone seeing this when they don't have either a `terraform_modules` directory or .tf files in a subdirectory of the workspace?

yes, i'm seeing this on several folders have no .tf or terraform_modules in them.
i load a large workspace with many different repos

**Comment by ronjouch** [comment]
> Hi folks, I'm sorry you're running into that problem. Is anyone seeing this when they don't have either a `terraform_modules` directory or .tf files in a subdirectory of the workspace?

@aeschright yes, I confirm too I'm seeing this problem in a leaf project (of my multi-root workspace) that has zero `terraform_modules` directory or .tf files in a subdirectory. Confirmed by running `find -type f -name "*.tf"` and `find -type d -name "terraform_modules"`.

For me too, the extension complains about the first repo in the multi-root workspace. If I edit my `.code-workspace` file, comment the first entry, and restart VSCode, then the extension will complain about the new first entry.

Available for more debug info.

**Comment by rpstreef** [comment]
I use `terraform init` per environment I deploy to, I too have this issue.

**Comment by eexit** [comment]
Yes, how to disable this!! I tried to run the command to disable the Language Server but it does not work, it keeps logging a bunch of errors in my console.

Is there a way to use this extension just for the syntax highlighting?

Thanks,

**Comment by mgabeler-lee-6rs** [comment]
> Is there a way to use this extension just for the syntax highlighting?

And code formatting? Running `terraform format` doesn't require the language server, but with the new release, if the language server fails to initialize, code formatting doesn't work.

**Comment by paultyng** [comment]
I believe these issues are resolved in the latest versions of the VS Code extension / terraform-ls. Specifically issues with focus hijacking, initializing with no schema, formatting with no schema, etc.

**Comment by ronjouch** [comment]
> I believe these issues are resolved in the latest versions of the VS Code extension / terraform-ls. Specifically issues with focus hijacking, initializing with no schema, formatting with no schema, etc.

Confirmed on my local install. After restarting Code, being prompted to install the latest tf-ls, and re-restarting, no more error. Thanks!

> We are still working to improve different workspace organization handling, the best tracking issue for that is [hashicorp/terraform-ls#32](https://github.com/hashicorp/terraform-ls/issues/32)

👍👍👍
