### ISSUE TITLE
Output tab stealing focus when running

### ISSUE THREAD

**Issue by LogicNinja** [hashicorp/vscode-terraform#371]
When using the new extension with the language server, the output tab keeps stealing focus when any action is performed. Disabling the output tab and hiding the bottom panel does nothing, as soon as the language server prints and output it brings the tab back and in focus

**Comment by dimisjim** [comment]
you can disable it for now (but still keep the code fomatting with the colors and such) by doing this: https://github.com/hashicorp/vscode-terraform/issues/366#issuecomment-642517541 until this is fixed

**Comment by jonjaques** [comment]
I was able to fix this by setting `trace.server` to anything but "verbose" which I believe may be the default.

Also I had a few other junk settings in here from the various incarnations of the TF VSCode extension / other language servers.

This is all I have now.

```json
  "terraform.languageServer": {
    "trace.server": "off",
    "external": true,
    "args": ["serve"]
  },
```
