### ISSUE TITLE
Version pinning as suggested in Readme results in 404 error

### ISSUE THREAD

**Issue by joerx** [hashicorp/vscode-terraform#372]
Not sure this is the right place, please correct me if I'm wrong. Trying to pin to an older version of the plugin as linked in the Readme leads to VS Code failing with a 404 error.

Steps to reproduce:

- Try to pin to an older version of the extension
- VSCode will try to list older versions

Expected behaviour:

- Can select the desired version

Actual behaviour:

- Error message is shown as attached

I reckon it has something to do with the repo having move and is likely more a VS Code problem. Still, it would be helpful to update the README tho. Maybe there's a way to manually install older versions, but I can't seem to find a packaged release.

**Comment by mrcrch** [comment]
Same here

**Comment by adamrushuk** [comment]
I've tested the latest version, but it's not ready for my use-case yet so I need to downgrade to the previous version. I believe the previous version was `1.4.0`, but I can only see `1.3.12` under Releases: https://github.com/hashicorp/vscode-terraform/releases

How can we downgrade to the previous version?

**Comment by abelal83** [comment]
upgrading to latest version has caused extension to completely stop working, attempted to downgrade but getting 404

**Comment by Colliwhopper** [comment]
getting 404 error too trying to downgrade...

**Comment by ipavlushin** [comment]
As temporary solution you can download vsix with previous version from https://www.vsixhub.com/vsix/382/ and install it manually via `code --install-extension terraform-1.4.0_vsixhub.com.vsix`

**Comment by jacobwgillespie** [comment]
There's a download extension link on the [extension page](https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform) sidebar (under `Resources`), and it appears you can adjust the version in the download URL, so:

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/HashiCorp/vsextensions/terraform/1.4.0/vspackage

Should be safer than downloading extensions from third-party websites.

**Comment by adamrushuk** [comment]
Just tested the `v1.4.0` release and it worked fine: https://github.com/hashicorp/vscode-terraform/releases/tag/v1.4.0

**Comment by paultyng** [comment]
We added some instructions and links to the previous VSIX's here: https://github.com/hashicorp/vscode-terraform/wiki/Install-a-Pre-transfer-Version

This was an unintended consequence of the VS Code Marketplace transfer process, that you couldn't use the standard downgrade / pinning options.

**Comment by paultyng** [comment]
Hey all, just a heads up, this actually appears to be an upstream VS Code bug: https://github.com/microsoft/vscode/issues/99699#issuecomment-643379024

We will track the upstream issue in #385 and update there once we have more info.
