### ISSUE TITLE
Language server requires `serve` argument to start up, differs from previous language server

### ISSUE THREAD

**Issue by tantweiler** [hashicorp/vscode-terraform#374]
After upgrading to v2.0.1 the language server crashes permanently. 
<img width="450" alt="image" src="https://user-images.githubusercontent.com/48676838/84376183-fafb0400-abe0-11ea-8683-4281ba57540a.png">

VS-Code v1.46.0 is running on MacOS 10.15.5.

**Comment by jenshonkan84** [comment]
Work around that worked for me is to put in (in settings.ini)
``` 
"pathToBinary": "/Users/xxx/.vscode/extensions/hashicorp.terraform-2.0.1/lsp/terraform-ls",

**Comment by tillig** [comment]
Same issue, same versions
- Terraform plugin 2.0.1
- VS Code 1.46.0
- MacOS 10.15.5

Log from output window:

```
Launching language server: /Users/tillig/.vscode/extensions/hashicorp.terraform-2.0.1/lsp/terraform-ls 
Usage: terraform-ls [--version] [--help] <command> [<args>]

Available commands are:
    completion    Lists available completion items
    serve         Starts the Language Server

[Info  - 6:47:11 AM] Connection to server got closed. Server will restart.
Usage: terraform-ls [--version] [--help] <command> [<args>]

Available commands are:
    completion    Lists available completion items
    serve         Starts the Language Server

[Info  - 6:47:11 AM] Connection to server got closed. Server will restart.
Usage: terraform-ls [--version] [--help] <command> [<args>]

Available commands are:
    completion    Lists available completion items
    serve         Starts the Language Server

[Info  - 6:47:11 AM] Connection to server got closed. Server will restart.
Usage: terraform-ls [--version] [--help] <command> [<args>]

Available commands are:
    completion    Lists available completion items
    serve         Starts the Language Server

[Info  - 6:47:11 AM] Connection to server got closed. Server will restart.
Usage: terraform-ls [--version] [--help] <command> [<args>]

Available commands are:
    completion    Lists available completion items
    serve         Starts the Language Server

[Error - 6:47:11 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by tillig** [comment]
I do see the default args in my settings.json:

```json
{
    "terraform.languageServer": {
        "external": true,
        "args": [
            "serve"
        ]
    }
}
```

But I also see that [I should be seeing](https://github.com/hashicorp/vscode-terraform/blob/7fd81ed6d40c93cfb9129515d58f2a0ac6216fa0/src/extension.ts#L109) a line that says something like:

`Launching language server: /.../terraform-ls serve`

That is, the args should be there because [they should be getting read from config](https://github.com/hashicorp/vscode-terraform/blob/master/src/extension.ts#L106) but I don't see the `serve` arg in the log. I'm guessing something is messed up with the configuration reading...?

**Comment by tillig** [comment]
Oh, I figured my issue out, maybe the same for others:

In my workspace I had a `.vscode/settings.json` file left over from the previous extension. It had - you guessed it - language server setting overrides.

```json
{
  "terraform.languageServer": {
    "enabled": true,
    "args": []
  }
}
```

So... yeah, empty arg array. Removing the `settings.json` from the workspace got the language server working for me. I gather the previous language server didn't require default args.

**Comment by paultyng** [comment]
Going to close this since it seems to just be a config mismatch. I re-titled it to improve discoverability, I'll also update the README with default configuration.

**Comment by paultyng** [comment]
Update added in d9f1b5a86b8eb6c4fdb3330fdd6bd93c333006de
