### ISSUE TITLE
Can't pin to earlier version of this extension

### ISSUE THREAD

**Issue by bnm22** [hashicorp/vscode-terraform#381]
I'm running Terraform 0.11.x and I can't pin the extension to an earlier version. The previous versions fail to load.

**Comment by nikskiz** [comment]
Maybe we should fork the repo and revert the changes back?

**Comment by maxannear** [comment]
Workaround for now:

Remove the 2.0 version

Download the .vsix for 1.4.0 here - https://github.com/hashicorp/vscode-terraform/releases/tag/v1.4.0

[Install it into vscode manually](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix)
```
code --install-extension mauve.terraform-v1.4.0.vsix
```

**Comment by paultyng** [comment]
This appears to be an upstream bug in VS Code: https://github.com/microsoft/vscode/issues/99699#issuecomment-643379024

Going to merge this in to #385 for tracking.

**Comment by ciaranevans** [comment]
> Workaround for now:
> 
> Remove the 2.0 version
> 
> Download the .vsix for 1.4.0 here - https://github.com/hashicorp/vscode-terraform/releases/tag/v1.4.0
> 
> [Install it into vscode manually](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix)
> 
> ```
> code --install-extension mauve.terraform-v1.4.0.vsix
> ```

Hi, thanks for the work-around, I'm also one of those that's affected by this breaking change.

Do you perhaps know how I would install this inside a Remote Container?

**Comment by paultyng** [comment]
@ciaranevans I have not tried this with a Remote Container, but in WSL the extensions pane shows multiple sections like this (see below) so you can install it in different sides of the runtime, do you get the same in Remote Containers? I'll have to try to spin one up, but haven't had an opportunity yet.

![image](https://user-images.githubusercontent.com/422474/84699928-6534e100-af20-11ea-8401-08585e62941d.png)
