### ISSUE TITLE
Code complete not working in vs code

### ISSUE THREAD

**Issue by chrisgallivan** [hashicorp/vscode-terraform#384]
I have version 2.0.1 of the extension installed in vs code 1.46.0

I can't get the code completion to work. 

I type a resource block in azurerm, and nothing happens to assist me.

**Comment by feeyu7** [comment]
I open a issue like that at #383

**Comment by tnightengale** [comment]
There appears to be a lot of issues with the new 2.0.1 version. To summarize my understanding thus far:
- the old formatting settings are now configured through the language server
- there is a stable language server supporting terraform 0.12, however when trying to enable the language server, 2.0.1 requires a .terraform file in the root of you VScode folder that you have opened (annoying for users that open a larger project where tf is a sub folder)
- some people have circumvented the above issue by adding a dummy .terraform file in their root that they work in, but frankly this seems like a garbage hack - and ostensibly would require adding .terraform files to any parent folder that opens to be "root" when opening it in VScode
- personally I downloaded the vsix for 1.4.0 and will be using that (despite the lack of 0.12 language support) until all these issue get fixed up

**Comment by paultyng** [comment]
Going to merge this with hashicorp/terraform-ls#32. Additional folder configurations are now supported, and we will be allowing users to easily configure/list their root module directories in #423
