### ISSUE TITLE
Unable to pin previous version of extension

### ISSUE THREAD

**Issue by QuinnStevens** [hashicorp/vscode-terraform#385]
Our company uses Terraform 11 currently, and when the 2.0 version of the extension came out there was a note that if one wanted to keep terraform 11 support, they'd need to pin the extension to an older version.

However, when I select "install a different version" on the Terraform extension, the "Select Version to Install..." dialogue box comes up for about a second and a half, before disappearing with a "Server returned 404" error. This isn't a problem for other extensions I have installed, so I don't *think* it's a problem on my end. Anyone have any ideas?

**Comment by QuinnStevens** [comment]
In case this is relevant, I'm running vscode on a Macbook Pro

**Comment by aicarmic** [comment]
Thanks for flagging @QuinnStevens, this appears to be a bug introduced on the Marketplace affecting all extensions and is being actively investigated. Please see https://github.com/microsoft/vscode/issues/99699

**Comment by paultyng** [comment]
I've written up manual downgrade instructions in the meantime: https://github.com/hashicorp/vscode-terraform/wiki/Install-a-Pre-transfer-Version

**Comment by paultyng** [comment]
This looks like its fixed upstream, the release next thursday of VS Code should have the fix.

**Comment by aicarmic** [comment]
@QuinnStevens Going to mark as closed as this was fixed upstream in https://github.com/microsoft/vscode/issues/99699 and previous versions are now available for install again. Thanks for the report, and let us know if you encounter any further issues.
