### ISSUE TITLE
Nothing works after update to 2.x

### ISSUE THREAD

**Issue by dac73** [hashicorp/vscode-terraform#386]
It's kinda unusable now, and install another version returns 404

:disappointed: 

Currently looks like extension doesn't support configuration with multiple environments configs with subfolders, and if I open "project" from env folder then all referenced modules don't work.
My setup (that was working until now):

```
.
├── env
│   ├── staging-dev
│   │   ├── main.tf
│   │   └── variables.tf
│   └── staging-qa
│       ├── main.tf
│       └── variables.tf
├── modules
│   ├── some_module
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   └── variables.tf
└── README.md
```

**Comment by dac73** [comment]
To install working version: https://github.com/hashicorp/vscode-terraform/issues/381#issuecomment-643065132

**Comment by 3mard** [comment]
Same here, very frustrating

**Comment by brandonh-msft** [comment]
.tf file formatting also busted.

**Comment by chriswacker** [comment]
I share your frustration. I had to install 1.4 with the .vsix and am still working with 0.11 syntax. At least that way you get some more advanced autocomplete, and even supports multiple configurations in sub-directories (which last I heard has no plans for support in 2.0).

As long as you open a single, initialized configuration, you get the listed features, which are only:

> - Manages installation and updates of the Terraform Language Server (terraform-ls), exposing its features:
>   - Initialized provider completion (resource names, data source names, attribute names)
> - Includes syntax highlighting for .tf and .tfvars files (and .hcl) -- including all syntax changes new to Terraform 0.12
> - Closes braces and quotes
> - Includes for_each and variable syntax shortcuts (fore, vare, varm)

**Comment by dac73** [comment]
Well if that is true, I hope some one will fork 1.4 and continue from there.

1.4 work wonders for 0.12

2.x is huge disappointment in current state.

**Comment by rpstreef** [comment]
I have a similar setup as the OP, this version completely breaks and is unusable.

**Comment by jianzhiteh** [comment]
Auto formatting doesn't work anymore... "There is no formatter for 'terraform' files installed."

**Comment by feeyu7** [comment]
No formating, no linting, no code suggestions.

**Comment by darrenfurr** [comment]
Ran into the same problem...workaround:
- Remove 2.0.1 extension from VS Code
- Download 1.4.0 of the vsix from here: https://github.com/hashicorp/vscode-terraform/releases/download/v1.4.0/mauve.terraform-v1.4.0.vsix
- Manually install it: `code --install-extension mauve.terraform-v1.4.0.vsix`
- Restart VS Code
- When prompted install language server: v.0.0.11-beta1

All the formatting is back & everything is happy again.

**Comment by paultyng** [comment]
Here are the canonical tracking issues for things raised in this thread:

* Different folder structures: hashicorp/terraform-ls#32
* Formatting without initialization: hashicorp/terraform-ls#165
* Diagnostic support (red squiggles): hashicorp/terraform-ls#27
* VS Code downgrade issue: microsoft/vscode#99699

Until the VS Code issue is resolved, you can manually downgrade following these instructions: https://github.com/hashicorp/vscode-terraform/wiki/Install-a-Pre-transfer-Version

**Comment by vikassood1** [comment]
Thank you

> Ran into the same problem...workaround:
> 
> * Remove 2.0.1 extension from VS Code
> * Download 1.4.0 of the vsix from here: https://github.com/hashicorp/vscode-terraform/releases/download/v1.4.0/mauve.terraform-v1.4.0.vsix
> * Manually install it: `code --install-extension mauve.terraform-v1.4.0.vsix`
> * Restart VS Code
> * When prompted install language server: v.0.0.11-beta2
> 
> All the formatting is back & everything is happy again.

Thank you so very much. Good to know I am not the only one losing my mind

**Comment by feeyu7** [comment]
@paultyng 

The formatting does not work at all, not only when there is a missing initialization. And what is about code suggestions? In which Ticket it will be solved? Sorry for asking, but i dont see that and i alredy asked in another issue where this is not been answered.

**Comment by paultyng** [comment]
@feeyu7 I think both of those issues are related to the different folder structure issue (https://github.com/hashicorp/terraform-ls/issues/32). We are working to support multiple different root and nested module configurations (including allowing users to just specify the one they want to use). So even if initialized, the root module detection is not finding the appropriate directory so causing it problems.

**Comment by chelnak** [comment]
> Ran into the same problem...workaround:
> 
> * Remove 2.0.1 extension from VS Code
> * Download 1.4.0 of the vsix from here: https://github.com/hashicorp/vscode-terraform/releases/download/v1.4.0/mauve.terraform-v1.4.0.vsix
> * Manually install it: `code --install-extension mauve.terraform-v1.4.0.vsix`
> * Restart VS Code
> * When prompted install language server: v.0.0.11-beta2
> 
> All the formatting is back & everything is happy again.

Thank you!
