### ISSUE TITLE
Move this to Terraform preview/nightly extension and restore the old version

### ISSUE THREAD

**Issue by nikolay** [hashicorp/vscode-terraform#389]
This is crashing constantly on basic plans.

**Comment by neodon** [comment]
I was excited about finally getting proper support in VSCode for terraform 0.12.  Now after wasting hours trying to get v2 to work and having to go back to v1.4, I am thoroughly disappointed and turned off of terraform and HashiCorp.

First of all, IDE tooling should have been developed way back alongside 0.12 before it was even close to release.  Maybe an unpopular opinion, but I think tooling is more important than new features.  Tooling is what enables people to be productive and happy with those new features.  Neglecting tooling is like removing essential features.  Using terraform the past several months without IDE support has been really obnoxious.

Second, don't replace an existing version of something like this extension with a new version that is not only nowhere near as good as far as feature parity and stability, but doesn't even work at all.  And users are forced to manually downgrade.  Use whatever mechanism or process you need to test the new software with users and issue preview releases until it's ready.

I appreciate being able to vent a little, and I know the devs are working hard to make this extension better.  I think some reflection by HashiCorp is in order on how Terraform 0.12 and the tooling worked out (and is still working out).

**Comment by paultyng** [comment]
Unfortunately we are limited by the VS Code marketplace in what we can do. Downgrading / pinning through the VS Code UI was [broken in the most recent VS Code release](https://github.com/microsoft/vscode/issues/99699#issuecomment-643379024), and the Marketplace Publishing UI does not have any sort of options for specific version management. We are still waiting on the upstream fix for easy downgrading.

We are tracking the VS Code upstream downgrade issue in #385, going to merge this issue with that one.
