### ISSUE TITLE
Language server is failing to start.

### ISSUE THREAD

**Issue by sunnynazar** [hashicorp/vscode-terraform#390]
I am getting below error while trying to install the latest version of this extension.
----------------------------------------------------------------------------------------
Launching language server: c:\Users\SunnyNazar\.vscode\extensions\hashicorp.terraform-2.0.1/lsp/terraform-ls serve
[Error - 9:00:32 PM] Starting client failed
Error: spawn EBUSY
	at ChildProcess.spawn (internal/child_process.js:394:11)
	at Object.spawn (child_process.js:553:9)
	at c:\Users\SunnyNazar\.vscode\extensions\hashicorp.terraform-2.0.1\node_modules\vscode-languageclient\lib\main.js:354:40

-----------------------------------------------------------------------------------------

Could you please check.

**Comment by vfab** [comment]
Mine fails to start as well, but with a different error message.  It says `Error for "initialize" (ID 0): [-32098] Workspace not initialized. Please run 'terraform init' in c:\....`.  But the main folder for my code base doesn't contain any Terraform code.  The Terraform is all in subfolders.  Others on my team have the same problem.  It appears the extension is quite busted now.

**Comment by awilkins** [comment]
There's a bunch of other tickets for this problem : `terraform-ls` the "stable" language server needs a `.terraform` folder with provider plugins in to start ; in your root folder.

`terraform-lsp`, the "unstable" one doesn't.

I've got a local fork of `terraform-lsp` because I've been fixing some of it's panic bugs that cause it to crash, so I just build it and set

```
    "terraform.languageServer": {
        "pathToBinary": "/path/to/built/terraform-lsp",
        "external": true,
    },
```

And everything works.

**Comment by briangardner** [comment]
I'm experiencing the same issue.  The root folder of the workspace does not have the terraform code, so the server blows up.  And since pinning to a previous version of the plugin is also broken, this plugin is now completely useless.

**Comment by mishak87** [comment]
UX wise this error is really annoying. Because it switches focus to terraform output (on same panel as terminal) so every time I open new project, load window etc. this panel steals focus from terminal.

**Comment by Walther** [comment]
Confirming on extension version `v2.0.1` on VSCode `Version: 1.46.0`

```
[Error - 4:59:51 PM] Server initialization failed.
  Message: Workspace not initialized. Please run `terraform init` in /Users/walther/git/[redacted]
```

Thankful for all the good work in the extension whenever I'm working on Terraform, and would appreciate the extension staying quiet when I'm working on something else

**Comment by paultyng** [comment]
The initialization error messaging has been softened and focus hijacking addressed. Some features also now don't require an initialized root module. The most recent version of the LS also will do some discovery of additional root module locations in some scenarios and we are adding override capability in #423.

Going to close this in favor of some of the other issues open for more specific features/bugs. The best tracking issue on the LS side for various directory/module configurations is hashicorp/terraform-ls#32.
