### ISSUE TITLE
Formatter stopped working 

### ISSUE THREAD

**Issue by MarkKharitonov** [hashicorp/vscode-terraform#393]
It was working for a while, but now it is not.

VS Code version:
```
Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763
```
Extension details:
```
Name: Terraform
Id: hashicorp.terraform
Description: Syntax highlighting, linting, formatting, and validation for Hashicorp's Terraform
Version: 2.0.1
Publisher: HashiCorp
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform
```
Running the Format Document command opens the **There is no formatter for 'terraform' files installed.** popup and suggests to **Install Formatter...**:
![image](https://user-images.githubusercontent.com/489792/84662810-4c113d80-aeea-11ea-9c3b-633c2f9c9a44.png)
Clicking **Install Formatter...** opens a list of code extensions, with this extension being present and marked as already installed (because it has been indeed already installed). At this point, I do not know what am I supposed to do:
![image](https://user-images.githubusercontent.com/489792/84663004-91356f80-aeea-11ea-8f98-0c4f6112fef4.png)

**Comment by btisdall** [comment]
Same here on macOS:

```
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z (5 days ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

Extension version `v2.0.1`

**Comment by darrenfurr** [comment]
I ran into the same problem on macOS. Found a workaround by using 1.4.0:
https://github.com/hashicorp/vscode-terraform/issues/386#issuecomment-644187733

**Comment by alexander-klang** [comment]
There is a workaround - you have to open the folder that contains .tf files. But this is not optimal - I would prefer to open top folder where I have all the subfolders with all the .tf files inside.

**Comment by paultyng** [comment]
Here is the tracking issue on the LS, this should be relaxed in a release soon: https://github.com/hashicorp/terraform-ls/issues/165
