### ISSUE TITLE
Server returned 404 when trying to install another version

### ISSUE THREAD

**Issue by yujunz** [hashicorp/vscode-terraform#394]
Trying to pin to earlier version but "Install another version" resulted in `Server returned 404` error.

**Comment by ankitkotnala** [comment]
Same error, ever since 2.0.1 release .Language server is not working and can't revert to previous version

**Comment by paultyng** [comment]
This is an upstream VS Code error: https://github.com/microsoft/vscode/issues/99699

We are tracking the resolution in #385 as well so going to close this in favor of that issue.
