### ISSUE TITLE
"Intellisense" does not like variables.tf

### ISSUE THREAD

**Issue by tymac753** [hashicorp/vscode-terraform#398]
Issue Type: <b>Bug</b>

It appears that the terraform plug-in is not parsing terraform variables correctly. The coloring breaks as soon as a varaible contains a description field.

Extension version: 2.0.1
VS Code version: Code - Insiders 1.47.0-insider (0288447572790f983c350905bd1fc5b754970a0a, 2020-06-15T07:44:14.223Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 2700 Eight-Core Processor       (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by horuscoding** [comment]
I just ran into a very similar problem today. More specifically for me though, highlighting would break down whenever there was no whitespace between the "=" and a string value.

For instance, highlighting would break for
`variable "broken" {
    description =""
    type = string
}`

But works as expected with 
`variable "working" {
    description = ""
    type = string
}`

**Comment by tymac753** [comment]
This is the exact issue. Not certain it that's by design but terraform will execute regardless as valid code.

**Comment by aeschright** [comment]
This was fixed in #428 and will go out in the next release. Thanks for reporting it!
