### ISSUE TITLE
Extension crash all the time

### ISSUE THREAD

**Issue by tnimni** [hashicorp/vscode-terraform#400]
Hi,

I have a complex terraform code, which i split into lib as suggested in "terraformform up and running 2"

every time the extension crash

attached is the output

`Launching language server: /Users/<USER NAME>/.vscode/extensions/hashicorp.terraform-2.0.1/lsp/terraform-ls serve
2020/06/18 01:58:10 service.go:63: Preparing new session ...
2020/06/18 01:58:10 langserver.go:79: Starting server (pid 9356) ...
2020/06/18 01:58:10 server.go:469: Received 1 new requests
2020/06/18 01:58:10 server.go:165: Processing 1 requests
2020/06/18 01:58:10 server.go:223: Checking request for "initialize": {"processId":9249,"rootPath":"/Users/<USER NAME>/src/<REMOVED FOR SECUIRTY REASONS>","rootUri":"file:///Users/<USER NAME>/src/<REMOVED FOR SECUIRTY REASONS>","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true}}},"trace":"off","workspaceFolders":[{"uri":"file:///Users/<USER NAME>/src/<REMOVED FOR SECUIRTY REASONS>","name":"<REMOVED FOR SECUIRTY REASONS>"}]}
2020/06/18 01:58:10 rpc_logger.go:29: Incoming request for "initialize" (ID 0): {"processId":9249,"rootPath":"/Users/<USER NAME>/src/<REMOVED FOR SECUIRTY REASONS>","rootUri":"file:///Users/<USER NAME>/src/<REMOVED FOR SECUIRTY REASONS>","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true}}},"trace":"off","workspaceFolders":[{"uri":"file:///Users/<USER NAME>/src/<REMOVED FOR SECUIRTY REASONS>","name":"<REMOVED FOR SECUIRTY REASONS>"}]}
2020/06/18 01:58:10 exec.go:176: Starting /usr/local/bin/terraform ["terraform" "version"] in "/var/folders/2m/7q98kxvx18l69cqwhbd00chh0000gn/T/"...
2020/06/18 01:58:10 exec.go:142: Waiting for command to finish ...
2020/06/18 01:58:11 exec.go:168: terraform run (/usr/local/bin/terraform ["terraform" "version"], in "/var/folders/2m/7q98kxvx18l69cqwhbd00chh0000gn/T/", pid 9359) finished with exit code 0
2020/06/18 01:58:11 initialize.go:90: Found compatible Terraform version (0.12.24) at /usr/local/bin/terraform
2020/06/18 01:58:11 schema_storage.go:334: Adding workspace for watching: "/Users/<USER NAME>/src/<REMOVED FOR SECUIRTY REASONS>"
2020/06/18 01:58:11 schema_storage.go:124: Acquiring semaphore before retrieving schema for "/Users/<USER NAME>/src/<REMOVED FOR SECUIRTY REASONS>" ...
2020/06/18 01:58:11 watcher.go:88: Adding "/Users/<USER NAME>/src/<REMOVED FOR SECUIRTY REASONS>/.terraform/plugins/darwin_amd64/lock.json" for watching...
2020/06/18 01:58:11 schema_storage.go:133: Retrieving schemas for "/Users/<USER NAME>/src/<REMOVED FOR SECUIRTY REASONS>" ...
2020/06/18 01:58:11 exec.go:176: Starting /usr/local/bin/terraform ["terraform" "providers" "schema" "-json"] in "/Users/<USER NAME>/src/<REMOVED FOR SECUIRTY REASONS>"...
2020/06/18 01:58:11 rpc_logger.go:45: Error for "initialize" (ID 0): [-32098] Workspace not initialized. Please run `terraform init` in /Users/<USER NAME>/src/<REMOVED FOR SECUIRTY REASONS>
2020/06/18 01:58:11 server.go:204: Completed 1 requests [1.336849928s elapsed]
[Error - 1:58:11 AM] Server initialization failed.
  Message: Workspace not initialized. Please run `terraform init` in /Users/<USER NAME>/src/<REMOVED FOR SECUIRTY REASONS>
  Code: -32098 
2020/06/18 01:58:11 exec.go:142: Waiting for command to finish ...
2020/06/18 01:58:11 server.go:469: Received 1 new requests
2020/06/18 01:58:11 server.go:165: Processing 1 requests
2020/06/18 01:58:11 server.go:223: Checking request for "shutdown": 
2020/06/18 01:58:11 rpc_logger.go:29: Incoming request for "shutdown" (ID 1): 
2020/06/18 01:58:11 rpc_logger.go:50: Response to "shutdown" (ID 1): null
2020/06/18 01:58:11 server.go:204: Completed 1 requests [187.236µs elapsed]
2020/06/18 01:58:11 server.go:469: Received 1 new requests
2020/06/18 01:58:11 server.go:165: Processing 1 requests
2020/06/18 01:58:11 server.go:223: Checking request for "exit": 
2020/06/18 01:58:11 rpc_logger.go:29: Incoming notification for "exit": 
2020/06/18 01:58:11 schema_storage.go:116: error obtaining schemas: Unable to retrieve schemas: failed to get schemas: Execution of ["terraform" "providers" "schema" "-json"] canceled.
signal: killed`

**Comment by giovannifl** [comment]
I believe you're in this scenario:
https://github.com/hashicorp/vscode-terraform/issues/390

As stated in another / related thread, "...There appears to be a lot of issues with the new 2.0.1 version. To summarize my understanding thus far:

- there is a stable language server supporting terraform 0.12, however when trying to enable the language server, 2.0.1 requires a .terraform file in the root of you VScode folder that you have opened (annoying for users that open a larger project where tf is a sub folder)..
"

https://github.com/hashicorp/vscode-terraform/issues/384

**Comment by paultyng** [comment]
This code path has changed pretty substantially in the latest versions of the [LS](https://github.com/hashicorp/terraform-ls), supporting different root module structures and softening how some of these issues are raised and what functionality is dependent upon the root module. Going to close as I believe any remaining issues are already covered in existing issues in the repo.
