### ISSUE TITLE
Since v2.0.0 the plugin's output constantly steals the focus from terminal during normal editing

### ISSUE THREAD

**Issue by courteouselk** [hashicorp/vscode-terraform#406]
When editing a .tf file, while typing any statement, the plugin will steal the focus and flood the output window with diagnostic messages about incorrect syntax. This is counter-productive (and annoying) because it's to be expected that until I finished typing the code some parts of it will be incomplete and therefore invalid, so no need to spam me with notifications about that.

**Comment by strowk** [comment]
I see no value in terraform output at all, all necessary output is given from CLI and it's in terminal (nicely highlighted and conveniently static). I'd suggest to completely cut that output.

**Comment by strowk** [comment]
BTW, that's actually a workaround - you can right click on "Output" tab and choose "Hide". That makes output completely unavailable, but I've never seen anything useful there anyway
