### ISSUE TITLE
Only works when on main directory?

### ISSUE THREAD

**Issue by bradennapier** [hashicorp/vscode-terraform#412]
Our setup is built with many environments and different terraform folders/modules.

Therefore our main directory for the repo is not really where the lsp should be expecting. 

Basically this completely crashes on load because it only works if we open each environment folder separately.

Seems the extension should instead search for `.terraform` folders and expect each of those to be a root environment or terraform project.  If no `.terraform` folder is found then it should just not run at all imo outside of the syntax highlighting and formatting.

```
repo/
 | - environments
 -- one
 -- two
 -- two
 |- modules
...
```

**Comment by uncycler** [comment]
I run on the same issue as well. Unfortunately, this makes the extensions unusable when having multiple directories.

**Comment by Sturgelose** [comment]
Already tracked here: https://github.com/hashicorp/vscode-terraform/issues/330

**Comment by paultyng** [comment]
This is probably more relevant if this is inside a single workspace directory: https://github.com/hashicorp/terraform-ls/issues/32

There is a PR proposed on the LS now with some fixes for this, hoping to test it this week and get it out shortly.
