### ISSUE TITLE
Add method to review LS changelog when update is downloaded

### ISSUE THREAD

**Issue by paultyng** [hashicorp/vscode-terraform#415]

**Comment by radeksimko** [comment]
Related to https://github.com/hashicorp/terraform-ls/issues/63

**Comment by radeksimko** [comment]
Right now the changelog in [GitHub Releases](https://github.com/hashicorp/terraform-ls/releases) is something I copy paste after the release is done - hoping to automate that, but it may be the best source, although it means re-introduction of GitHub's SDK into the extension (and potentially having to deal with API rate limitation?).

**Comment by paultyng** [comment]
It could maybe just be a link and not have to actually pull the content down.

**Comment by aeschright** [comment]
Given the size of the window we're working with, I think a link is the best choice.
