### ISSUE TITLE
Should work when using multiple children projects

### ISSUE THREAD

**Issue by Sytten** [hashicorp/vscode-terraform#417]
Before this update, I was able to managed all my projects even if I opened a parent folder containing multiple projects, now it just fails to init with the message `Workspace not initialized. Please run terraform init`.
It is very common to have a lot of projects in a decent architecture, something like:
```
aws/
├── modules/
│   ├── service/
├── projects/
│   ├── dns/
│   └── cluster/
``` 

Or even something like
```
aws/
├── modules/
│   ├── service/
├── projects/
│   ├── dev/
│   └── prod/
```

**Comment by radeksimko** [comment]
Hi @Sytten 
Have you tried the extension with the last updated version of the language server (v0.4.0, published yesterday)?

The new version will walk through the hierarchy of directory opened in VSCode and attempt to add any initialized root modules (any directories which have been `terraform init`'d). See the full [changelog](https://github.com/hashicorp/terraform-ls/blob/v0.4.0/CHANGELOG.md#040-25-june-2020).

VSCode should prompt you for the update on a fresh launch, or you can just try restarting it.

**Comment by paultyng** [comment]
We are also adding support for manual specification of root module folders as a workaround while discovery is improved on the LS, you can track that in #396. If your structure isn't covered in 0.4.0 as suggested by Radek above, you can track improvements in the LS for different folder structures in https://github.com/hashicorp/terraform-ls/issues/32

**Comment by bradennapier** [comment]
> We are also adding support for manual specification of root module folders as a workaround while discovery is improved on the LS, you can track that in #396. If your structure isn't covered in 0.4.0 as suggested by Radek above, you can track improvements in the LS for different folder structures in [hashicorp/terraform-ls#32](https://github.com/hashicorp/terraform-ls/issues/32)

The feature `rootModules` is basically useless in most cases.  generally if you need to define that many paths you want to do relative paths not absolute paths... you can get the project directory easily enough so that should be the relative base so that the settings do not need to be made for every user independently and can instead just be added once in a project-local `.vscode/settings.json`

**Comment by radeksimko** [comment]
Relative paths are tracked under https://github.com/hashicorp/terraform-ls/issues/235 - that is something we will ship independently of the extension's release cycle.

**Comment by Sytten** [comment]
I think this is fixed now, unless somebody has a particular usecase that doesnt work I propose we close the issue

**Comment by aeschright** [comment]
Since there are no further comments, I'll close it. Please open a new issue if needed.
