### ISSUE TITLE
Read LS version from stdout+stderr

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/vscode-terraform#418]
As per https://github.com/hashicorp/terraform-ls/issues/185 printing out version output to stderr was an unfortunate oversight.

https://github.com/hashicorp/vscode-terraform/blob/1c882b35bb52e834214fad186c167f8ecaf04804/src/languageServerInstaller.ts#L32

I'm not sure of all the implications for old versions lying around, but I think we could at least start reading from both stdout and stderr, with `stdout` having priority (if it's not empty)?

**Comment by aeschright** [comment]
I think reading from stdout and falling back to stderr should be fine on the extension side.
