### ISSUE TITLE
expose settings in code settings

### ISSUE THREAD

**Issue by FernandoMiguel** [hashicorp/vscode-terraform#425]
can you expose the settings in vscode settings, instead of having to do it all in the json?

also, what are the default and available options?

```json
"files.associations": {
	"terragrunt.hcl": "terraform",
	"*.tfvars": "terraform",
	"*.tf": "terraform",
	"*.tf.override": "terraform",
},
"files.watcherExclude": {
	"**/.terraform/**": true,
	"**/.terragrunt-cache/**": true
},
"[terraform]": {
	"editor.formatOnSave": true
},
"terraform.languageServer": {
	"enabled": true,
	// "external": true,
	// "args": [
	//     "serve"
	// ]
},
```

**Comment by FernandoMiguel** [comment]
bump ?

**Comment by paultyng** [comment]
We are reworking some of this now (see #423 for one). 

Unfortunately VS Code requires these exposed in a certain way to be UI visible, so the names and things need to change to expose it in the UI (it can't be nested) which would be a breaking config change. Not that I don't think we should expose things where possible in the UI, but its not just a simple (ie. `editInUI: bool`) type change to expose it.

**Comment by FernandoMiguel** [comment]
breaking change, so v3.0?

**Comment by radeksimko** [comment]
We plan to do a small overhaul of the extension settings as part of https://github.com/hashicorp/vscode-terraform/issues/791 - one of the main motivations is exactly to make all settings easily available through the UI as you mentioned - with that in mind I'm going to close this issue in favour of #791 

Existing settings are currently documented under the Readme: https://github.com/hashicorp/vscode-terraform#configuration
