### ISSUE TITLE
Documentation Links

### ISSUE THREAD

**Issue by jkodroff** [hashicorp/vscode-terraform#433]
In previous versions of the plugin, I could Command-click (OSX, Ctrl-click on Windows) to get to the docs for any resource.  This feature appears to no longer work.

Could we bring back this feature?  I found it incredibly useful and is common in other languages in VS Code.

**Comment by mattburgess** [comment]
Looks like this will be handled on the language server side: https://github.com/hashicorp/terraform-ls/issues/190

**Comment by radeksimko** [comment]
This is indeed being handled on the language server side.

https://github.com/hashicorp/terraform-ls/pull/402 was just released yesterday as part of 0.14.0 and more improvements in that area are tracked under https://github.com/hashicorp/terraform-ls/issues/418 and https://github.com/hashicorp/terraform-ls/issues/190 as already mentioned.

With that in mind I would recommend subscribing to these issues and/or commenting with any feedback you may have related to these features there.

I'm going to close this issue to keep the discussion in one place.

Thanks.
