### ISSUE TITLE
Install error: SHA sum for terraform-ls_0.5.1_darwin_amd64.zip does not match

### ISSUE THREAD

**Issue by alexjurkiewicz** [hashicorp/vscode-terraform#437]
This error pops up whenever I open a Terraform code directory in vscode 1.47.0.

**Comment by radeksimko** [comment]
Thanks for the report - I managed to reproduce it.

**Comment by radeksimko** [comment]
It appears that the shasum for darwin/amd64 is read from the SHA256SUMS file correctly as `baed46680be6559e1c653b86dad7da4f2ff9fe54360a3dbfd896863ba0683d74`, but the same one isn't calculated locally for some reason (`9852ff2eddc59dbbae069e60edce62e4c6e0f0f66b39920815a9b41a40ddb108`).
