### ISSUE TITLE
Multiline string interpolation still breaks syntax highlighting?

### ISSUE THREAD

**Issue by MichaelBrown08** [hashicorp/vscode-terraform#441]
Previous issue: https://github.com/hashicorp/vscode-terraform/issues/109
PR fix: https://github.com/hashicorp/vscode-terraform/pull/120

![image](https://user-images.githubusercontent.com/46346590/87851738-9de72200-c8f3-11ea-865d-599078868bb5.png)

Double quotes around the key breaks the syntax highlighting from then out.

After removing double quotes (which won't apply, errors on '$ is not used within the language'):

![image](https://user-images.githubusercontent.com/46346590/87851766-d5ee6500-c8f3-11ea-871f-66c11bcf1143.png)

Syntax is fine, and syntax from single-line string interpolation doesn't affect following resource syntax.

**Comment by robsonpeixoto** [comment]
A more complex example: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/aws_auth.tf

**Comment by drewmullen** [comment]
im running into something similar too: 
![image](https://user-images.githubusercontent.com/3812162/89932915-4bd8aa00-dbdc-11ea-942b-262dcfee08ff.png)

**Comment by mikew1927** [comment]
If I have even a space in a double-quoted string the syntax highlighting is quite broken. 
![image](https://user-images.githubusercontent.com/18093798/90989639-699c0b00-e5ef-11ea-8a28-3c70c708531e.png)

**Comment by DenWin** [comment]
This is a duplicate to #466 - or vice versa. Remove the equal sign before the curly bracket - even though breaking the code - the highlighting will be correct.

**Comment by danekan** [comment]
possibly related:
`resource_tags_merged = merge(local.resource_tags, { "Name" = "${local.tfenv.project_name}-${local.tfenv.environment}" })
`
breaks syntax highlighting in a similar way as described above for everything following the ${local.tfenv.environment}

**Comment by aeschright** [comment]
Hi folks, I can confirm the original examples are fixed in v2.2.1 so I'm going to close this ticket to let us focus on narrowing down other cases. If you see anything that appears to be a regression, or other unexpected highlighting, please open a new issue. Thanks!
