### ISSUE TITLE
Object key-value in array breaks syntax highliting

### ISSUE THREAD

**Issue by gentksb** [hashicorp/vscode-terraform#442]
When I input key-value set in object array, followed lines are got breaked highlighting.
 
See below.

![image](https://user-images.githubusercontent.com/36843875/87998811-f7d62a80-cb33-11ea-9174-d8fd74a19bc8.png)

![image](https://user-images.githubusercontent.com/36843875/87998789-e3922d80-cb33-11ea-9b69-7c75b4cf61d8.png)

![image](https://user-images.githubusercontent.com/36843875/87998856-12a89f00-cb34-11ea-949b-f29e6d3c7a97.png)

**Comment by privomark** [comment]
Experiencing the same behavior. For more context, my issue was the key value not respecting quotes. If I put the quote behind a comment, it would trick the extension to satisfying the closing quote.

![Screen Shot 2020-07-23 at 6 25 17 AM](https://user-images.githubusercontent.com/64918455/88312152-828e6500-ccad-11ea-895a-48438f3e7fde.png)
