### ISSUE TITLE
Still getting "No root module found for ..."

### ISSUE THREAD

**Issue by fcatacut** [hashicorp/vscode-terraform#447]
We have many repositories contain nothing but modules that are to be used in other repositories.  As such, we don't actually have any .tf files in the root folder.  Whenever I click on a .tf file in the Explorer or Source Control side bar, the following message pops up:

```
No root module found for <folder path to .tf file>. Functionality may be limited. You may need to run terraform init and reload your editor.
```

**HashiCorp Terraform**
2.1.1

**Visual Studio Code**
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

**Comment by cmamigonian** [comment]
Would love to know a way to disable this message.

**Comment by lobsterdore** [comment]
I have removed the extension because of this message.

**Comment by fcatacut** [comment]
This is actually getting worse because the pop-up notification is getting larger:

![image](https://user-images.githubusercontent.com/20847572/101962804-f0d2b600-3bc1-11eb-8a31-3667dd437ec9.png)

Honestly, I'd be content if we just had a means to disable this from popping up.

**HashiCorp Terraform**
v2.3.0

**Visual Studio Code**
Version: 1.52.0
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:46:53.673Z (1 day ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0

**Comment by radeksimko** [comment]
Hi folks,
the issue is not addressed _yet_, but we have a plan for addressing it and I'm just converging all the issues with the same root cause, such as this one, into a single issue: https://github.com/hashicorp/vscode-terraform/issues/569

Thank you for understanding and patience.
