### ISSUE TITLE
Formatter hangs

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [hashicorp/vscode-terraform#452]
Trying to format documents explicitly does nothing. There is no feedback, and no log lines appear in the output window for the Terraform extension, nor in the terraform-ls view there, when invoking the format command. (Note: there are other lines in the terraform-ls output window, but nothing that correlates with invoking the format command)

If I enable format-on-save, then saving just hangs forever waiting on the extension, still with no output in the aforementioned output windows.

What does appear in the terraform-ls window every few seconds is `service.go:81: Root modules waiting to be loaded: 0`, regardless of what I'm doing in the editor.

Using extension version 2.1.1

**Comment by wernerb** [comment]
Same problem with terraform 0.13.0 but

**Comment by appilon** [comment]
Hello, this is likely an issue on the language server (https://github.com/hashicorp/terraform-ls/issues/258), we believe this should be fixed in [v0.6.1](https://github.com/hashicorp/terraform-ls/releases/tag/v0.6.1)

I will close this for now, but we can reopen if needed

**Comment by mgabeler-lee-6rs** [comment]
Confirmed fix here, thank you!
