### ISSUE TITLE
Syntax higlighting on .hcl file

### ISSUE THREAD

**Issue by asolari** [hashicorp/vscode-terraform#453]
Syntax highlighting is not active for file with extension .hcl here.
I renamed my settings.json file, which had a few customizations, but still it doesn't work.

I also tried to reinstall version 2.1.1, still no luck.

What could I check to verify what's wrong here?
Thanks

**Comment by aeschright** [comment]
Hi @asolari – right now the extension doesn't support highlighting for .hcl files. We're working on a way to integrate it, but for now you might want to try one of the community extensions that does HCL only.

**Comment by asolari** [comment]
Hi @aeschright, ok I'll look into community extensions, as you suggest!
Thanks!

**Comment by tmaier** [comment]
@asolari which community extension are you using now?
