### ISSUE TITLE
VSCode autocomplete

### ISSUE THREAD

**Issue by andreyvital** [hashicorp/vscode-terraform#460]
For some reason, it doesn't work for autocompleting attribute references, only works at the root "resource" level. For example:

![image](https://user-images.githubusercontent.com/967317/90396961-82477680-e06d-11ea-949d-f594aac8a707.png)

Doesn't populate my **data** or any of the available resources options:

![image](https://user-images.githubusercontent.com/967317/90397001-91c6bf80-e06d-11ea-937e-56ef148a61f2.png)
![image](https://user-images.githubusercontent.com/967317/90397110-bae75000-e06d-11ea-870e-8ccd5533d363.png)

VSCode:
```
Version: 1.48.0
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T08:03:27.059Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
```

**terraform-ls**
```
devopz (master — ✔) % terraform-ls -v
0.6.0
```

![image](https://user-images.githubusercontent.com/967317/90397231-ec601b80-e06d-11ea-9801-74c3d94b2ff8.png)

**Comment by radeksimko** [comment]
Right-hand-side completion doesn't work _yet_, but it is tracked under https://github.com/hashicorp/terraform-ls/issues/38

With that in mind I will close this issue as a duplicate, to keep discussion in one place.

Thanks.
