### ISSUE TITLE
Quoted string interpolation not detected properly when map within map

### ISSUE THREAD

**Issue by danekan** [hashicorp/vscode-terraform#461]
Formatting appearance is not correctly tokenizing quotes when they are part of an assignment that is a map within a map, and that assignment makes use of string interpolation.

For example:

 default_settings = {
    test1 = {
      setting1 = "ami-aaa1e"
      item2     = "x"
      item3     = "${local.tfenv.project_name}-${local.tfenv.environment}"
      item4     = "not_showing_properly"
    }
  }

Will leave everything after ${local.tfenv.environment}" highlighted orange in VSC due apparently to not having interpreted the quotes within

![image](https://user-images.githubusercontent.com/5197850/90421093-7dd78980-e07e-11ea-88e6-ef36115f65fc.png)

**Comment by DenWin** [comment]
I strongly assume it is a duplicate to #466 .
Remove the equal-signs and the syntax highlighting is fixed (though the code will be broken ;-))

**Comment by danekan** [comment]
So you're saying #466 is a duplicate of #461 then? ;)

**Comment by DenWin** [comment]
> So you're saying #466 is a duplicate of #461 then? ;)

Technically they are all duplicates of #407

**Comment by danekan** [comment]
There is also #441 which #466 seems surely directly related to, that issue specifically states regarding multiline assignments, though.  This issue #461 happens whether or not there are multiple lines within the tag assignment (actually in my actual code I only have one within). 441 and 461 might be the same underlying code issues, but as it is stated now they don't seem to be the same symptoms to cause the issue reported. #407 might also be related in terms of the underlying issues, but I wouldn't assume.

**Comment by DenWin** [comment]
Had to delete my comment about 407, there I was wrong.

Here the comparison between with and without equal sign:
![image](https://user-images.githubusercontent.com/13867326/91084940-004ae500-e64d-11ea-9684-d691ca297e4a.png)

**Comment by danekan** [comment]
`resource_tags_merged =  merge(local.resource_tags, { "Name" = "${local.tfenv.project_name}-${local.tfenv.environment}" }) 
`
also breaks syntax highlighting for everything after it, but that might be more related to the underlying issue in #441

**Comment by aeschright** [comment]
Hi @danekan – I'm no longer able to reproduce the issue in your example using v2.2.1 so I'm going to close this. Please open new issues if you find cases that still appear to have the incorrect highlighting or any regressions. Thanks!

**Comment by danekan** [comment]
In 2.2.2 with visual studio code  1.48.2 these string interpolation syntax examples are still not highlighting correctly:

```
  default_settings = {
    abcds = {
      good = "ami-674cbc1e"
      goody = "${local.tfenv.x1}-${local.tfenv.x2}"
      nogoody = "ami-0fc20dd1da406780b"
    }
  }
```

And 

```
 resource_t = {
    for tag, tagvalue in local.resource_tags:
      tag =>  tag == "access-project" ? (length(tagvalue) < 1 ? "${local.tfenv.project_name}-${local.tfenv.environment}" : tagvalue) : tagvalue
  }
```

And 

`
  resource_tags_transformed_with_name =  merge(local.resource_tags_transformed, { "Name" = "${local.tfenv.project_name}-${local.tfenv.environment}" }) `
