### ISSUE TITLE
`tags = {` breaks syntax highlighting

### ISSUE THREAD

**Issue by tresni** [hashicorp/vscode-terraform#466]
Not sure if this belongs here or at [hashicorp/terraform-ls](https://github.com/hashicorp/terraform-ls), but the following block appears to break any subsequent stanzas:

```
resource "aws_instance" "test" {
  tags = {
    A = "thisisfine"
    B = "this is not fine"
    C = "neither.is.this"
  }
}

resource "aws_instance" "test2" {
    tags = {}
}

```

## Expected result:

Proper syntax highlighting with `"this is not fine"` and `"niether.is.this"` being highlighted as strings and the next block being highlighted normally.

## Actual Result:

<img width="254" alt="example tf — phishtank-infra 2020-08-20 17-01-03" src="https://user-images.githubusercontent.com/210250/90834130-be493880-e306-11ea-9468-7c2f69bda062.png">

Removing only `B =` or `C = ` lines still gives a broken block, each of those lines appears to break the parser.  Removing both lines and never having anything but `[a-z0-9]` in the tag value appears to be the only "fix".

**Comment by trotman23** [comment]
Adding some examples i've run into: 
```
resource "example" "test" {
  test = [{
    key = "valu-e"
  }]
}

resource "example" "test" {
  test = [{
    key = "value"
  }]
}
```

<img width="226" alt="Screen Shot 2020-08-20 at 6 38 13 PM" src="https://user-images.githubusercontent.com/2636805/90836178-5568bd00-e314-11ea-8a1c-13a79af4da35.png">

```
resource "example" "test" {
  test = [{
    domain = "example.com"
  }]
}

resource "example" "test" {
  test = [{
    key = "value"
  }]
  key = "value"
}
```

<img width="211" alt="Screen Shot 2020-08-20 at 6 40 08 PM" src="https://user-images.githubusercontent.com/2636805/90836290-99f45880-e314-11ea-953c-cf3aadec7163.png">

**Comment by phil737** [comment]
What seems to break the highlighting is xxx = {
I have the same issue with for example: 
config = {
   path = ""
}

If I write
config {
}
it works.

tags {
}
works as well. But of course is not correct.

**Comment by DenWin** [comment]
The problem can be drilled down to the equal sign in front of the curly bracket:
![Left "azurerm ={", Right only "azurerm {"](https://user-images.githubusercontent.com/13867326/91042524-2b641300-e612-11ea-9f01-9454d12d2dfb.png)

**Comment by DenWin** [comment]
> Smells like a regression from #462 (meant to fix #442 which is distressingly similar to this issue)

Line 452 in terraform.tmGrammar.json to be precise. If one would revert this line back to 2.1.1 everything works fine!

**Comment by jufemaiz** [comment]
Ugh. v2.2.0 really wasn't well road tested.

As per above I've had to rollback to v2.1.1 as the latest release is completely unusable.

```hcl
data "terraform_remote_state" "a_terraform_remote_state" {
  backend = "remote"

  config = {
    organization = "org_name"

    workspaces = {
      name = "how-sweet-are-workspace"
    }
  }
}
```

is but one example of things that broke syntax highlighting.

**Comment by ryderdain** [comment]
@jufemaiz thanks for the tip, for anyone else that needs to downgrade the v2.1.1 package is available via
```
curl -o /path/to/vsix/hashicorp.terraform.2.1.1.vsix https://hashicorp.gallery.vsassets.io/_apis/public/gallery/publisher/hashicorp/extension/terraform/2.1.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
```
Then just uninstall the v2.2.0 version, restart, install the new package, restart VSCode again and works a charm.

**Comment by paultyng** [comment]
We are currently working on a fix for this, but for now the best option is to downgrade. We hope to have a hotfix out as soon as we resolve the issue.
