### ISSUE TITLE
Problems removed?

### ISSUE THREAD

**Issue by acdha** [hashicorp/vscode-terraform#468]
The problems pane no longer populates with Terraform warnings / errors. It looks like there's a vestigal `maxNumberOfProblems` reference in the package metadata but it doesn't appear to be used in the source any more. Is this feature planned to return before #337 lands?

**Comment by radeksimko** [comment]
> Is this feature planned to return before #337 lands?

#337 specifically tracks tflint support, but there are plans to provide a more generic interface and publish diagnostics from Terraform natively too as part of https://github.com/hashicorp/terraform-ls/issues/27

With that in mind are you happy for me to close this issue and track the above one instead?

**Comment by acdha** [comment]
Sure - I couldn’t find confirmation that this was expected behavior and wanted to check.
