### ISSUE TITLE
null_resource trigger breaks highlighting

### ISSUE THREAD

**Issue by okgolove** [hashicorp/vscode-terraform#469]
It is not necessary to use `filemd5` function, for `triggers` block the problem reproduces using any function (i.e. `file`).

```
resource "null_resource" "test" {
  triggers = {
    trigger = filemd5("templates/123")
  }

  provisioner "file" {
    content     = "123"
    destination = "/tmp/private_key"
  }
}
```

![image](https://user-images.githubusercontent.com/36846182/90950937-f499cb80-e45e-11ea-9b76-69f872d0d49a.png)

If I comment `trigger` line it works properly:
![image](https://user-images.githubusercontent.com/36846182/90950946-07ac9b80-e45f-11ea-9ee5-77a77c423f86.png)

**Comment by dgcaron** [comment]
i am seeing the same behaviour, and i think it is related to the use of functions (and or functions in functions).

![image](https://user-images.githubusercontent.com/9764640/91180396-fa561200-e6e7-11ea-8995-6168c8df9b00.png)

and 

![image](https://user-images.githubusercontent.com/9764640/91180475-0c37b500-e6e8-11ea-96bd-a42343cbf2bd.png)

**Comment by paultyng** [comment]
I think this is the same as #466, going to merge them together. We are currently investigating the syntax issues and plan to publish a hotfix once resolved.
