### ISSUE TITLE
Highlighting for a directive highlights also the letter before %{

### ISSUE THREAD

**Issue by DenWin** [hashicorp/vscode-terraform#472]
With this code:
 ```
locals {
  local_var1 = "%{  if "X" != "" }abc%{               else }ABC%{ endif }"

  local_var2 = "A%{ if "X" != "" }${var.input_var}%{  else }ABC%{ endif }"

  local_var3 = "%{  if "X" != "" }A${var.input_var}%{ else }ABC%{ endif }"

  local_var4 = "A${var.input_var}"

  local_var5 = "${var.input_var}%{  if "X" != "" }abc%{ else }ABC%{ endif }${var.input_var}${var.input_var}${var.input_var}"
}
```

not only %{ is highlighted, but any character before it, like e.g. A%{

![image](https://user-images.githubusercontent.com/13867326/91072119-5a41af80-e639-11ea-940b-098bbe3a275b.png)

A similar behavior happens with String interpolations (#471) - for a better issue handling I have opend 2 seperate issues.

I did not want to open 2 more issues, as a similar behavior happens at the end of a curly bracket - see line 5.

**Comment by paultyng** [comment]
I think this is the same as #466, going to merge them together. We are currently investigating the syntax issues and plan to publish a hotfix once resolved.
