### ISSUE TITLE
jsonencode syntax highlighting broken

### ISSUE THREAD

**Issue by danieladams456** [hashicorp/vscode-terraform#474]
### Server Version

```
0.6.1
```

### Terraform Version

```
Terraform v0.12.29
```

### Client Version

```
vscode hashicorp.terraform-2.2.0
```

### Terraform Configuration Files

Syntax highlighting regression:
```hcl
resource "aws_iam_role" "task_role" {
  name = var.task_role_name

  assume_role_policy = jsonencode({
    Version = "2012-10-17",
    Statement = [
      {
        Effect = "Allow",
        Principal = {
          Service = "ecs-tasks.amazonaws.com"
        },
        Action = "sts:AssumeRole"
      }
    ]
  })
}
```
![jsonencode-equals](https://user-images.githubusercontent.com/3953840/91178819-b6491a00-e6b3-11ea-8ca3-214162659057.png)

Working alternative:
```hcl
resource "aws_iam_role" "task_role" {
  name = var.task_role_name

  assume_role_policy = jsonencode({
    Version : "2012-10-17",
    Statement : [
      {
        Effect : "Allow",
        Principal : {
          Service : "ecs-tasks.amazonaws.com"
        },
        Action : "sts:AssumeRole"
      }
    ]
  })
}
```
![jsonencode-colon](https://user-images.githubusercontent.com/3953840/91178815-b517ed00-e6b3-11ea-88d1-64e84657767b.png)

### Log Output

I'm not getting much on the logs
```
2020/08/25 09:03:14 serve_command.go:101: Terraform executions will be logged to /tmp/tf-exec-{{lsPid}}-{{args}}.log (interpolated at the time of execution)
2020/08/25 09:03:14 serve_command.go:137: Starting terraform-ls 0.6.1
2020/08/25 09:03:14 service.go:60: Preparing new session ...
2020/08/25 09:03:14 service.go:77: Worker pool size set to 48
2020/08/25 09:03:14 watcher.go:118: watching for changes ...
2020/08/25 09:03:14 langserver.go:69: Starting server (pid 84280) ...
```

### Expected Behavior

Both syntaxes should be appropriately highlighted?  I tried to follow the documentation at https://www.terraform.io/docs/configuration/functions/jsonencode.html which lead me to believe that each attribute should be delimited by `=`.  The highlighting seems to work better with `:`.  Terraform itself correctly interprets both.  I remember thinking when I originally wrote it that having an equals sign made sense since it's a terraform map but just felt a little weird since it's inside something that says json.  Let me know if an issue/PR should be filed for more explanation in the terraform repo for `jsonencode` documentation.

### Actual Behavior
Syntax highlighting doesn't work with `=` option.  If I remember correctly it used to on an earlier version of the language server.

### Steps to Reproduce
1. Open a folder in vscode
2. Open file task-role.tf from that folder

**Comment by danieladams456** [comment]
That at least explains why I couldn't get any errors from the language server.

**Comment by DenWin** [comment]
@cryptk Your problem can be found in #466.

The issue of the original issue seems to be similar to #466, though not necessarily related. Nonetheless, the fix might work anyway:
Downgrade to v2.1.1

**Comment by paultyng** [comment]
I think this is the same as #466, going to merge them together. We are currently investigating the syntax issues and plan to publish a hotfix once resolved.
