### ISSUE TITLE
Syntax highlighting still broken in more obscure cases

### ISSUE THREAD

**Issue by freakinhippie** [hashicorp/vscode-terraform#481]
I've installed the v2.2.2 fix for the syntax highlighting issue and I've identified an additional case where the syntax highlighting breaks:

```hcl
locals {
  targets_groups = ["one", "two"]
  routes = [
    for i in range(length(local.target_groups)) :
      {
        priority = (i + 15) # this is where it breaks
        test = "something else"
      }
  ]
}
```

This is a follow-on to #479

**Comment by rodrigoechaide** [comment]
After the upgrade to v2.2.2 I am still getting the same issues that I explained in this issue #479. It seems that the fixes did not take into account the case I mentioned in the issue.

**Comment by aeschright** [comment]
Thanks for your patience on this! v2.2.3 has been released with a syntax highlighting update and you should be able to upgrade shortly.
