### ISSUE TITLE
issue with VS code formatting

### ISSUE THREAD

**Issue by deepakkhetwal** [hashicorp/vscode-terraform#491]
[main.txt](https://github.com/hashicorp/vscode-terraform/files/5285109/main.txt)

namespaces              = var.namespaces
1  team-add-admin-objectid = var.team-add-admin-objectid

2  team-add-view-objectid = var.team-add-view-objectid
3  dependsOn              = data.azurerm_kubernetes_cluster.aks-cluster.name

I am having issues with formatting. here are the steps to reproduce
 1) move line 2 to line 1 and save it
 2) give multiple tabs to line 3 after = sign
3) bring back line 2 to it's original position
Output - formatting gets messed up. It looks something like that below - 
 See the attached file

**Comment by radeksimko** [comment]
Hi @deepakkhetwal 
I'm sorry but I don't fully understand the nature of the problem.

The attached file contains a config file which seems formatted as expected according to the latest stable Terraform version (0.14). Can you point out exactly what you expect to be formatted differently in the snippet?

Thanks.

**Comment by radeksimko** [comment]
Closing due to no response for a few months. If the problem persists please open a new issue and attach a config to demonstrate the problem.

Thanks.
