### ISSUE TITLE
Color highlight broken for terragrunt git example

### ISSUE THREAD

**Issue by bedge** [hashicorp/vscode-terraform#492]
As this is the base "getting started" page for terragrunt, I'm using it to illustrate the problem.

I have the terraform plugin version 2.2.3

Version: 1.50.0-insider
Commit: 0c50e1db17168a738235bd7e5c02b9f05ea5df59
Date: 2020-09-30T06:45:45.996Z (1 day ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

For this file: https://github.com/gruntwork-io/terragrunt-infrastructure-live-example, the highlighting is broken for everything after line 42, which seems to be a matter of ignoring a close quote:

![Screen Shot 2020-10-01 at 12 34 02 PM](https://user-images.githubusercontent.com/499317/94854844-65c78980-03e2-11eb-9e76-3fc47222f5b1.png)

If one deletes the close quote on line 42, the highlighting is OK:

![Screen Shot 2020-10-01 at 12 34 54 PM](https://user-images.githubusercontent.com/499317/94854907-842d8500-03e2-11eb-817f-740851c717ab.png)

Well, OK, to be more specific, it's still broken as it's not highlighting the fact that there's a missing close quote.

**Comment by dbanck** [comment]
Thanks for raising this issue.

At some point in the past, the extension falsely claimed to offer syntax highlighting for `.hcl` files, too. As Terraform itself does not use the `.hcl` suffix, we removed this with the release of 2.0.0.

We do have plans to publish a more generic grammar as per #638, and it is likely that this grammar would replace the existing one. However, even then, such grammar would - in the context of this (Terraform) extension - would still be used to highlight Terraform code, not any other HCL (i.e., not Terragrunt).

With that in mind, I'm going to close this PR. Thanks for your understanding.
