### ISSUE TITLE
Command Key is opening Terraform Documentation Website

### ISSUE THREAD

**Issue by dtiziani** [hashicorp/vscode-terraform#494]
Whenever my focus is in one resource, and I just press the Command button (Mac OSX), it opens the resource documentation page.

As nice as it is to open the documentation, this shortcut gets in the way. Is it possible to disable/change it? Didn't find anything available on Keyboard Shortcuts except for Enabling/Disabling the Language Server.

Thanks!

**Comment by zulhfreelancer** [comment]
Hey @dtiziani, how did you disable it? I'm facing the same problem.

**Comment by dtiziani** [comment]
it wasn't this extension, it was another with terraform snippets or something like it. Disable them all and test each one to find the culprit 🤟
