### ISSUE TITLE
couldn't start client language server (Windows)

### ISSUE THREAD

**Issue by sugarraysam** [hashicorp/vscode-terraform#504]
I am working from an airgapped environment so having the extension manage the language server is not a possibility. The only thing I can do is pull down go repositories basically.

I installed the latest version of `terraform-ls` using:

```bash
$ go get github.com/hashicorp/terraform-ls
$ terraform-ls --version
0.0.0-dev
```

The language server starts fine, and is in $GOBIN. ($GOBIN is also in $PATH)

```bash
$ echo $GOBIN # c:\Users\<user>\.go\bin
$ cd $GOBIN
$ terraform-ls.exe serve 
# ...
# langserver.go:69: Starting server (pid <pid>) ...
```

In my project, I initialize stuff with `terraform init`. And here is my vscode settings:

```json
"terraform.languageServer": {
  "trace.server": "verbose",
  "external": true,
  "pathToBinary": "C:\\Users\\<user>\\.go\\bin\\terraform-ls.exe",
  "args": [
    "server"
  ],
},
```

And the errors I get are seen in this screenshot:
![image](https://user-images.githubusercontent.com/20143605/96738765-ac2a5b80-1384-11eb-9c14-24162f0e7d61.png)

**Other information**
- I'm using `git bash` as my shell in vscode.
- I'm getting my go pkgs from [gocenter.io](https://search.gocenter.io/github.com/hashicorp/terraform-ls) through artifactory

```bash
$ terraform version
Terraform version: v0.13.4
+ provider <hostname>/rancher/rancher2 v1.9.0

$ terraform-ls version
0.0.0-dev
# Even if I try pinning the terraform-ls version, it still outputs `0.0.0-dev`
$ go get github.com/hashicorp/terraform-ls@v0.5.4
$ terraform-ls
0.0.0-dev
```

**Questions**
How can I see more verbose output for these errors? I enabled `"trace.server": "verbose"` but have no idea how to use it.

Thanks for your help!

**Comment by aeschright** [comment]
Hi @sugarraysam – Sorry you're running into a problem there! You can see the full language server logs by opening the output panel and choosing the one that says "terraform-ls".

If you need to install the language server manually, the best option is to download it from https://releases.hashicorp.com/terraform-ls/
It doesn't need to be in your path as long as you have that `pathToBinary` setting.

if you want to share the logs from the output panel, we can look into why it might be failing to start.

**Comment by BazzardTCR** [comment]
The last update seems to make it much more stable.

If it stays like this I shall retract review and give it 5 stars.

Cheers

**Comment by wirdatrd** [comment]
I'm running into this problem too.  Here is the output from the terraform-ls panel:
Launching language server: c:\Users\*****\.vscode\extensions\hashicorp.terraform-2.7.0/lsp/terraform-ls serve for folder: file:///c%3A/Users/*****/projects/
[Error - 8:38:18 AM] Starting client failed
Error: spawn EBUSY
	at ChildProcess.spawn (internal/child_process.js:407:11)
	at Object.spawn (child_process.js:557:9)
	at c:\Users\*****\.vscode\extensions\hashicorp.terraform-2.7.0\node_modules\vscode-languageclient\lib\node\main.js:383:40

I have tried uninstalling and upgrading/reinstalling the Terraform extension, uninstalling and upgrading/reinstalling VSCode with no joy.  I've tried starting VSCode with normal perms as well as with elevated Administrator perms.

**Comment by pabloportillo-ti** [comment]
I'm getting the same error :/ 

Launching language server: c:\Users\user\.vscode\extensions\hashicorp.terraform-2.12.1\lsp\terraform-ls serve for folder: file:///c%3A/Users/user/Documents/Terraform/
[Error - 7:50:46 AM] Starting client failed
Error: spawn EBUSY
	at ChildProcess.spawn (internal/child_process.js:403:11)
	at Object.spawn (child_process.js:562:9)
	at c:\Users\user\.vscode\extensions\hashicorp.terraform-2.12.1\node_modules\vscode-languageclient\lib\node\main.js:383:40

**Comment by chudytom** [comment]
I'm getting the same error

Launching language server: c:\Users\tochu\.vscode\extensions\hashicorp.terraform-2.12.1\lsp\terraform-ls serve for folder: file:///<my-repo-folder-name>
[Error - 11:55:27] Starting client failed
Error: spawn EBUSY
	at ChildProcess.spawn (internal/child_process.js:403:11)
	at Object.spawn (child_process.js:562:9)
	at c:\<user>\hashicorp.terraform-2.12.1\node_modules\vscode-languageclient\lib\node\main.js:383:40

**Comment by vitskr** [comment]
I have found workaround for this issue.

In vscode settings file specify path to terraform-ls.exe. Or simply put terraform-ls.exe if it is in your path.

    "terraform.languageServer": {        
        "external": true,
        "pathToBinary": "terraform-ls.exe",

**Comment by radeksimko** [comment]
https://github.com/hashicorp/vscode-terraform/pull/694 (released as part of `2.14.0` recently) fixed a bug where paths with escapable characters (such as spaces, which are common in usernames on Windows) were causing server to fail to start.

With that I'm going to close this issue, but please let us know by opening a new issue if you continue having (any similar or different) issues. The LS installation should work out of the box now on all platforms, _without_ any additional configuration.

@vitskr Can you try removing that settings and confirm that it works now (on `>= 2.14.0`)?

Thanks.

**Comment by Gladskih** [comment]
I get "Couldn't start client Terraform LS" so it's not fixed.
hashicorp.terraform v2.14.0

Version: 1.58.2 (user setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by radeksimko** [comment]
@Gladskih We are tracking that particular issue under https://github.com/hashicorp/vscode-terraform/issues/707 - feel free to subscribe

**Comment by TylerHaigh** [comment]
Hi @radeksimko 
Seems to still be occurring. Any tips? Let me know if you need more details to dig further

```
Launching language server: c:\Users\tyler\.vscode\extensions\hashicorp.terraform-2.14.0\lsp\terraform-ls.exe serve
[Error - 9:11:30 AM] Starting client failed
Error: spawn EBUSY
	at ChildProcess.spawn (internal/child_process.js:403:11)
	at Object.spawn (child_process.js:562:9)
	at c:\Users\tyler\.vscode\extensions\hashicorp.terraform-2.14.0\node_modules\vscode-languageclient\lib\node\main.js:383:40
```

**Comment by herrmadbeef** [comment]
I just started ti face the issue today 
it was working yesterday but something change and I do not know what to do 
vscode versionL 

```
Version: 1.59.1 (user setup)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:56:46.957Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
```

terraform-ls.exe location: 
`C:\Users\<uid>\.vscode\extensions\hashicorp.terraform-2.14.0\lsp`
