### ISSUE TITLE
Saving Files and Formatting taking at least 2 seconds.

### ISSUE THREAD

**Issue by solidnerd** [hashicorp/vscode-terraform#505]
Hey, 

I would like to ask if anyone has the problem like. Currently when I'm saving a file it takes at least 2 seconds to be able further in the file. My first thought was the new language server but this was correct. After checking the logs it seems that `terraform fmt -no-color -` takes 2 seconds.

```sh
2020/10/23 17:05:00 server.go:568: Received 1 new requests
2020/10/23 17:05:00 server.go:174: Processing 1 requests
2020/10/23 17:05:00 server.go:265: Checking request for "textDocument/formatting": {"textDocument":{"uri":"file:///home/solidnerd/tf/testenvironments/global/main.tf"},"options":{"tabSize":2,"insertSpaces":true}}
2020/10/23 17:05:00 rpc_logger.go:29: Incoming request for "textDocument/formatting" (ID 35): {"textDocument":{"uri":"file:///home/solidnerd/tf/testenvironments/global/main.tf"},"options":{"tabSize":2,"insertSpaces":true}}
2020/10/23 17:05:00 root_module_manager.go:149: direct root module lookup succeeded: /home/solidnerd/tf/testenvironments/global
2020/10/23 17:05:00 root_module_manager.go:149: direct root module lookup succeeded: /home/solidnerd/tf/testenvironments/global
2020/10/23 17:05:00 cmd.go:133: [INFO] running Terraform command: /usr/local/bin/terraform fmt -no-color -
2020/10/23 17:05:02 rpc_logger.go:50: Response to "textDocument/formatting" (ID 35): []
2020/10/23 17:05:02 server.go:246: Completed 1 requests [1.596364967s elapsed]
```

Current VS Settings:

```json
    "terraform.languageServer": {
        "external": true,
        "args": [
            "serve"
        ]
    },
        "terraform.indexing": {
            "enabled": true,
            "liveIndexing": true,
            "delay": 500,
            "exclude": [
                ".terraform/**/*",
                "**/.terraform/**/*"
            ]
        },
    
    "[terraform]": {
        "editor.formatOnSave": true
        
    },
```

Versions that I used:
- vscode version: 1.50.1
- vscode-terraform: v2.2.3

**Comment by paultyng** [comment]
Out of curiousity are you using `tfenv`? Or another wrapper for `terraform` execution? We've seen this in those situations due to delays of multiple sub-shells, etc. (here is an upstream `tfenv` issue: https://github.com/tfutils/tfenv/issues/196).

**Comment by solidnerd** [comment]
Hey @paultyng,
yep I used `tfenv` mostly. It came also to my mind but I wasn't sure if it could be and I didn't found any related issues to that.

🙇  for mentioning this and I helped me to understand the root cause.  

From my side, we can gonna close this issue because it's not related directly to the plugin.
