### ISSUE TITLE
Region folding is not working

### ISSUE THREAD

**Issue by ajklotz** [hashicorp/vscode-terraform#515]
I have HashiCorp Terraform extension 2.3.0 and I'm trying to use the [region folding feature that was added some time ago](https://github.com/hashicorp/vscode-terraform/commit/3ae5eea0b2689d2839db75b388d9baadd81d0f55), but it isn't working.

When I add `#region` and `#endregion`, the folding indicator doesn't appear.

#63

**Comment by radeksimko** [comment]
Hi @ajklotz 
Code folding will be (re)implemented as part of the language server and that feature is tracked under https://github.com/hashicorp/terraform-ls/issues/105

I'm therefore going to close this issue, but feel free to subscribe to that one and/or comment if you have any particular questions/requests with regards to that feature beyond what was discussed there.
