### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by FavourOkonta** [hashicorp/vscode-terraform#517]
- Issue Type: `Bug`
- Extension Name: `terraform`
- Extension Version: `2.3.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.51.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by aeschright** [comment]
Hi @FavourOkonta 👋 Can you describe the bug you're seeing?

**Comment by radeksimko** [comment]
Closing the issue as we aren't able to reproduce any particular bug based on the information provided.

Feel free to raise a new one if you continue experiencing issues and attach details such as error message, expected vs actual behaviour, configuration etc.

Thanks.
