### ISSUE TITLE
VSCode language server popup installs latest on clicking x (to close)

### ISSUE THREAD

**Issue by slushnys** [hashicorp/vscode-terraform#519]
Apologies for posting this here, but it triggers me that whenever there's a new language server update of terraform on VSCode and i click on X in order to close the popup, it immediately installs the new language server. Is this something that no other people are experiencing because I haven't seen a related ticket like this or I haven't searched for the right keywords. Thank you for your attention.

**Comment by aeschright** [comment]
Hi @slushnys 👋 Are you saying that you're trying to cancel the language server from installing the update, but it proceeds anyhow? Can you tell me what version of the extension you have installed? Also, is your goal to delay the update, or to not use the language server?

**Comment by radeksimko** [comment]
It would be indeed useful to know what the motivation behind clicking `X` is, as LS being present and up to date is quite essential for the extension.

Regardless though I think the extension should avoid installing LS, or updating it when user clicks `X` - at least that's a behaviour I would expect as a user.

**Comment by slushnys** [comment]
Hello @aeschright  and @radeksimko 

Apologies for the late reply. The motivation may be just not wanting to do it now. I had the change to record a video of that in action:

https://user-images.githubusercontent.com/10806701/107397720-94c7d780-6b07-11eb-9c1e-536c27f20c74.mov
