### ISSUE TITLE
"Unable to install terraform-ls" macOS arm64

### ISSUE THREAD

**Issue by jgardner04** [hashicorp/vscode-terraform#521]
I am getting an error installing terraform-ls. 

OS: macOS 11 arm64 (Apple Silicon)
vscode: 1.52.0-exploration
commit: 88c7381b77df9601914ca914f80c700fee35825a
Electron: 11.0.2
Chrome: 87.0.4280.67
Node.js: 12.18.3
V8: 8.7.220.25-electron.0
OS: Darwin arm64 20.1.0

This may be related to #507 but there is no error message in the Extension Host Log

**Comment by sg-sg-sg** [comment]
I've got the same issue and this message on the console

`Error: Install error: no matching terraform-ls binary for platform	at LanguageServerInstaller.<anonymous> (/Users/sg/.vscode-exploration/extensions/hashicorp.terraform-2.3.0/out/languageServerInstaller.js:115:23)`
