### ISSUE TITLE
Alternative root modules found for <filename> (project), picked: <something>. You can try setting paths to root modules explicitly in settings.

### ISSUE THREAD

**Issue by oliversalzburg** [hashicorp/vscode-terraform#524]
In every single file I open, I get a super annoying notification box telling me about this cryptic problem. I don't know what it's trying to tell me. I see no problem with the document and my workflows are working as expected.

Please remove this message or make it useful. "You can change this in the settings" is extremely unhelpful.

**Comment by iancward** [comment]
I find that after seeing this error a few times, I VS Code then says that the plugin has crashed multiple times and will not be restarted. After that point code formatting doesn't work anymore ("there is no formatter for terraform installed").

**Comment by eatplaysleep** [comment]
> I find that after seeing this error a few times, I VS Code then says that the plugin has crashed multiple times and will not be restarted. After that point code formatting doesn't work anymore ("there is no formatter for terraform installed").

Encountering similar issue -- code formatter hangs for a really long time and sometimes dies. Started happening it seems with the November VS Code update?

**Comment by radeksimko** [comment]
Hi folks,
the issue is not addressed _yet_, but we have a plan for addressing it and I'm just converging all the issues with the same root cause, such as this one, into a single issue: https://github.com/hashicorp/vscode-terraform/issues/569

Thank you for understanding and patience.
