### ISSUE TITLE
Config to disable notifications

### ISSUE THREAD

**Issue by skupjoe** [hashicorp/vscode-terraform#545]
Hello- first off, thank you for the awesome plugin. It has made my life much better.

My implementation with terraform is different and we use [terragrunt](https://terragrunt.gruntwork.io/) as our wrapper- among other customizations. So, I mainly use this plugin for its language syntax highlighting support, as the rest of its features don't directly apply to my setup.

I always receive an error stating `You may need to run terraform init.` when I view my modules/terragrunt.hcl files in VScode.

I'd like to disable these notifications (and, ideally, all notifications) as they are an annoyance to me. Is there a way to do this? Or can you consider this feature request?

Most other notifications produced in VScode that I've seen usually include a tick box to select "Don't notify me about these types of notifications again." and then it updates `settings.json`.

Thank you

**Comment by kchristensen** [comment]
PLEASE consider adding this. We also use Terragrunt and the constant onslaught of popups is super irritating.

**Comment by gzimmers** [comment]
I also am constantly having this problem. I'm aware I haven't initi'd the module, yet it will remind me over and over again when I'm just simply trying to develop some of my TF files.

**Comment by edify42** [comment]
A blanket disable on notifications while you're working on the TF files is possible with the settings on the bottom right (just untick it)
<img width="386" alt="image" src="https://user-images.githubusercontent.com/5309633/108442056-84072680-72aa-11eb-8430-425fe8d13f05.png">

**Comment by spilliams** [comment]
> A blanket disable on notifications while you're working on the TF files is possible with the settings on the bottom right (just untick it)

This doesn't actually solve the problem for me. When I disable this status bar item, I still get the notification when I open a new `.tf` file.

**Comment by radeksimko** [comment]
Hi folks,
the issue is not addressed _yet_, but we have a plan for addressing it and I'm just converging all the issues with the same root cause, such as this one, into a single issue: https://github.com/hashicorp/vscode-terraform/issues/569

Thank you for understanding and patience.
