### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by NileshMoradiya** [hashicorp/vscode-terraform#556]
- Issue Type: `Bug`
- Extension Name: `terraform`
- Extension Version: `2.5.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.53.0`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 15190,
		"activateCallTime": 45,
		"activateResolvedTime": 19013,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "hashicorp.terraform",
				"_lower": "hashicorp.terraform"
			},
			"activationEvent": "onLanguage:terraform"
		}
	},
	"runtimeErrors": []
}
```

**Comment by radeksimko** [comment]
Hi @NileshMoradiya 
Can you provide any more information about what's the nature of the bug you experienced?

**Comment by radeksimko** [comment]
Closing the issue as we aren't able to reproduce any particular bug based on the information provided.

Feel free to raise a new one if you continue experiencing issues and attach details such as error message, expected vs actual behaviour, configuration etc.

Thanks.
