### ISSUE TITLE
Install error: SHA sum ... does not match.

### ISSUE THREAD

**Issue by ghost** [hashicorp/vscode-terraform#561]
VSCode extension fails to enable terraform-ls as part of the install, here is the error message:

> [2021-02-16 10:20:34.397] [exthost] [error] Error: Install error: SHA sum for terraform-ls_0.13.0_windows_amd64.zip does not match.
> (expected: 5620135de9c0a89edc24313f575deda52dda4cf093cef5c36914aa5bedf2154e calculated: 76539cc0683bc66451f5d5210305375119cb582e66bedf741e7f51f82521b0df)
> 	at Release.<anonymous> (c:\Users\xxxxx\.vscode\extensions\hashicorp.terraform-2.6.0\node_modules\@hashicorp\js-releases\out\index.js:90:23)
> 	at Generator.next (<anonymous>)
> 	at fulfilled (c:\Users\xxxxx\.vscode\extensions\hashicorp.terraform-2.6.0\node_modules\@hashicorp\js-releases\out\index.js:5:58)
> 	at processTicksAndRejections (internal/process/task_queues.js:97:5) terraform.enableLanguageServer

> [2021-02-16 10:20:34.399] [exthost] [error] Error: Running the contributed command: 'terraform.enableLanguageServer' failed.
> 	at b._executeContributedCommand (c:\Users\xxxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:88571)
> 	at processTicksAndRejections (internal/process/task_queues.js:97:5)

Any idea how to overcome this issue?

**Comment by aeschright** [comment]
Hi @mubarak-j – I'm sorry you're running into this! Does it still happen if you try again now? We pushed a new version of `terraform-ls` so I just want to be sure it's a problem with the download process and not the particular binary.

**Comment by mubarak-j** [comment]
Hi @aeschright, thanks for the response. I no longer see the installation error after re-installing the extension. 
I was curious, does the extension make sure that `terraform-ls` is added to PATH? I had to do that manually.

**Comment by firstPole** [comment]
@aeschright  I am still getting this issue as like below,

Unable to install terraform-ls: Install error: SHA sum for terraform-ls_0.15.0_windows_amd64.zip does not match. (expected: 16eb3e3fa6c1697c382f9217ef4de71ee11e8203f958c1e902864863c2578815 calculated: f2dd88e2fb4a4973e848484fd863b2dec656f69240f89b268debf1d1f111c1f5)

**Comment by aeschright** [comment]
I have one guess about why this might happen – do you typically have multiple windows or workspaces open? It's possible that the installer is stepping on itself by trying to run multiple times.

**Comment by aeschright** [comment]
If you're going to install terraform-ls on your own, you'll need to put the full path for it in the settings. By default, the extension does that part for you when it handles the install. Installing it yourself will prevent this error, but then you're stuck checking for upgrades.

**Comment by radeksimko** [comment]
As of [2.20.0](https://github.com/hashicorp/vscode-terraform/blob/main/CHANGELOG.md#2200-2022-03-01) we started embedding the language server in the extension, which means that we no longer install it (except once at release time in our CI), as a result you should no longer experience this error, so I'm going to close this.
