### ISSUE TITLE
Vscode asking about to install terraform

### ISSUE THREAD

**Issue by zipper-krew** [hashicorp/vscode-terraform#568]
<img width="1488" alt="image" src="https://user-images.githubusercontent.com/68272278/109066872-6399fa80-76f6-11eb-85f8-7af571310d05.png">

Vscode is always asking about to install terraform, but terraform and terraform-ls already installed. See screen above

**Comment by radeksimko** [comment]
If you have Terraform CLI installed, I would assume this just means it's not available in the `$PATH` passed down to VS Code.
Note that on macOS at least the environment of an app (launched from Finder/Dock/Spotlight or elsewhere outside of your terminal) may differ from the environment available to your terminal.

Can you try following some of the debugging steps I mentioned in this comment? https://github.com/hashicorp/vscode-terraform/issues/552#issuecomment-775037784

**Comment by zipper-krew** [comment]
Yes, I've Terraform CLI installed via brew manager

 which terraform
/usr/local/bin/terraform

So as you can see it's on well known OS PATH

launchctl getenv PATH - ended with 0 code but empty result


echo $PATH
/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/Users/aleksey/bin:/usr/local/opt/mysql-client/bin/

**Comment by radeksimko** [comment]
@zipper-krew Can you try relaunching VS Code from the terminal so that it inherits the environment of the active shell?

e.g.

```sh
code ./directory
```

**Comment by zipper-krew** [comment]
@radeksimko it works fine if i run from terminal as `open 'Visual Studio Code.app'` but still getting alert if start from dock/finder. Thanks

**Comment by zipper-krew** [comment]
Issue fixed by adding PATH to `launchctl setenv PATH`
Now it's same as in terminal and no alerts in app. Thank you.
