### ISSUE TITLE
Commands are sent without verifying server capabilities

### ISSUE THREAD

**Issue by aeschright** [hashicorp/vscode-terraform#575]
## Background

The extension is sending workspace/executeCommand requests to the language server that it may not be able to respond to if the server version or an alternate binary in use doesn't support that. In order to provide better information to the user, the server capabilities should be verified.

Server provides an array of all supported commands via `Capabilities.ExecuteCommandProvider.Commands`:
https://github.com/hashicorp/terraform-ls/blob/778fb9b69e22741ad1f258a7241ee8f04ab0caa1/internal/langserver/handlers/initialize.go#L93-L98

## Proposal

 - [x] https://github.com/hashicorp/vscode-terraform/pull/1075
 - [ ] Check whether a command is supported as part of https://github.com/hashicorp/vscode-terraform/blob/ad5104eba5f9df9ffb4298022b5f21ecb978c701/src/extension.ts#L339-L345
   - [ ] return appropriate error if it's not supported

**Comment by radeksimko** [comment]
From what I can tell this is done for all the commands which are executed on the background:

https://github.com/hashicorp/vscode-terraform/blob/ad5104eba5f9df9ffb4298022b5f21ecb978c701/src/features/moduleCalls.ts#L20-L24

https://github.com/hashicorp/vscode-terraform/blob/ad5104eba5f9df9ffb4298022b5f21ecb978c701/src/features/moduleProviders.ts#L20-L25

https://github.com/hashicorp/vscode-terraform/blob/ad5104eba5f9df9ffb4298022b5f21ecb978c701/src/features/showReferences.ts#L37-L40

but we still don't check capabilities for the commands which are executed manually, i.e.

 - apply
 - init
 - plan
 - validate

https://github.com/hashicorp/vscode-terraform/blob/ad5104eba5f9df9ffb4298022b5f21ecb978c701/src/extension.ts#L339-L345

**Comment by radeksimko** [comment]
This was addressed as part of https://github.com/hashicorp/vscode-terraform/pull/1185

specifically in

https://github.com/hashicorp/vscode-terraform/blob/a9e93f5dea9e9f1ac25feed7355f8bb9d0475cd4/src/terraform.ts#L219-L222

https://github.com/hashicorp/vscode-terraform/blob/a9e93f5dea9e9f1ac25feed7355f8bb9d0475cd4/src/utils/clientHelpers.ts#L59-L65
