### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by upenderadepu** [hashicorp/vscode-terraform#581]
- Issue Type: `Bug`
- Extension Name: `terraform`
- Extension Version: `2.8.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by radeksimko** [comment]
Hi @upenderadepu 
Unfortunately it looks like you have missed this part:

> ⚠️ We have written the needed data into your clipboard. Please paste! ⚠️

and there isn't much to act upon from the data above, so I'm going to close this issue.

Feel free to comment or open a new issue if you have additional info or can describe the symptoms of the problem in any other way such that we can investigate.
