### ISSUE TITLE
How to prevent annoying recurring message: `No schema found for ...`

### ISSUE THREAD

**Issue by MagnusBrzenk** [hashicorp/vscode-terraform#585]
Just about **every time** I open a `.tf` file in VSCode I get this message, which gets super annoying very quickly: 

```
No schema found for "...". Functionality may be limited. You may need to run terraform init.
```

I am not an advanced TF user, and don't know why this message is always prompted. I have a dir full of nested modules and I do not want every single module dir to be polluted with a `.terraform` dir and `.terraform.lock.hcl` file. I could perhaps tolerate this message showing up *once*, and having `terraform init` run in the root dir, but I think it's really crude to have to run it in **every** single dir.

My questions/requests in summary are:

1. What does `No schema found for XXX` **mean**?
2. How can I prevent this message getting presented to me upon opening a .tf file **every single** time?

**Comment by iJebus** [comment]
See #569.

**Comment by radeksimko** [comment]
Hi @MagnusBrzenk 
As @iJebus mentioned there is #569 tracking this particular problem. That may also answer your questions.

I'm going to close this one, but feel free to subscribe to that pinned issue.
