### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by binsta** [hashicorp/vscode-terraform#586]
- Issue Type: `Performance`
- Extension Name: `terraform`
- Extension Version: `2.8.2`
- OS Version: `Windows_NT ia32 10.0.19042`
- VSCode version: `1.54.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\binst\AppData\Local\Temp\hashicorp.terraform-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by radeksimko** [comment]
Hi @binsta 
Unfortunately it looks like you forgot to attach the cpuprofile.txt as the issue template suggests.

With that in mind there is nothing we can do with regards to debugging and investigating without that file or further details, so I'm going to close this issue. Feel free to comment or open a new one if you do have that file or more details (or ideally both).

Thanks!

**Comment by binsta** [comment]
Hi @radeksimko 
Sorry for the delay, I have attached the hashicorp.terraform-unresponsive.cpuprofile.txt. Please fix you have done great work keep it up
[hashicorp.terraform-unresponsive.cpuprofile.txt](https://github.com/hashicorp/vscode-terraform/files/6141893/hashicorp.terraform-unresponsive.cpuprofile.txt)

**Comment by radeksimko** [comment]
Thank you for providing the file.

I can't see anything unusual, but also I don't have much experience reading these JS profiles.

Before we go further, could you check what's the version of LS being used by looking at the very top of the relevant Output panel?
![Screenshot 2021-03-15 at 14 17 41](https://user-images.githubusercontent.com/287584/111167647-3d4ed880-8599-11eb-84a0-53f1742b7a53.png)

If that's lower than 0.15.0 - can you try to upgrade, please?
