### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by batmanhit** [hashicorp/vscode-terraform#590]
- Issue Type: `Performance`
- Extension Name: `terraform`
- Extension Version: `2.8.3`
- OS Version: `Darwin x64 20.3.0`
- VSCode version: `1.54.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/6m/r0382sc95mjbwwzpg8_b4lx00000gn/T/hashicorp.terraform-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by radeksimko** [comment]
Hi @batmanhit 
Unfortunately it looks like you forgot to attach the cpuprofile.txt as the issue template suggests.

With that in mind there is nothing we can do with regards to debugging and investigating without that file or further details, so I'm going to close this issue. Feel free to comment or open a new one if you do have that file or more details (or ideally both).

Thanks!
