### ISSUE TITLE
Error when installing Terraform 2.9 extension

### ISSUE THREAD

**Issue by fitchtech** [hashicorp/vscode-terraform#596]
ENOENT: no such file or directory, mkdir 'c:\Users\cfitch\.vscode\extensions\.hashicorp.terraform-2.9.0\file:\Users\aeschright\code\vscode-terraform\lsp'

@aeschright seems to be referencing your user path somehow

**Comment by fitchtech** [comment]
I'm able to install terraform-2.8.3.vsix directly from the file but get the above error when using terraform-2.9.0.vsix

**Comment by aeschright** [comment]
Weird! I'm looking into it and I'll have a patch ASAP.

**Comment by avoidik** [comment]
as a workaround download vsix, open it as zip, remove directory named "file:", install modified vsix

**Comment by aeschright** [comment]
If anyone wants to give it a test directly, here's the new package https://github.com/hashicorp/vscode-terraform/releases/tag/v2.9.1

I'll get this on the marketplace and maybe it's also a good day to move the builds to CI 😅

**Comment by aeschright** [comment]
v2.9.1 is in the marketplace and it looks like things are running smoothly again, so I'm going to close this. Thanks for the reports, and please file another issue if you encounter any other surprises 💖
