### ISSUE TITLE
list/map variable type syntax highlighting

### ISSUE THREAD

**Issue by frittsy** [hashicorp/vscode-terraform#610]
While I know the `list` and `map` functions were officially removed in v0.15.0, they are still valid types for variables and should not be highlighted as red, as shown below. I believe this was broken in #604.
<img width="225" alt="Screen Shot 2021-04-22 at 8 02 55 AM" src="https://user-images.githubusercontent.com/4554717/115711529-9d2b6280-a341-11eb-9c49-807ccfc093c0.png">

**Comment by frittsy** [comment]
I can take a stab at fixing this, but not sure if it would be better to simply add these as additional types to `terraform_type_keywords`, or if there needs to be something more akin to `structural_types` but for all the collection types.

**Comment by dbanck** [comment]
Thanks for the report. I'm able to reproduce this behavior.

`list()` is always highlighted as `invalid.deprecated.terraform` even if it's a valid type in `variable` blocks.
<img width="505" alt="CleanShot 2022-02-01 at 15 05 39@2x" src="https://user-images.githubusercontent.com/45985/151983691-ffb73885-d51c-42c6-ab92-f307e4d3b01d.png">

The red color should only be applied in a function-call context. 
<img width="552" alt="CleanShot 2022-02-01 at 15 06 29@2x" src="https://user-images.githubusercontent.com/45985/151983688-de342b83-664d-4393-8cbe-c435456f1796.png">
