### ISSUE TITLE
Prevent language server installer from overlapping runs

### ISSUE THREAD

**Issue by aeschright** [hashicorp/vscode-terraform#614]
Currently, if a user has more than one workspace open in VSCode, it's possible that the language server installer will attempt to run the install process once per workspace. This can produce the kinds of errors seen in #561 as well as other failures since one process may try to delete the zipfile while another is reading it.

The best option would be to put a timestamp or uid on the zipfile so the installer only tries to access the one it downloaded. It may also be useful to do something like a lockfile when the install is happening, since there's no reason to allow installs to overlap.

**Comment by radeksimko** [comment]
We no longer install the language server on activation - it is now embedded since [2.20.0](https://github.com/hashicorp/vscode-terraform/blob/main/CHANGELOG.md#2200-2022-03-01), therefore this is no longer an issue.
