### ISSUE TITLE
There is no formatter for 'terraform' files installed.

### ISSUE THREAD

**Issue by Jeiwan** [hashicorp/vscode-terraform#617]
Formatting of .tf files stopped working, yesterday everything was fine. Re-installing the extension and restarting VSCode doesn't help.

**Comment by Jeiwan** [comment]
Installing older versions of the extension doesn't help. VSCode suggests this extensions as a formatter, but obviously something has gone wrong.

**Comment by Jeiwan** [comment]
Auto-completion also stopped working. No errors or warnings though.

**Comment by haflidif** [comment]
This also happened to me after upgrading to the new language server: v.0.16.0  it keeps crashing, and auto-completion stopped working, got frustrated and reverted back to v.0.15.0 that is now working like a charm.

Also to point out i just downloaded version v.0.15.0 and configured terraform.languageServer in the settings.json file to use those binaries.

`"terraform.languageServer": {
        "external": true,
        "pathToBinary": "c:\\tools\\terraform-ls.exe",
        "args": [
            "serve",
        ],
        "maxNumberOfProblems": 100,
        "trace.server": "off"
    }`

**Comment by radeksimko** [comment]
Hi @Jeiwan and @haflidif
Can you provide some more details? I'd like to get to the bottom of this. For example can you open the Output pane and see if there's any output from the language server? Not all errors are necessarily sign of a bug, but if you can scan for any potentially sensitive data, remove that and share it via [gist](https://gist.github.com/) that would be great.

![Screenshot 2021-04-30 at 07 10 30](https://user-images.githubusercontent.com/287584/116655555-37fbf080-a983-11eb-9af4-699aab6a8959.png)

Can you also check what version of the extension you have installed currently?
![Screenshot 2021-04-30 at 07 17 09](https://user-images.githubusercontent.com/287584/116656174-25ce8200-a984-11eb-9587-1ab5b71b3f14.png)

**Comment by haflidif** [comment]
##619

**Comment by Jeiwan** [comment]
I've managed to fix it. I needed to install and enable the language server by pressing Cmd+Shift+P and executing "Terraform: Enable Language Server". Apparently, it was disabled by default. Not sure if it was my configuration that affected that.

My extension version is 2.10.1 and there are no other Terraform extensions installed. Output log was empty.
