### ISSUE TITLE
Allow pinning language server to a version

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/vscode-terraform#628]
Ideally users should not have any strong reasons to be pinning LS to any particular older version. This assumes that latest version always provides the latest (security) patches and stability.

However sometimes it is useful, esp. when debugging to be able to pin to an older version, so that the user can verify that a bug they're experiencing is only present in particular versions.

I imagine this could be exposed to the user in the form of a field in settings, say "terraform-ls version" which could be either a selectbox of last N versions, or text box accepting version constraints such as `~> 0.12`. I don't have any strong opinion on the UI side of things, also I'm not sure what's realistic within the VS Code API constraints.

**Comment by jpogran** [comment]
This was implemented in #656
