### ISSUE TITLE
Meta: use this extension outside VSCode

### ISSUE THREAD

**Issue by danieldreier** [hashicorp/vscode-terraform#637]
This is a thematic tracking issue to describe the broader set of requests around using this extension outside of VSCode, for example in Theia. The purpose of this issue is to consolidate tracking of those requests; work will need to be planned more concretely before implementation starts.

**Comment by danieldreier** [comment]
https://github.com/hashicorp/vscode-terraform/issues/379 is an instance of this

**Comment by radeksimko** [comment]
Addressed as part of #1064
