### ISSUE TITLE
meta: Dedicated HCL VS Code extension

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/vscode-terraform#639]
Depends on https://github.com/hashicorp/vscode-terraform/issues/638

--- 

## Problem Statement

Many users regularly edit files which are not Terraform configuration and which wouldn't make sense to support in **Terraform** extension or language server. For example:

 - `terragrunt.hcl` https://github.com/hashicorp/vscode-terraform/issues/239
 - `.tflint.hcl` https://github.com/hashicorp/vscode-terraform/issues/303
 - `jobspec.nomad` - [Nomad jobspec](https://www.nomadproject.io/docs/job-specification)
 - `template.pkr.hcl` - [Packer build template](https://www.packer.io/docs/templates/hcl_templates)
 - `waypoint.hcl` - [Waypoint configuration](https://www.waypointproject.io/docs/waypoint-hcl)

These users naturally want to have a decent experience while editing such files, but we don't provide it for them. They use additional community extensions, or treat the above files as "Terraform syntax". The experience resulting from such workarounds is suboptimal.

 - Some community extensions, such as [`wholroyd.HCL`](https://marketplace.visualstudio.com/items?itemName=wholroyd.HCL) claim not only `*.hcl` but also `.tf` or `.tfvars` which naturally overlap with our Terraform extension and VS Code itself doesn't always handle such conflicts well. Frozen UI was seen as one possible symptom of such conflict.
 - Terraform extension isn't prepared to deal with just "any HCL" from any perspective at this point - the syntax grammar used for highlighting is Terraform-specific and language server will error out if it can't parse the configuration, because it's not Terraform configuration and will not provide any completion, hover, or any other functionality.

## Technical Details

Languages based on HCL look very similar, but they all often differ e.g. in block names, attribute names, data types, function names etc. (often defined by schema). These are all important differences that cause described problems when users try to treat them as equal.

## User Impact

Users have asked us for HCL support in the following issues:

 - https://github.com/hashicorp/vscode-terraform/issues/303
 - https://github.com/hashicorp/vscode-terraform/issues/239
 - https://github.com/hashicorp/vscode-terraform/pull/615
 - https://github.com/hashicorp/vscode-terraform/issues/602
 - https://github.com/hashicorp/vscode-terraform/pull/225

## Expected User Experience

Users editing `*.hcl` files or files which were explicitly marked as `HCL` syntax will be provided with a dedicated `HashiCorp.HCL` extension with minimal functionality as outlined below.

### Syntax Highlighting

Similar to the Terraform extension, HCL configuration will be highlighted, but won't expect any particular block type names, function names or any product-specific syntax.

### Symbol Navigation

User is provided with symbols outline, e.g.

![Screenshot 2021-05-18 at 17 07 11](https://user-images.githubusercontent.com/287584/118686004-83275780-b7fb-11eb-8846-b3fd885010f5.png)

and navigate to any particular symbol in the tree, e.g. via command palette

![Screenshot 2021-05-18 at 17 08 13](https://user-images.githubusercontent.com/287584/118686152-a81bca80-b7fb-11eb-9983-ea873a862c72.png)

### Folding Ranges

User is able to fold parts of their configuration, e.g. via `>` button on the left side

![Screenshot 2021-05-18 at 17 08 52](https://user-images.githubusercontent.com/287584/118686336-cf729780-b7fb-11eb-865f-bc9c7d52fcbb.png)

### Formatting

User is able to format their configuration via command palette

![Screenshot 2021-05-18 at 17 10 13](https://user-images.githubusercontent.com/287584/118686497-f3ce7400-b7fb-11eb-97fd-7584ed91ac09.png)

and automatically on-save, as long as they have the following set in their VS Code configuration:

```json
    "[hcl]": {
        "editor.formatOnSave": true
    },
```

## Proposal

 - Create a new language server, e.g. at `hashicorp/hcl-ls` which implements
    - symbol navigation
    - folding ranges
    - formatting - this can basically leverage internal mechanics of [`hclfmt`](https://github.com/hashicorp/hcl/tree/main/cmd/hclfmt)
 - Create a new extension (e.g. `HashiCorp.HCL`) which can rely on `hcl-ls` in the same way that our current `HashiCorp.Terraform` extension relies on `terraform-ls` (automatic installation & updates)
 - Build in the generic HCL grammar created as part of https://github.com/hashicorp/vscode-terraform/issues/638

**Comment by oinkbark** [comment]
I currently use this outdated extension/repo: https://github.com/wholroyd/vscode-hcl. I wholeheartedly agree that a dedicated extension for HCL is needed, as I work on Consul, Vault, Nomad, and Packer configurations beyond just Terraform.

**Comment by Manouchehri** [comment]
@oinkbark Try this: https://github.com/tprasadtp/vscode-hcl2

**Comment by radeksimko** [comment]
Hi folks,
We have recently taken over and updated the mentioned [HCL extension](https://marketplace.visualstudio.com/items?itemName=HashiCorp.HCL), as [announced via blogpost](https://www.hashicorp.com/blog/announcing-the-hcl-extension-for-visual-studio-code-0-1). The latest update also includes support for HCL2.

That extension can be used to highlight any HCL files, as long as these use `*.hcl` naming convention - including Packer, Terragrunt, tflint or Waypoint.

Formatting support is tracked under https://github.com/hashicorp/vscode-hcl/issues/98. For folding ranges - these are already provided in some basic form via the TextMate grammar as part of the extension and helpful symbol navigation requires schema - therefore would be quite difficult to provide for any HCL file without knowing the schema, so we don't currently plan to provide that as part of an HCL extension.

We welcome any feedback on the extension under https://github.com/hashicorp/vscode-hcl/issues
