### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by charlesanil** [hashicorp/vscode-terraform#657]
- Issue Type: `Bug`
- Extension Name: `terraform`
- Extension Version: `2.10.2`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.55.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 15960,
		"activateCallTime": 82,
		"activateResolvedTime": 19850,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "hashicorp.terraform",
				"_lower": "hashicorp.terraform"
			},
			"activationEvent": "onLanguage:terraform"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "write after end"
		}
	]
}
```

**Comment by radeksimko** [comment]
Hi @charlesanil 
Can you provide any more details about what went wrong or what doesn't work as expected?

Thanks.

**Comment by radeksimko** [comment]
Closing the issue as we aren't able to reproduce any particular bug based on the information provided.

Feel free to raise a new one if you continue experiencing issues and attach details such as error message, expected vs actual behaviour, configuration etc.

Thanks.
