### ISSUE TITLE
Crashing language server (terraform-ls)

### ISSUE THREAD

**Issue by AJCandfield** [hashicorp/vscode-terraform#665]
After an update to the latest version (v2.12.1) my Terraform language server does not work anymore. As a consequence, I do not have auto-completion like I used to just over a week ago. Also, the following error message appears:
```
The Language Server: 
file:///<path-pointing-to-my-terraform-project> server crashed 5 times in the last 3 minutes. 
The server will not be restarted.
```
These are the VSCode settings I specified in the `settings.json` file:
```
...
"terraform.languageServer": {
        "external": true,
        "pathToBinary": "C:\\Portable\\terraform\\terraform.exe",
        "args": [
            "serve"
        ],
        "maxNumberOfProblems": 100,
        "trace.server": "off"
    },
...
```
Is it normal that the path displayed in the error message and the one I set in the `settings.json` file are different?
Can you help me troubleshoot the error?

I'm using a Win10 x64 workstation.

**Comment by radeksimko** [comment]
Hi @AJCandfield 
Thank you for the report!

I noticed you don't use the auto-install/update feature (i.e. you have specified `pathToBinary` in your settings) - is there a particular reason for that?

Either way can you please provide us the log from here?

![Screenshot 2021-06-18 at 10 02 27](https://user-images.githubusercontent.com/287584/122536363-59d93180-d01c-11eb-8fe7-1424265b6f8f.png)

I'm specifically interested in the first few lines, which should contain the LS version used and then the whole stack trace after any line which begins with `panic:`.

If you can also provide the configuration which is triggering this crash, so that I can reproduce it, that would be amazing.

**Comment by AJCandfield** [comment]
Hi, thanks for the quick help 😃 
This is the output you asked me:
```
Launching language server: C:\Portable\terraform\terraform.exe serve for folder: file:///<path-pointing-to-my-terraform-project>
Terraform has no command named "serve".

To see all of Terraform's top-level commands, run:
  terraform -help

[Info  - 09:48:35] Connection to server got closed. Server will restart.
Terraform has no command named "serve".

To see all of Terraform's top-level commands, run:
  terraform -help

[Info  - 09:48:37] Connection to server got closed. Server will restart.
Terraform has no command named "serve".

To see all of Terraform's top-level commands, run:
  terraform -help

[Info  - 09:48:38] Connection to server got closed. Server will restart.
Terraform has no command named "serve".

To see all of Terraform's top-level commands, run:
  terraform -help

[Info  - 09:48:40] Connection to server got closed. Server will restart.
Terraform has no command named "serve".

To see all of Terraform's top-level commands, run:
  terraform -help

[Error - 09:48:41] Connection to server got closed. Server will not be restarted.
```
I'm starting to think that `terraform.exe` and `terraform-ls` are two different things. If that's the case, I apologize for my ignorance.

I tried to re-install the extension without specifying the path but I get this error:
```
Couldn't start client Language Server: 
file:///<path-pointing-to-my-terraform-project>
```
and no output like before.

About the configuration info you asked, the crash happens in any Terraform project every time I start VSCode.
I'm using a portable VSCode instance located at a custom path `C:\Portable\vscode`.

**Comment by radeksimko** [comment]
> I'm starting to think that terraform.exe and terraform-ls are two different things.

Yes - these are two different things. We do not bundle the language server with Terraform itself, at least not at this point.

No need to apologize - I'm just curious what motived you to set this config option? The extension should just install the LS automatically after first activation and it should not need any manual configuration at all.

Is there any piece of documentation that needs updating, or adding somewhere?

> I tried to re-install the extension without specifying the path but I get this error:

I'm assuming that's the (unfortunately vague) message from a popup. I haven't quite figured out where that one comes from and how to make it more useful, but I've seen it before.

I wonder if this could be related to the way you run VS Code or the network you're on?

Generally the extension needs to:

 - be able to reach `releases.hashicorp.com` - if you're behind any kind of restrictive corporate firewall that blocks requests to that domain then I imagine that might confuse the updater.
 - be able to create a new `lsp` directory within the extension dir (i.e. `$HOME/.vscode/extensions/hashicorp.terraform-2.12.1`) and be able to write files into that directory

**Comment by AJCandfield** [comment]
Success! ✅ 
> I wonder if this could be related to the way you run VS Code or the **_network you're on_**?

I am in fact working behind a proxy server! I disconnected from the company network and tried reinstalling the extension with my home gateway and it worked!

Something I noticed is that, when installing the extension behind the proxy, everything was downloaded in the `$HOME/.vscode/extensions/hashicorp.terraform-2.12.1` folder except for the `lsp` folder which contains `terraform-ls.exe`. I thought the installation was successful but actually the most important piece was missing!

Maybe another solution could be specifying VSCode proxy settings:
![image](https://user-images.githubusercontent.com/40602303/122545328-01ab2b00-d02e-11eb-8594-d62e34583e6b.png)
But I haven't tested this yet.

Thanks a lot Radek 😄

**Comment by AJCandfield** [comment]
>Is there any piece of documentation that needs updating, or adding somewhere?

You could add:
* `terraform-ls` is its own thing, separate from `terraform` binary
* A warning about installations behind proxy servers. 

Thanks again!

**Comment by radeksimko** [comment]
I have created https://github.com/hashicorp/vscode-terraform/issues/667 to address the proxy related issues.

> terraform-ls is its own thing, separate from terraform binary

The field is under `terraform.languageServer` section and the description already mentions this, so I'm not sure what more can be done in this area? 🤔 

https://github.com/hashicorp/vscode-terraform/blob/ab57089375e2c5f989bf854ca47e45335e3ac1d6/package.json#L101
