### ISSUE TITLE
Go to (local) module implementation from `source`

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/vscode-terraform#669]
## Problem Statement

When users edit _local_ modules they might benefit from being able to jump between those modules from a place where they're called to the source code.

For example in a configuration like this

```hcl
module "example" {
  source = "./foo-submodule" 
}
```

It should be easy to open `./foo-submodule` in the editor.

## User Impact

Any users which use _local_ modules would benefit.

### Go To Definition

https://code.visualstudio.com/docs/editor/editingevolved#_go-to-definition

![ctrlhover](https://user-images.githubusercontent.com/287584/122579107-7c833e80-d04c-11eb-9cdd-920abe11d15b.png)

## Proposal

 - https://github.com/hashicorp/terraform-ls/issues/558

## Blocking Question

Explore the UX implications of "Go To Declaration" also and see if that can/should be implemented too.

**Comment by dbanck** [comment]
Closed via https://github.com/hashicorp/terraform-ls/issues/558

**Comment by jpogran** [comment]
Closing as 0.27.0 is being released.
