### ISSUE TITLE
terraform-ls module fails to notify textDocument/hover - states file not found

### ISSUE THREAD

**Issue by gyoza** [hashicorp/vscode-terraform#703]
```
2021/07/27 09:45:19 server.go:266: Checking request for "textDocument/hover": {"textDocument":{"uri":"file:///Users/xx/_repos/xx/terraform/stg/gcp/env/terragrunt.hcl"},"position":{"line":41,"character":88}}
2021/07/27 09:45:19 rpc_logger.go:29: Incoming request for "textDocument/hover" (ID 20): {"textDocument":{"uri":"file:///Users/xx/_repos/xx/terraform/stg/gcp/env/terragrunt.hcl"},"position":{"line":41,"character":88}}
2021/07/27 09:45:19 hover.go:53: Looking for hover data at "terragrunt.hcl" -> hcl.Pos{Line:42, Column:89, Byte:3333}
2021/07/27 09:45:19 hover.go:55: received hover data: (*lang.HoverData)(nil)
2021/07/27 09:45:19 rpc_logger.go:45: Error for "textDocument/hover" (ID 20): [-32098] terragrunt.hcl: file not found
2021/07/27 09:45:19 server.go:247: Completed 1 requests [1.292906ms elapsed]
[Error - 9:45:19 AM] Request textDocument/hover failed.
  Message: terragrunt.hcl: file not found
  Code: -32098 
2021/07/27 09:45:20 server.go:591: Received 1 new requests
2021/07/27 09:45:20 server.go:175: Processing 1 requests
```

os:

```
Version: 1.58.2 (Universal)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:09:06.581Z (1 wk ago)
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.6.0
```

Not sure what to do at this point.. No errors are displayed in the UI at all. 

New to VScode, came from sublime text..

**Comment by radeksimko** [comment]
Hi @gyoza 
Thank you for the report.
I am surprised that `terragrunt.hcl` is being sent to the language server in the first place. This extension should not recognize that file by default.

That said we do plan to create a dedicated (separate) extension for these files https://github.com/hashicorp/vscode-terraform/issues/639 to provide at least basic functionality that isn't related to Terraform.

Did you manually overwrite detected language to Terraform?

**Comment by gyoza** [comment]
I figured it would work just the same as tflint.. I have vscode to run all `ext:*.hcl` files through terraform extension.

**Comment by radeksimko** [comment]
As the `Technical Details` paragraph mentions in https://github.com/hashicorp/vscode-terraform/issues/639 HCL config files are similar, but not the same. The only functionality that this extension may offer which happens to be relevant in that context is syntax highlighting - and even that is actually by accident as the grammar is Terraform-specific as you can see e.g. from these lines:
https://github.com/hashicorp/vscode-terraform/blob/b5c8b6c7855c98918b6fe4d2fea0f11d1c438599/syntaxes/terraform.tmGrammar.json#L112-L113

With that in mind I would discourage sending anything other that (default) `*.tf` and `*.tfvars` files to this extension. These are the only formats this extension can handle and will handle in the foreseeable future.

We do plan to create and maintain a more generic HCL grammar for highlighting any HCL - as mentioned in https://github.com/hashicorp/vscode-terraform/issues/638 - this would most likely be then used by this extension and also be part of the mentioned HCL extension. However it requires more context and complexity to provide any other functionality beyond highlighting - such as hover or completion.

It is likely that we'll address the basic needs of Terragrunt users via a generic HCL extension and leave any more complex Terragrunt-specific functionality for any Terragrunt extension & LS which the community wishes to develop. Similar logic could be applied to any other HCL-based languages used by Packer, Nomad etc. That said no decisions were made in this area yet.

I should mention that there is also https://github.com/hashicorp/vscode-terraform/issues/239 tracking Terragrunt request.

**Comment by radeksimko** [comment]
I'm going to close this issue as it is a combination of different issues which are already being tracked elsewhere. You are free to subscribe to any of the issues I linked to above however.
