### ISSUE TITLE
Format on save not working anymore

### ISSUE THREAD

**Issue by audiolomb** [hashicorp/vscode-terraform#705]
settings.json:

```
    "terraform.languageServer": {
        "external": true,
        "pathToBinary": "",
        "args": [
            "serve"
        ],
        "maxNumberOfProblems": 100,
        "trace.server": "off"
    },
    "[terraform]": {
        "editor.defaultFormatter": "hashicorp.terraform",
        "editor.formatOnSave": true
    },
```

Version installed is 2.14.0 with latest language server

Format on save does not work anymore.

**Comment by radeksimko** [comment]
Hi @audiolomb 
Thank you for the report.

That line `"pathToBinary": "",` is redundant and can be removed but admittedly it shouldn't affect anything and shouldn't cause this problem (it is just empty string which should be ignored).

I'd love to know more details 🙏🏻 , specifically:
 - Do you have any other (Terraform) extensions installed?
    - If so, which ones?
    - If so, have you tried disabling all of those?
 - Can you confirm you have the latest version of the language server installed? (version can be seen in the first few lines of the relevant `Output` `terraform-ls` pane)

We have a long-running open thread on this topic https://github.com/hashicorp/vscode-terraform/issues/542 so I would prefer if you respond to these questions there while I close this one, just to keep the conversation in one place.

I hope you don't mind.
