### ISSUE TITLE
[Feature request] Color syntax: add scope for resource_type and resource_name

### ISSUE THREAD

**Issue by tringuyen-yw** [hashicorp/vscode-terraform#710]
Using VSCode Version: 1.58.2, OS: Linux x64 5.8.0-63-generic snap (Ubuntu 20.04.2)

Currently a resource type and resource identification are recognized as string. As such the color syntax is not very readable. Can you please add new editor scopes for:

* Terraform resource_type
* Terraform resource_name

To allow to configure the corresponding element with a different color syntax. The attached screenshot shows the desired effects using IntelliJ IDEA v2021.2

VS Code Color theme:
- [Customizing a Color Theme](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme)
- [Theme Color Reference](https://code.visualstudio.com/api/references/theme-color)

![VSCode_Terraform_colorSyntax_resource](https://user-images.githubusercontent.com/58445772/127780465-6e240207-68d4-4066-9796-675aa3257255.png)

**Comment by softveda** [comment]
I like this too.

**Comment by radeksimko** [comment]
Hi folks,
While #934, https://github.com/hashicorp/terraform-ls/pull/802 and  made it possible to distinguish between plain strings and labels I just wanted to note that we plan to still look into the original proposal - that is distinguishing between the resource type and name.

We track that under https://github.com/hashicorp/terraform-ls/issues/803 as all the relevant work will be done on the language server.
