### ISSUE TITLE
Provide opt out config option for ref count code lens

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/vscode-terraform#713]
### Use Cases

The most recent versions of the extension and LS introduced code lens for displaying reference counts above top level blocks and attributes.

<img src="https://user-images.githubusercontent.com/287584/125472525-01349c02-9d5b-4dd2-aad6-fa3780d171de.gif">

While many users may find this useful, some may find it distracting or just generally may not want it (https://github.com/hashicorp/terraform-ls/pull/584#issuecomment-891190519) and it would be useful if these users have a way of opting out of this code lens.

### Proposal

Introduce a new config option `enableReferenceCountCodeLens` (defaulting to `true`) which will prevent the client from registering the relevant feature

https://github.com/hashicorp/vscode-terraform/blob/b3d812edd5ec334f5c42e7df109cef50dd32b5ac/src/clientHandler.ts#L181

and as a result prevent the relevant client capability to be sent to the server, which would in turn prevent it from sending the code lens back.

**Comment by DoctorPolski** [comment]
Please, please, please.

Further, I feel such a potentially "invasive" feature should never have been implemented without the option to disable it.

**Comment by abroun** [comment]
+1
I'm also not a fan of something adding extra lines to my code, so I'd favour this being information that is only displayed when you hover over a referenced item, or having a very clear off switch if it can only be displayed inline.

In situations where you have a number of referenced items it's very distracting

![image](https://user-images.githubusercontent.com/270437/134498259-b74245be-acd7-4e59-9152-7cb8462d90d8.png)

**Comment by jpogran** [comment]
Hi @DoctorPolski and @abroun, thanks for the feedback. The CodeLens functionality placement is decided by VS Code, not our extension. This VS Code [issue](https://github.com/Microsoft/vscode/issues/23652#issuecomment-304025993) describes their rationale for not giving an option on placement or display. Unfortunately that is out of our hands.

The good news is, if you do not want any CodeLens displayed in any Terraform file right now, you can do so now with setting a language specific editor option:

```
"[terraform]": {
    "editor.codeLens": false
  },
```

This is a useful way to set editor settings per language, so each extension behaves as you desire without affecting other languages.

Alternately, if you do not want to see any CodeLens for anything ever, you can set the following without a language filter:

```
"editor.codeLens": false
```

In the longer term, it is common for extensions to create settings per CodeLens feature they add, so we will continue to look into that as we fill out the CodeLens functionality. There are more accelerators that we can add to the CodeLens line than just reference count.

**Comment by abroun** [comment]
Hi @jpogran, thank you for the reply. The placement makes more sense given the linked issue which also makes clear that my issue is with CodeLens rather than this use of it. :)

I'll follow your tip for turning off CodeLens for now. Appreciate the effort put in to provide and support this free extension.
