### ISSUE TITLE
Enhanced module support

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/vscode-terraform#715]
## Problem Statement

Terraform users use modules to package and reuse configuration. Users should not loose out on UX they get when editing resources, data sources etc. directly after "modularising" their configs and when leveraging 3rd party modules.

## User Impact

Any users of modules will benefit.

## Expected User Experience

Most UX features evolve around the [`module` block](https://www.terraform.io/docs/language/modules/syntax.html).

The overall aim is to help users introduce **new modules** to the configuration and help manage **existing modules** and _increase the chance_ that user will be provided with the following

 - completion
 - hover
 - accurate highlighting
 - relevant links (to docs)
 - go to references/definitions
 - installation/update via contextual code actions

for all modules in their configuration regardless of where the module comes from or whether it's installed.

## Proposal

 - https://github.com/hashicorp/vscode-terraform/issues/668
 - https://github.com/hashicorp/vscode-terraform/issues/669
 - https://github.com/hashicorp/vscode-terraform/issues/670
 - https://github.com/hashicorp/vscode-terraform/issues/672
 - https://github.com/hashicorp/vscode-terraform/issues/673
 - https://github.com/hashicorp/vscode-terraform/issues/698
 - https://github.com/hashicorp/vscode-terraform/issues/706
 - https://github.com/hashicorp/terraform-ls/issues/598
 - https://github.com/hashicorp/terraform-ls/issues/599
 - https://github.com/hashicorp/terraform-ls/issues/32
 - https://github.com/hashicorp/terraform-ls/issues/722
 - https://github.com/hashicorp/terraform-ls/issues/723
 - https://github.com/hashicorp/terraform-ls/issues/725
 - https://github.com/hashicorp/terraform-ls/issues/515

**Comment by timdhoffmann** [comment]
#668 has been closed but for me, module inputs are not working. 
Example, I am expecting a IntelliSense tooltip on hover 
![image](https://user-images.githubusercontent.com/9947384/179193292-8332e678-1d70-406b-b719-d4f7daeb47fa.png)

# Additional info

## VS Code
Version: 1.69.1 (user setup)
Commit: b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
Date: 2022-07-12T08:21:24.514Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

## Extension
HashiCorp Terraform
v2.23.0

## Platform
Windows 11
