### ISSUE TITLE
Register command to show references (#686) - not working if variable has a default

### ISSUE THREAD

**Issue by scott-doyland-burrows** [hashicorp/vscode-terraform#736]
https://github.com/hashicorp/vscode-terraform/pull/686

Please see attached screenshots.
Note how the ```lb``` variable shows no references in the first screenshot, but as soon as I remove the default for the variable, it then shows references, in the second screenshot attachement.

![no_ref](https://user-images.githubusercontent.com/61512176/129056718-ed9e7707-a3d5-4219-b4c4-6a9f56f26e2a.png)

![ref](https://user-images.githubusercontent.com/61512176/129056721-d97ff01e-3aad-4c76-8883-82ff86263cfd.png)

**Comment by radeksimko** [comment]
Hi @scott-doyland-burrows 
Thank you for the report.

Can you also share the configuration for all 4 references that refer to that variable?

Generally speaking the parser takes type constraints into account, e.g. if you refer to a boolean variable in a string argument, then it will not be counted as a valid reference. Variable without explicit `type` or `default` (which would infer a type from the value) is assumed to be of "any" type - in which case the matching is loose and argument type doesn't matter - it will be always counted.

It is possible that you are running into https://github.com/hashicorp/terraform-ls/issues/583 ?

**Comment by radeksimko** [comment]
Thank you for that added context @scott-doyland-burrows - this is helpful.

Based on the first screenshot I believe you ran into a problem which is tracked under https://github.com/hashicorp/vscode-terraform/issues/641 - basically the language server is (falsely) expecting `var.lb` to be of number type based on `count` type. This is indeed inaccurate, but fixing the inaccuracy involves adding support for the conditional expression (`X ? Y : Z`) which itself is tracked under https://github.com/hashicorp/terraform-ls/issues/528 (also linked from the first issue). There are many other expression types which are not recognized yet at this point.

As for the 2nd screenshot - you are certainly hitting a problem which is tracked under https://github.com/hashicorp/terraform-ls/issues/562 - `haa-dev.tfvars` is treated as a variables file which is _not_ autoloaded by Terraform.

That said we do not recognize references in _any_ `tfvars` files yet (not even the auto-loaded ones). I will create a separate issue to track that feature.

**Comment by radeksimko** [comment]
I just created https://github.com/hashicorp/terraform-ls/issues/618 to track the mentioned feature - feel free to subscribe to that issue.

I'm going to close this issue now - not because it's resolved - but because it makes it easier to track the smaller-scope issues individually and address them individually. I hope you don't mind.

Thank you for your report.
