### ISSUE TITLE
Research npm version

### ISSUE THREAD

**Issue by jpogran** [hashicorp/vscode-terraform#770]
## Problem Statement

In https://github.com/hashicorp/vscode-terraform/pull/661, we updated the npm package-lock.json to version 2. Version 2 lockfiles are from npm version 7. We set this project to use node 14.X which bundles npm 6.

## Proposal

We should research whether we should update to node 16.X and keep npm 7 or reset back to npm 6 and keep node 14.X.

**Comment by dbanck** [comment]
Resolved by https://github.com/hashicorp/vscode-terraform/pull/904
