### ISSUE TITLE
Publish preview builds to VS Code Marketplace

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/vscode-terraform#774]
## Problem Statement

Some users may want to help us test upcoming features before these even land in a release.

We do currently generate package on every commit to `main`, but the resulting vsix is quite hidden away from users, we have no idea whether users even use this and we have no documented process on how to install it or how to provide feedback.

## Expected User Experience

Users can find a dedicated Marketplace entry for a preview build, similar to the Go entry and are able to install it from there:

![Screenshot 2021-09-15 at 10 21 34](https://user-images.githubusercontent.com/287584/133407176-151a3729-8a55-4086-9d35-8f429b79201d.png)

https://marketplace.visualstudio.com/items?itemName=golang.go-nightly

## Proposal

The manifest we publish extension with would need to be modified to include `"preview": true`
https://code.visualstudio.com/api/references/extension-manifest

We can consider making this a default as it's a safer default for any accidental publishing.

We'll also need to repurpose the existing `Build` workflow to automate the publishing:
https://github.com/hashicorp/vscode-terraform/blob/main/.github/workflows/build.yml

**Comment by jpogran** [comment]
Just to clarify, this means registering a new extension, not just setting a value in `package.json`:

```
> code --list-extensions
golang.go
golang.go-nightly
```

**Comment by radeksimko** [comment]
Yep, that is what I meant - sorry for not being clear above. I do believe though that we can reuse the same `package.json` for both extensions.
