### ISSUE TITLE
Avoid executing `module.calls` for internal VS Code documents

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/vscode-terraform#817]
## Versions

This bug is reproducible in:
 - [x] the **latest** version of the extension (below)
 - [x] the **latest** version of the language server (below)

### Extension

```
2.16.0
```

### Language Server

```
0.23.0
```

### VS Code

```
1.61.1
```

### Operating System

```
macOS 10.15.7
```

### Steps To Reproduce

1. Open folder with some Terraform code
2. Open command palette
3. Pick `Preferences: Open Settings (JSON)`

### Expected Behavior

No request is sent to LS, no error is shown in case user opens preferences page.

### Actual Behavior

Error is shown

> URI "vscode-userdata:/Users/radeksimko/Library/Application%20Support/Code/User" is not valid

once the following request is sent to the server

```
2021/10/18 14:48:32 rpc_logger.go:29: Incoming request for "workspace/executeCommand" (ID 1): {"command":"5.terraform-ls.module.calls","arguments":["uri=vscode-userdata:/Users/radeksimko/Library/Application%20Support/Code/User"]}
2021/10/18 14:48:32 rpc_logger.go:45: Error for "workspace/executeCommand" (ID 1): [-32098] URI "vscode-userdata:/Users/radeksimko/Library/Application%20Support/Code/User" is not valid
```

**Comment by ericpaulsen** [comment]
I've upgraded to the latest language server version - `0.25.0` - and I'm still able to reproduce this bug. Is there a recommended path to resolving this?

**Comment by jpogran** [comment]
@ericpaulsen This was merged today and we haven't yet released the stable extension. If you would like to try it out now, the preview extension builds nightly so there should be a new build available tomorrow.
