### ISSUE TITLE
Improve client-side startup reliability

### ISSUE THREAD

**Issue by phinze** [hashicorp/vscode-terraform#819]
## Problem Statement

There has been a problem with the client side of the extension that has been occurring for awhile. We mostly fixed this in https://github.com/hashicorp/vscode-terraform/issues/778, but there are still cases where it happens. It's a race condition that happens when we try to do anything that uses terraform-ls (LS) before the client is fully connected to the LS, but it's sporadic because the LS is so fast to serve clients in 99.9% of cases. 

When these crashes happen, it's often silent and hidden in a log file and there is little to no indication to the user something is wrong. If the user does notice something is wrong, we need a lot of separate pieces of information from different places in the extension to help us figure out what is going on, and non-trivial for the user to find and give us. This causes a lot of back and forth in the GitHub issue until we get what we need, which is not a good experience for a user.

Then, when we do fix things or release new features, the user is prompted every time if they want to upgrade to the latest version. This prompt is outside of the existing VS Code update infrastructure because we download the LS separately from the VSIX. We release frequently, so this prompt can become tiresome.

## User Impact

Any user which uses the extension would be impacted.

## Expected User Experience

A user will be able to use our extension reliably in both single and multi-folder workspaces. Extension updates will happen silently in the background, respecting existing VS Code settings determining if an update occurs. In order for a user to be informed about the current state of the extension, the current state of the extension will be show in the status bar. If a problem occurs, there will be built in ways for the user to submit a bug report with all necessary information needed for us to troubleshoot. 

## Proposal

 - https://github.com/hashicorp/vscode-terraform/issues/816 - use one languageclient instead of one per folder
 - https://github.com/hashicorp/vscode-terraform/issues/760 - generate bug report command
 - https://github.com/hashicorp/vscode-terraform/issues/812 - autoupdate ls uses workspace.fs
 - https://github.com/hashicorp/vscode-terraform/issues/815 - respect extension autoupdate settings (#783)
 - https://github.com/hashicorp/vscode-terraform/issues/820 - bundle terraform-ls inside vsix

**Comment by jpogran** [comment]
The proposed work has been completed, so this epic can be closed
