### ISSUE TITLE
Unable to do a comment block on TFVARS files

### ISSUE THREAD

**Issue by mechastorm** [hashicorp/vscode-terraform#835]
## Versions

This bug is reproducible in:
 - [x] the **latest** version of the extension (below)
 - [x] the **latest** version of the language server (below)

VSCode version

```
Version: 1.62.0
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-03T15:24:41.297Z (1 day ago)
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.4.0
```

### Steps To Reproduce

1. Open a terraform file *.tfvars
2. Select Text
3. Do comment block via shortcut key `Shift + Cmd+ /`

### Expected Behavior

Code block selected in Terraform file

### Actual Behavior

Text stays as in
 
### Additional context

Comment block works on other files - for some weird reason Terraform files will refused to recognise code blocks.

**Comment by jpogran** [comment]
Hi @mechastorm, thank you for the report. I think you are using the wrong keyboard shortcut. The keyboard shortcut for block comments is `Shift + Option + A` as shown in https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf. The command `Cmd + /` toggles a single line comment.

Remember, these shortcuts change per OS you use. For example, using Windows I entered Shift + Alt + A and see it working:

![tfvar_block_comment](https://user-images.githubusercontent.com/272569/148990250-6b0bfea8-874c-4035-a283-2195b597b4a3.gif)

I'm going to close this issue, but please feel free to respond with an example if this isn't working for you.
