### ISSUE TITLE
terraform plugin not suggested for - depends on 

### ISSUE THREAD

**Issue by RoiSec** [hashicorp/vscode-terraform#838]
Hi 
"Depends on" basically get a list of items,
I do not understand why the first Vscode suggests me a resource and for the second resource, he did not suggest it.
If I write it manually It works.
What am I doing wrong?

I have  the HashiCorp Terraform addon v2.16.0

![image](https://user-images.githubusercontent.com/68992144/140661562-3b44bf52-9023-44e7-b58a-e2b48a069269.png)

### VS Code

vscode 1.62.0

### Terraform Version
Terraform v1.0.10
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.63.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.6.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1-->

**Comment by radeksimko** [comment]
Hi @RoiSec 
This is unfortunately an effect of currently incomplete expressions support in the language server.

The completion currently works for the first item in a list, amongst other limitations.

We track this under https://github.com/hashicorp/terraform-ls/issues/496 and this task is on the near-term roadmap.
With that in mind I'm going to close this issue to keep discussion in one place, but feel free to comment under that issue if you have any related ideas or suggestions.
