### ISSUE TITLE
Error when Terraform file is updated. Git file status never updates.

### ISSUE THREAD

**Issue by rednevals** [hashicorp/vscode-terraform#847]
## Versions

This bug is reproducible in:
 - [ ] the **latest** version of the extension (below)
 
### Extension
```
v2.16.0
```

### Language Server
```
Launching language server: /home/sxl73/.vscode-server/data/User/globalStorage/hashicorp.terraform/bin/terraform-ls serve
2021/11/10 16:01:30 serve_command.go:162: Starting terraform-ls 0.24.0
2021/11/10 16:01:30 service.go:87: Preparing new session ...
```

### VS Code
```
Version: 1.62.1 (user setup)
Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
Date: 2021-11-05T10:57:55.946Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```

### Operating System
```
Edition	Windows 10 Pro
Version	21H1
Installed on	‎3/‎26/‎2021
OS build	19043.1348
Experience	Windows Feature Experience Pack 120.2212.3920.0

WSL 2 -> Ubuntu 20.04.3 LTS
```

### Terraform Version
```
Terraform v1.0.10
on linux_amd64
```

### Steps To Reproduce
After upgrading to latest VSCode, when I edit a terraform file, the status takes a very long time to update in the editor and in the source control view. The log window has the following error:

```
[2021-11-10 16:22:37.370] [renderer1] [error] main.tf (13,19): position outside of any attribute name, value or block: Error: main.tf (13,19): position outside of any attribute name, value or block
	at handleResponse (/home/sxl73/.vscode-server/extensions/hashicorp.terraform-2.16.0/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
	at processMessageQueue (/home/sxl73/.vscode-server/extensions/hashicorp.terraform-2.16.0/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
	at Immediate.<anonymous> (/home/sxl73/.vscode-server/extensions/hashicorp.terraform-2.16.0/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
	at processImmediate (internal/timers.js:461:21)
```

Change was made:
![image](https://user-images.githubusercontent.com/7444378/141198336-17c946a2-b2d2-4d92-9945-ee305849713d.png)

But Git status is not updated...

### Expected Behavior
Status of file should have been indicated in relation to Git repository.

### Actual Behavior
Status is never update, or takes a very long time to appear.
 
When the file is closed, returning to the editor does not show the changes made. But, the file on the file system does show the change as does Git:
```
diff --git a/setup/main.tf b/setup/main.tf
index 7589c8a..2969e02 100644
--- a/setup/main.tf
+++ b/setup/main.tf
@@ -3,8 +3,9 @@ provider "aws" {
   region  = "us-east-1"
   default_tags {
     tags = {
-      Name      = "CloudBolt"
-      Terraform = "true"
+      Business-Unit = "IT"
+      Name          = "CloudBolt"
+      Terraform     = "true"
     }
```

**Comment by jpogran** [comment]
Hi @rednevals, thanks for the report but I'm not sure that the Terraform extension is involved here. The Terraform extension doesn't interact directly with Git, file changes and other git operations are handled in the SCM view in VS Code.

Taking a step back, you're on Windows using WSL with an Ubuntu distro. I can't tell from the screenshot or the error you pasted, but are you running VS Code inside WSL using a Windows filesystem mount like `/mnt/c/Users/james/src/hashicorp`? If so that will be slower than using the native Linux filesystem. This is for the VS Code Remote Extension and Docker, but the information applies here as well: https://docs.docker.com/desktop/windows/wsl/#best-practices

**Comment by jpogran** [comment]
Since this has been open for a long time, I'm going to lock and close this issue now. Please do open a new issue if problems persist for you.
