### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by PascalBourdier** [hashicorp/vscode-terraform#861]
- Issue Type: `Bug`
- Extension Name: `terraform`
- Extension Version: `2.16.0`
- OS Version: `Darwin x64 20.6.0`
- VS Code version: `1.62.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jpogran** [comment]
Hi @PascalBourdier, we need more information about what the problem is and what was happening when it occurred.
