### ISSUE TITLE
Reuse terraform-ls process between multiple vscode instances

### ISSUE THREAD

**Issue by fernandomoraes** [hashicorp/vscode-terraform#865]
## Versions

This feature does not yet exist in:
 - [x] the **latest** version of the extension (below)
 - [x] the **latest** version of the language server (below)

### Extension
```
v2.17.0
```

### Language Server
```
terraform-ls 0.25.0
```

## Problem Statement
I think that would be nice if we could reuse  terraform-ls process between multiple vscode instances. Today, the following situation happens:

![image](https://user-images.githubusercontent.com/2366763/144726366-c5fb2b16-e5c8-4e8b-9f3c-5d34ae4b9047.png)

**Comment by jpogran** [comment]
@fernandomoraes thank you for the suggestion. Our language server supports [multi-folder workspaces](https://code.visualstudio.com/docs/editor/workspaces). If you add more than one folder to a workspace, a single terraform-ls process will be used.

**Comment by fernandomoraes** [comment]
@jpogran nice, thank for your feedback!

**Comment by fernandomoraes** [comment]
feel free to close the issue
