### ISSUE TITLE
terraform-ls.terraformExecPath setting not taken into account

### ISSUE THREAD

**Issue by ks1977** [hashicorp/vscode-terraform#919]
Hi, 

I want to change the location of the terraform-ls.exe because in our company it's not allowed to run exe's from other directories than "C:\Program Files" etc.

In the Windows event viewer I get this AppLocker entry:
_%OSDRIVE%\USERS\<myusername>\APPDATA\ROAMING\CODE\USER\GLOBALSTORAGE\HASHICORP.TERRAFORM\BIN\TERRAFORM-LS.EXE was prevented from running._

Then I noticed that the path to terraform-ls can be changed in the extension settings, so I did that but it doesn't seem to take this change into account.  I tried both: pointing to the folder containing the exe and pointing to the exe itself.  No success, it still tries to execute the default one under appdata.

Can you fix this please?

**Comment by dbanck** [comment]
Hi,

Thanks for taking the time to report this. Two different settings might help you get around your issue.

The extension tries to launch the downloaded (or bundled) Terraform language server binary from an internal VS Code directory, like displayed in your error message: `GLOBALSTORAGE\HASHICORP.TERRAFORM\BIN\TERRAFORM-LS.EXE `

You can override this behavior by specifying the path to the language server binary in the VS Code settings:
```json
"terraform.languageServer": {
  "pathToBinary": "<allowedBinaryPath>\terraform-ls.exe",
},
```

Please keep in mind that if you specify a path here, the extension won't automatically update the language server in the background. So to keep using the latest version of the language server, you'll need to update the binary yourself.

The second setting we provide is for the Terraform binary itself. The language server launches Terraform for specific commands like `init` or `validate`. You can control the location of the Terraform binary by using `terraform-ls.terraformExecPath`.

```json
"terraform-ls.terraformExecPath": "<allowedBinaryPath>\terraform.exe",
```

By pointing both setting paths to binaries inside `C:\Program Files`, you should be able to avoid the AppLocker error.

**Comment by ks1977** [comment]
Thank you very much! That indeed solves my issue.
