### ISSUE TITLE
Missing highlighting for nested for expressions

### ISSUE THREAD

**Issue by dbanck** [hashicorp/vscode-terraform#926]
The syntax highlighting for `for` expressions currently only works if they start with a `[` or `{` in the same line.

When using a `for` expression for filtering elements, the expression is not highlighted correctly.

![CleanShot 2022-02-08 at 17 51 18](https://user-images.githubusercontent.com/45985/153035656-2bc1d194-dfc1-47c4-b14a-8acbe43a8296.png)

**Comment by radeksimko** [comment]
Just for clarification - as I wasn't sure about this myself - the tokens in the expression are exactly the same in both cases, there's just extra newline. In other words the `{` and `}` are still considered as part of the `for` expression even if they're on separate lines.

See https://go.dev/play/p/m13bKnvCLpt
