### ISSUE TITLE
HCL syntax highlighting should be a part of this extension

### ISSUE THREAD

**Issue by leighstillard** [hashicorp/vscode-terraform#987]
## Versions

This feature does not yet exist in: v2.18.0

### Extension

```
Go, Hashicorp Terraform, Jupyter, Python
```

## Problem Statement

As discussed in [Issue #453](https://github.com/hashicorp/vscode-terraform/issues/453), HCL highlighting is not yet enabled.  The previous issue directed the users to other extensions, however it seems none exist at this time. A search for HCL highlighting in vscode goes to issue #453. 

I'd like to request this functionality please.

## Expected User Experience

Appropriate syntax highlighting for HCL files. 

## References

[Issue #453](https://github.com/hashicorp/vscode-terraform/issues/453)

**Comment by dbanck** [comment]
Thanks for taking the time to raise this issue, @leighstillard.

Highlighting HCL files is something we're actively working on and expecting to release something soon. We'll keep you posted. Thanks for your patience!

**Comment by radeksimko** [comment]
We have recently took over and updated the HCL extension, which now also supports HCL2. You can read more about it at https://www.hashicorp.com/blog/announcing-the-hcl-extension-for-visual-studio-code-0-1

You can install it from https://marketplace.visualstudio.com/items?itemName=HashiCorp.HCL

Any feedback is welcomed at https://github.com/hashicorp/vscode-hcl
