### ISSUE TITLE
Wrong terraform language server binary

### ISSUE THREAD

**Issue by elizabeth-dev** [hashicorp/vscode-terraform#988]
## Versions

This bug is reproducible in:
 - [x] the **latest** version of the extension (below)
 - [x] the **latest** version of the language server (below)

### Extension

```
2.20.0
```

### Language Server

```
(Unable to find)
```

### VS Code

```
1.65.1
```

### Operating System

```
Local: macOS Monterey 12.2.1
Remote: Arch Linux
```

### Terraform Version

```
1.1.6
```

### Steps To Reproduce

When using the Remote Development feature of VSCode via SSH, the extension downloads the language server binary according to the local platform & arch, not the remote host.

For example, in my case, I'm connecting from my M1 Macbook (macOS, arm64) to a t3a.large instance in AWS (Linux, amd64), and when I check the downloaded binary in the server using the `file` command, i get the following output:
```
$ file /fakepath/.vscode-server/extensions/hashicorp.terraform-2.20.0/bin/terraform-ls
/fakepath/.vscode-server/extensions/hashicorp.terraform-2.20.0/bin/terraform-ls: Mach-O 64-bit arm64 executable, flags:<|DYLDLINK|PIE>
```
(Note the `Mach-O arm64` part)

### Expected Behavior

When connecting to a remote host, the extension should consider the platform and architecture from the remote, not from the local machine.

### Actual Behavior

The extension is using the local platform and architecture when downloading the language server binary, making it unable to execute the language server.

**Comment by jpogran** [comment]
Thanks for the detailed repo @elizabeth-dev, I'm sorry this isn't working but I do know what is causing this. I've posted a short-term workaround for you to use right now, then a longer explanation with the long term fix I can implement.

Short Term:

After opening your workspace using the SSH Extension, make sure that the Terraform Extension is installed to the remote by clicking `Install in SSH`, similar to how I have it here with the WSL extension:

![image](https://user-images.githubusercontent.com/272569/157331831-7a22ff4d-7bd2-4078-bf92-5aefaa0153a0.png)

Once clicked, VS Code will download the appropriate platform for the remote target. It may take awhile to download and transfer, depending on the speed of your connection.

![image](https://user-images.githubusercontent.com/272569/157331766-be80484e-3fb3-4e5a-8570-2b80d4ad84dd.png)

You can add the following to your VS Code settings in the short term to make it choose the remote first if available:

```json
"remote.extensionKind": {
  "hashicorp.terraform": ["workspace","ui"]
 },
```

There may still be some wonkiness with it choosing which place to install the extension until I implement to long term fix below. Once we implement the long term fix, you won't have to do this anymore.

Long Term:

The terraform extension is being installed locally and not remotely (see [this link](https://code.visualstudio.com/docs/remote/ssh#_managing-extensions) for detailed explanation). If you install the Terraform extension using the SSH extension, it should pick the correct platform for your target.

The decision logic on what extension to install on the remote host/container/WSL instance is handled by VS Code, not our extension **but** it is up to the extension to [advertise itself properly](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location). In my limited testing, the default registration worked, but as you show it is not comprehensive.

To fix this I'll add this to our manifest:

```json
"extensionKind": [
  "workspace",
  "ui"
]
```

I'll update this ticket when we've got a fix planned and tested.

**Comment by jpogran** [comment]
This is now in stable as well. Please let us know if this has fixed your issue.

**Comment by jpogran** [comment]
@elizabeth-dev I'm going to close this out. If you encounter anything, please open a new issue and let us know!
